# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "820ff289-52b1-4c8f-8705-a88c51f147ce",
# META       "default_lakehouse_name": "GOLD_LAKEHOUSE",
# META       "default_lakehouse_workspace_id": "890304bc-64e8-46be-93d9-8ea5a5a56669",
# META       "known_lakehouses": [
# META         {
# META           "id": "820ff289-52b1-4c8f-8705-a88c51f147ce"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInRead", "LEGACY")
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY")
spark.conf.set("spark.sql.parquet.vorder.enabled", "true")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# **BHF Common Facts**

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_MBR_MDCL_PROD_DTL_BHF
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC 	PROD_KEY INT,
# MAGIC 	SNAP_YEAR_MNTH_NBR INT,
# MAGIC 	ZIP_KEY INT,
# MAGIC 	CMPNY_CF_KEY INT,
# MAGIC 	EDM_MBR_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC 	FUNDG_CF_KEY INT,
# MAGIC 	GNDR_KEY INT,
# MAGIC 	GRP_CNTRCT_SIZE_KEY INT,
# MAGIC 	GRP_MBR_SIZE_KEY INT,
# MAGIC 	HW_KEY INT,
# MAGIC 	INCRD_YEAR_MNTH_NBR INT,
# MAGIC 	JAA_KEY INT,
# MAGIC 	MBU_CF_KEY INT,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY INT,
# MAGIC 	PROD_CF_KEY INT,
# MAGIC 	STNDRD_AGE_MNTH_KEY INT,
# MAGIC 	EOM_MBR_CNT INT,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT INT,
# MAGIC 	GRP_MBR_RNG_KEY INT
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_MBR_MDCL_PROD_DTL_BHF
# MAGIC SELECT  
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	PROD_KEY,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	ZIP_KEY,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC 	HW_KEY,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	JAA_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	EOM_MBR_CNT,
# MAGIC 	PRORTD_MBR_MNTH_CNT,
# MAGIC 	SBSCRBR_CNT,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBRSHP;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC --FACT_WBS_MBR_PRCG / FACT_WBS_MBR_PRCG_PGM
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PGM_BHF
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC 	SNAP_YEAR_MNTH_NBR INT,
# MAGIC 	PROD_KEY INT,
# MAGIC 	ZIP_KEY INT,
# MAGIC 	CMPNY_CF_KEY INT,
# MAGIC 	EDM_MBR_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC 	FUNDG_CF_KEY INT,
# MAGIC 	GRP_CNTRCT_SIZE_KEY INT,
# MAGIC 	GRP_MBR_SIZE_KEY INT,
# MAGIC 	GNDR_KEY INT,
# MAGIC 	HW_KEY INT,
# MAGIC 	INCRD_YEAR_MNTH_NBR INT,
# MAGIC 	JAA_KEY INT,
# MAGIC 	MBU_CF_KEY INT,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY INT,
# MAGIC 	PFOL_YEAR_NBR INT,
# MAGIC 	PROD_CF_KEY INT,
# MAGIC 	STNDRD_AGE_MNTH_KEY INT,
# MAGIC 	EOM_MBR_CNT INT,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT INT,
# MAGIC 	COST_AMT Double,
# MAGIC 	RVNU_AMT Double,
# MAGIC 	PRCG_COST_PEPM_AMT Double,
# MAGIC 	PRCG_COST_PMPM_AMT Double,
# MAGIC 	PRCG_RVNU_PEPM_AMT Double,
# MAGIC 	PRCG_RVNU_PMPM_AMT Double,
# MAGIC 	GRP_MBR_RNG_KEY INT
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PGM_BHF
# MAGIC SELECT  
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	PROD_KEY,
# MAGIC 	ZIP_KEY,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	HW_KEY,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	JAA_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY,
# MAGIC 	PFOL_YEAR_NBR,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	EOM_MBR_CNT,
# MAGIC 	PRORTD_MBR_MNTH_CNT,
# MAGIC 	SBSCRBR_CNT,
# MAGIC 	COST_AMT,
# MAGIC 	RVNU_AMT,
# MAGIC 	PRCG_COST_PEPM_AMT,
# MAGIC 	PRCG_COST_PMPM_AMT,
# MAGIC 	PRCG_RVNU_PEPM_AMT,
# MAGIC 	PRCG_RVNU_PMPM_AMT,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_PRCG_PGM;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# **BHF Specific Facts**

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC --WORK_ADIM_PRDA_BHF_IVR_CALL_DTL
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_ADIM_PRDA_BHF_IVR_CALL_DTL_BHF
# MAGIC (
# MAGIC     SNAP_YEAR_MNTH_NBR INT,
# MAGIC     INCRD_YEAR_MNTH_NBR INT,
# MAGIC     IVR_TFN STRING,
# MAGIC     MNTHLY_CALL_CNT DOUBLE
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_ADIM_PRDA_BHF_IVR_CALL_DTL_BHF
# MAGIC SELECT 
# MAGIC     SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC     IVR_TFN,
# MAGIC     MNTHLY_CALL_CNT
# MAGIC from GOLD_LAKEHOUSE.dbo.FACT_PRDA_BHF_IVR;
# MAGIC 


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC --FACT_PRDA_BHF_MBR
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_ADIM_PRDA_BHF_MBR_DTL_BHF
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC 	CTGRY_NM STRING,
# MAGIC 	MCID_EDM_MBR_RANK_NBR INTEGER,
# MAGIC     SNAP_YEAR_MNTH_NBR INT,
# MAGIC 	INCRD_YEAR_MNTH_NBR INT,
# MAGIC 	EDM_MBR_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 	PROD_KEY INT,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC 	MCID BIGINT,
# MAGIC 	STNDRD_AGE_MNTH_KEY INT,
# MAGIC 	GNDR_KEY INT,
# MAGIC 	ZIP_KEY INT,
# MAGIC 	FUNDG_CF_KEY INT,
# MAGIC 	MBU_CF_KEY INT,
# MAGIC 	JAA_KEY INT,
# MAGIC 	PROD_CF_KEY INT,
# MAGIC 	CMPNY_CF_KEY INT,
# MAGIC 	BHFP_KEY INT,
# MAGIC 	CALL_CHAT_TYPE_KEY INT,
# MAGIC 	DGTL_STTS_KEY INT,
# MAGIC 	GSTTNL_DLVRY_AGE_KEY INT,
# MAGIC 	MBR_AGE_KEY INT,
# MAGIC 	LIFE_CTGRY_KEY INT,
# MAGIC 	BRTH_WT_KEY INT,
# MAGIC 	BHF_MBR_TYPE_KEY INT,
# MAGIC 	PRFLG_CMPLT_PHASE_KEY INT,
# MAGIC 	--DLVRY_MNTH_KEY DOUBLE,
# MAGIC 	MTRNTY_RISK_LVL_KEY INT,
# MAGIC 	BHF_RWRD_ACTV_PRFL_KEY INT,
# MAGIC 	BHF_DLVRY_CHK_IN_QSTNR_IND STRING,
# MAGIC 	BHF_INTRCTN_IND STRING,
# MAGIC 	BHF_PRGNNCY_LOSS_QSTNR_IND STRING,
# MAGIC 	BLK_MTRNL_IND STRING,
# MAGIC 	BRST_FEEDG_IND STRING,
# MAGIC 	EPDSCRN_IND STRING,
# MAGIC 	GSTTNL_HTN_IND STRING,
# MAGIC 	LGBTQ_IND STRING,
# MAGIC 	--OUTPT_VAL_CD STRING,
# MAGIC 	PRGNNCY_IND STRING,
# MAGIC 	BHF_RWRD_ACTV_PRFL_CNT DOUBLE,
# MAGIC 	BHF_RWRD_POST_DLVRY_QSTNR_CNT DOUBLE,
# MAGIC 	BHF_RWRD_PRE_DLVRY_QSTNR_CNT DOUBLE,
# MAGIC 	BHF_RWRD_PRGNNCY_SCRNG_CNT DOUBLE,
# MAGIC 	BHF_STSFCN_SCOR_NBR DOUBLE,
# MAGIC 	CARE_COCH_CHAT_CNT DOUBLE,
# MAGIC 	EMRGNCY_DEPT_VST_CNT DOUBLE,
# MAGIC 	GRP_CNTRCT_SIZE_NBR DOUBLE,
# MAGIC 	GRP_CNTRCT_SIZE_SORT_NBR DOUBLE,
# MAGIC 	GRP_MBR_SIZE_NBR DOUBLE,
# MAGIC 	GRP_MBR_SIZE_SORT_NBR DOUBLE,
# MAGIC 	DERIVD_SORT_GRP_MBR_SIZE_RNG_TXT STRING,
# MAGIC 	GSTTNL_DLVRY_AGE_NBR DOUBLE,
# MAGIC 	HLTH_PGM_RPRSNTV_CHAT_CNT DOUBLE,
# MAGIC 	NICU_AMT DOUBLE,
# MAGIC 	NICU_SPNT_DAYS_NBR DOUBLE,
# MAGIC 	TOTL_INCMNG_MNTHLY_TLPHN_CALLS_CNT DOUBLE,
# MAGIC 	TOTL_OUTGNG_MNTHLY_TLPHN_CALLS_CNT DOUBLE,
# MAGIC 	PRFL_CREAT_DT DATE,
# MAGIC     DGTL_RGSTRD_DT DATE,
# MAGIC     RGSTRD_DT DATE,
# MAGIC     MBR_GSTTNL_AGE_NBR DOUBLE,
# MAGIC 	GRP_MBR_RNG_KEY INT,
# MAGIC 	GRP_CNTRCT_SIZE_KEY INT,
# MAGIC 	GRP_MBR_SIZE_KEY INT,
# MAGIC 	--M_ID INTEGER,
# MAGIC 	AGE_YEAR_NBR INT,
# MAGIC 	MCID_RANK_NBR BIGINT
# MAGIC 	--MCID_INCRD_YEAR_MNTH_RANK_NBR DOUBLE
# MAGIC 	  -- NEW FLAG COLUMNS
# MAGIC     --PREGNANCY_LOSS_FLAG DOUBLE,
# MAGIC     --DELIVERY_CHECKIN_FLAG DOUBLE,
# MAGIC     --POSTNATAL_DEPRESSION_FLAG DOUBLE,
# MAGIC     --CATEGORY_NAME STRING
# MAGIC 	--RN INTEGER
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_ADIM_PRDA_BHF_MBR_DTL_BHF
# MAGIC SELECT  
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	CTGRY_NM ,
# MAGIC 	MCID_EDM_MBR_RANK_NBR ,
# MAGIC         SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	PROD_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	MCID,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	ZIP_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	JAA_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	BHFP_KEY,
# MAGIC 	CALL_CHAT_TYPE_KEY,
# MAGIC 	DGTL_STTS_KEY,
# MAGIC 	GSTTNL_DLVRY_AGE_KEY,
# MAGIC 	MBR_AGE_KEY,
# MAGIC 	LIFE_CTGRY_KEY,
# MAGIC 	BRTH_WT_KEY,
# MAGIC 	BHF_MBR_TYPE_KEY,
# MAGIC 	PRFLG_CMPLT_PHASE_KEY,
# MAGIC 	--DLVRY_MNTH_KEY,
# MAGIC 	MTRNTY_RISK_LVL_KEY,
# MAGIC 	BHF_RWRD_ACTV_PRFL_KEY,
# MAGIC 	BHF_DLVRY_CHK_IN_QSTNR_IND,
# MAGIC 	BHF_INTRCTN_IND,
# MAGIC 	BHF_PRGNNCY_LOSS_QSTNR_IND,
# MAGIC 	BLK_MTRNL_IND,
# MAGIC 	BRST_FEEDG_IND,
# MAGIC 	EPDSCRN_IND,
# MAGIC 	GSTTNL_HTN_IND,
# MAGIC 	LGBTQ_IND,
# MAGIC 	--OUTPT_VAL_CD,
# MAGIC 	PRGNNCY_IND,
# MAGIC 	BHF_RWRD_ACTV_PRFL_CNT,
# MAGIC 	BHF_RWRD_POST_DLVRY_QSTNR_CNT,
# MAGIC 	BHF_RWRD_PRE_DLVRY_QSTNR_CNT,
# MAGIC 	BHF_RWRD_PRGNNCY_SCRNG_CNT,
# MAGIC 	BHF_STSFCN_SCOR_NBR,
# MAGIC 	CARE_COCH_CHAT_CNT,
# MAGIC 	EMRGNCY_DEPT_VST_CNT,
# MAGIC 	GRP_CNTRCT_SIZE_NBR,
# MAGIC 	GRP_CNTRCT_SIZE_SORT_NBR,
# MAGIC 	GRP_MBR_SIZE_NBR,
# MAGIC 	GRP_MBR_SIZE_SORT_NBR,
# MAGIC 	DERIVD_SORT_GRP_MBR_SIZE_RNG_TXT,
# MAGIC 	GSTTNL_DLVRY_AGE_NBR,
# MAGIC 	HLTH_PGM_RPRSNTV_CHAT_CNT,
# MAGIC 	NICU_AMT,
# MAGIC 	NICU_SPNT_DAYS_NBR,
# MAGIC 	TOTL_INCMNG_MNTHLY_TLPHN_CALLS_CNT,
# MAGIC 	TOTL_OUTGNG_MNTHLY_TLPHN_CALLS_CNT,
# MAGIC 	CAST(PRFL_CREAT_DT AS DATE) AS PRFL_CREAT_DT,
# MAGIC     CAST(DGTL_RGSTRD_DT AS DATE) AS DGTL_RGSTRD_DT,
# MAGIC     CAST(RGSTRD_DT AS DATE) AS DGTL_RGSTRD_DT,
# MAGIC     MBR_GSTTNL_AGE_NBR,
# MAGIC 	GRP_MBR_RNG_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY ,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC     --DENSE_RANK() OVER (ORDER BY FACT_PRDA_BHF_MBR.MCID ASC) AS M_ID,
# MAGIC 	AGE_YEAR_NBR,
# MAGIC 	MCID_RANK_NBR
# MAGIC 	--MCID_INCRD_YEAR_MNTH_RANK_NBR
# MAGIC 	--CASE WHEN BHF_PRGNNCY_LOSS_QSTNR_IND = 'Y' THEN 1 ELSE 0 END as PREGNANCY_LOSS_FLAG,
# MAGIC     --CASE WHEN BHF_DLVRY_CHK_IN_QSTNR_IND = 'Y' THEN 1 ELSE 0 END as DELIVERY_CHECKIN_FLAG,
# MAGIC     --CASE WHEN EPDSCRN_IND = 'Y' THEN 1 ELSE 0 END as POSTNATAL_DEPRESSION_FLAG,
# MAGIC 	--CASE WHEN BHF_DLVRY_CHK_IN_QSTNR_IND ='Y' THEN 'Delivery Check-in'
# MAGIC     --WHEN EPDSCRN_IND ='Y' THEN 'Post-Natal Depression (EPDS)'
# MAGIC     --WHEN BHF_PRGNNCY_LOSS_QSTNR_IND= 'Y'  THEN 'Pregnancy Loss/Deleting a Pregnancy'
# MAGIC    	--END CATEGORY_NAME
# MAGIC /*ROW_NUMBER() OVER (
# MAGIC         PARTITION BY MCID, INCRD_YEAR_MNTH_NBR
# MAGIC         ORDER BY CAST(EDL_LOAD_DTM AS DATE) DESC,    
# MAGIC                  COALESCE(LIFE_CTGRY_KEY, -1) DESC    
# MAGIC     ) AS RN*/
# MAGIC 	
# MAGIC 	
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_PRDA_BHF_MBR
# MAGIC 	--WHERE INCRD_YEAR_MNTH_NBR BETWEEN 
# MAGIC --CAST (date_format(add_months(current_date(),-6),'yyyyMM') AS DECIMAL(6,0)) and
# MAGIC --CAST (date_format(current_date(),'yyyyMM')AS DECIMAL(6,0))
# MAGIC 	


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC -- Creating aggregated table TO Gold lakehouse
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.PRDA_BHF_MBR_Aggregated_BHF AS
# MAGIC SELECT 
# MAGIC     -- From WORK_ADIM (Gold table)
# MAGIC     mbr.MCID_RANK_NBR,
# MAGIC     mbr.PRGNNCY_IND,
# MAGIC     
# MAGIC     -- Dimension keys, count columns
# MAGIC     mbr.INCRD_YEAR_MNTH_NBR,
# MAGIC     mbr.EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC     mbr.GNDR_KEY,
# MAGIC     mbr.MBR_AGE_KEY,
# MAGIC     mbr.DGTL_STTS_KEY,
# MAGIC     mbr.MTRNTY_RISK_LVL_KEY,
# MAGIC     mbr.PRFLG_CMPLT_PHASE_KEY,
# MAGIC     mbr.LIFE_CTGRY_KEY,
# MAGIC     mbr.BHF_RWRD_ACTV_PRFL_KEY,
# MAGIC     mbr.MCID_EDM_MBR_RANK_NBR,
# MAGIC     mbr.MCID,
# MAGIC     mbr.EDM_MBR_ACCT_KEY,
# MAGIC     mbr.CTGRY_NM,
# MAGIC     mbr.BHF_RWRD_ACTV_PRFL_CNT,
# MAGIC     mbr.BHF_RWRD_PRE_DLVRY_QSTNR_CNT,
# MAGIC     mbr.BHF_RWRD_PRGNNCY_SCRNG_CNT,
# MAGIC     mbr.BHF_RWRD_POST_DLVRY_QSTNR_CNT,
# MAGIC     
# MAGIC     -- Aggregated measure
# MAGIC     COUNT(DISTINCT mbr.MCID) AS MCID_Count
# MAGIC     
# MAGIC FROM GOLD_LAKEHOUSE.dbo.WORK_ADIM_PRDA_BHF_MBR_DTL mbr
# MAGIC 
# MAGIC GROUP BY
# MAGIC     mbr.INCRD_YEAR_MNTH_NBR,
# MAGIC     mbr.MCID_RANK_NBR,
# MAGIC     mbr.PRGNNCY_IND,
# MAGIC     mbr.EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC     mbr.GNDR_KEY,
# MAGIC     mbr.MBR_AGE_KEY,
# MAGIC     mbr.DGTL_STTS_KEY,
# MAGIC     mbr.MTRNTY_RISK_LVL_KEY,
# MAGIC     mbr.PRFLG_CMPLT_PHASE_KEY,
# MAGIC     mbr.LIFE_CTGRY_KEY,
# MAGIC     mbr.BHF_RWRD_ACTV_PRFL_KEY,
# MAGIC     mbr.MCID_EDM_MBR_RANK_NBR,
# MAGIC     mbr.MCID,
# MAGIC     mbr.EDM_MBR_ACCT_KEY,
# MAGIC     mbr.CTGRY_NM,
# MAGIC     mbr.BHF_RWRD_ACTV_PRFL_CNT,
# MAGIC     mbr.BHF_RWRD_PRE_DLVRY_QSTNR_CNT,
# MAGIC     mbr.BHF_RWRD_PRGNNCY_SCRNG_CNT,
# MAGIC     mbr.BHF_RWRD_POST_DLVRY_QSTNR_CNT;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark",
# META   "frozen": true,
# META   "editable": false
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.BHF_MCID_Month_Calls AS
# MAGIC WITH ranked AS (
# MAGIC   SELECT
# MAGIC     MCID,
# MAGIC     INCRD_YEAR_MNTH_NBR,
# MAGIC     TOTL_INCMNG_MNTHLY_TLPHN_CALLS_CNT AS InboundCalls,
# MAGIC     TOTL_OUTGNG_MNTHLY_TLPHN_CALLS_CNT AS OutboundCalls,
# MAGIC     CARE_COCH_CHAT_CNT AS Wildflower_Care_Coach_Chats_Base,
# MAGIC     HLTH_PGM_RPRSNTV_CHAT_CNT AS Elevance_Health_Program_Rep_BHF_Chats_Base,
# MAGIC     --ROW_NUMBER() OVER (
# MAGIC       --PARTITION BY MCID, INCRD_YEAR_MNTH_NBR
# MAGIC       --ORDER BY CAST(EDL_LOAD_DTM AS DATE) DESC,
# MAGIC         --       COALESCE(LIFE_CTGRY_KEY, -1) DESC
# MAGIC     --) 
# MAGIC     MCID_INCRD_YEAR_MNTH_RANK_NBR AS RN,
# MAGIC     EDM_MBR_ACCT_KEY,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC     PROD_KEY,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY,
# MAGIC     STNDRD_AGE_MNTH_KEY,
# MAGIC     GNDR_KEY,
# MAGIC     ZIP_KEY,
# MAGIC     FUNDG_CF_KEY,
# MAGIC     MBU_CF_KEY,
# MAGIC     JAA_KEY,
# MAGIC     PROD_CF_KEY,
# MAGIC     CMPNY_CF_KEY,
# MAGIC     BHFP_KEY,
# MAGIC     CALL_CHAT_TYPE_KEY,
# MAGIC     DGTL_STTS_KEY,
# MAGIC     GSTTNL_DLVRY_AGE_KEY,
# MAGIC     MBR_AGE_KEY,
# MAGIC     LIFE_CTGRY_KEY,
# MAGIC     BRTH_WT_KEY,
# MAGIC     BHF_MBR_TYPE_KEY,
# MAGIC     PRFLG_CMPLT_PHASE_KEY,
# MAGIC     DLVRY_MNTH_KEY,
# MAGIC     MTRNTY_RISK_LVL_KEY,
# MAGIC     BHF_RWRD_ACTV_PRFL_KEY,
# MAGIC     GRP_MBR_RNG_KEY,
# MAGIC     GRP_CNTRCT_SIZE_KEY,
# MAGIC     GRP_MBR_SIZE_KEY
# MAGIC   FROM GOLD_LAKEHOUSE.dbo.FACT_PRDA_BHF_MBR
# MAGIC   --WHERE INCRD_YEAR_MNTH_NBR BETWEEN 
# MAGIC     --    CAST(date_format(add_months(current_date(), -37), 'yyyyMM') AS DECIMAL(6,0))
# MAGIC     --AND CAST(date_format(current_date(), 'yyyyMM') AS DECIMAL(6,0))
# MAGIC )
# MAGIC SELECT
# MAGIC   MCID,
# MAGIC   INCRD_YEAR_MNTH_NBR,
# MAGIC   InboundCalls,
# MAGIC   OutboundCalls,
# MAGIC   Wildflower_Care_Coach_Chats_Base,
# MAGIC   Elevance_Health_Program_Rep_BHF_Chats_Base,
# MAGIC   RN,
# MAGIC   EDM_MBR_ACCT_KEY,
# MAGIC   EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC   PROD_KEY,
# MAGIC   EDM_CLNT_GRP_ACCT_KEY,
# MAGIC   STNDRD_AGE_MNTH_KEY,
# MAGIC   GNDR_KEY,
# MAGIC   ZIP_KEY,
# MAGIC   FUNDG_CF_KEY,
# MAGIC   MBU_CF_KEY,
# MAGIC   JAA_KEY,
# MAGIC   PROD_CF_KEY,
# MAGIC   CMPNY_CF_KEY,
# MAGIC   BHFP_KEY,
# MAGIC   CALL_CHAT_TYPE_KEY,
# MAGIC   DGTL_STTS_KEY,
# MAGIC   GSTTNL_DLVRY_AGE_KEY,
# MAGIC   MBR_AGE_KEY,
# MAGIC   LIFE_CTGRY_KEY,
# MAGIC   BRTH_WT_KEY,
# MAGIC   BHF_MBR_TYPE_KEY,
# MAGIC   PRFLG_CMPLT_PHASE_KEY,
# MAGIC   DLVRY_MNTH_KEY,
# MAGIC   MTRNTY_RISK_LVL_KEY,
# MAGIC   BHF_RWRD_ACTV_PRFL_KEY,
# MAGIC   GRP_MBR_RNG_KEY,
# MAGIC   GRP_CNTRCT_SIZE_KEY,
# MAGIC   GRP_MBR_SIZE_KEY
# MAGIC FROM ranked
# MAGIC WHERE RN = 1;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark",
# META   "frozen": true,
# META   "editable": false
# META }
