# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "820ff289-52b1-4c8f-8705-a88c51f147ce",
# META       "default_lakehouse_name": "GOLD_LAKEHOUSE",
# META       "default_lakehouse_workspace_id": "890304bc-64e8-46be-93d9-8ea5a5a56669",
# META       "known_lakehouses": [
# META         {
# META           "id": "820ff289-52b1-4c8f-8705-a88c51f147ce"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInRead", "LEGACY")
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### HWBS FACT'S

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_MBR_MDCL_PROD_DTL
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC 	PROD_KEY Double,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	ZIP_KEY Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC 	EDM_MBR_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC 	GNDR_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC 	HW_KEY Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	MBU_CF_KEY Double,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY Double,
# MAGIC 	PROD_CF_KEY Double,
# MAGIC 	STNDRD_AGE_MNTH_KEY Double,
# MAGIC 	EOM_MBR_CNT Double,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT Double,
# MAGIC 	GRP_MBR_RNG_KEY DOUBLE
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_MBR_MDCL_PROD_DTL
# MAGIC SELECT  
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	PROD_KEY,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	ZIP_KEY,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC 	HW_KEY,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	JAA_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	EOM_MBR_CNT,
# MAGIC 	PRORTD_MBR_MNTH_CNT,
# MAGIC 	SBSCRBR_CNT,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBRSHP;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_ELGBL
# MAGIC (
# MAGIC         EDL_LOAD_DTM DATE,
# MAGIC 	PROD_KEY Double,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC 	EDM_MBR_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC 	GNDR_KEY Double,
# MAGIC 	HW_KEY Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC 	MBU_CF_KEY Double,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY Double,
# MAGIC 	PROD_CF_KEY Double,
# MAGIC 	STNDRD_AGE_MNTH_KEY Double,
# MAGIC 	ZIP_KEY Double,
# MAGIC 	GRP_MBR_RNG_KEY Double
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_ELGBL
# MAGIC SELECT 
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	PROD_KEY,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	HW_KEY,
# MAGIC 	JAA_KEY,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	ZIP_KEY,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC  
# MAGIC  FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_ELGBL;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_INCNTV_ACTVTY
# MAGIC (
# MAGIC         EDL_LOAD_DTM DATE,
# MAGIC 	PROD_KEY Double,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	ZIP_CD STRING,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	EDM_MBR_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC 	GNDR_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC 	HW_KEY Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	MBU_CF_KEY Double,
# MAGIC 	MBR_PROD_MNTH_KEY Double,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY Double,
# MAGIC 	PROD_CF_KEY Double,
# MAGIC 	RWRD_TYPE_KEY Double,
# MAGIC 	STNDRD_AGE_MNTH_KEY Double,
# MAGIC 	DIM_SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	DIM_PROD_KEY Double,
# MAGIC 	ACTVTY_CNT Double,
# MAGIC 	RWRD_AMT Double,
# MAGIC 	PRDA_MBR_RWRD_KEY Double,
# MAGIC 	GRP_MBR_RNG_KEY Double,
# MAGIC 	RWRD_TYPE_CD STRING,
# MAGIC 	RWRD_TYPE_DESC STRING
# MAGIC         
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_INCNTV_ACTVTY
# MAGIC SELECT 
# MAGIC         
# MAGIC         CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	PROD_KEY,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	ZIP_CD,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID,
# MAGIC 	HW_KEY,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	JAA_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	MBR_PROD_MNTH_KEY,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	RWRD_TYPE_KEY,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	DIM_SNAP_YEAR_MNTH_NBR,
# MAGIC 	DIM_PROD_KEY,
# MAGIC 	ACTVTY_CNT,
# MAGIC 	RWRD_AMT,
# MAGIC 	PRDA_MBR_RWRD_KEY,
# MAGIC 	GRP_MBR_RNG_KEY,
# MAGIC 	RWRD_TYPE_CD ,
# MAGIC 	RWRD_TYPE_DESC 
# MAGIC  
# MAGIC  FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_HW_INCNTV_ACTVTY;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_INCNTV_DSBRSMNT
# MAGIC (
# MAGIC         EDL_RUN_ID STRING,
# MAGIC 		EDL_LOAD_DTM DATE,
# MAGIC 	PROD_KEY Double,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC 	DSBRSMNT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	EDM_MBR_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC 	GNDR_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC 	HW_KEY Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	MBU_CF_KEY Double,
# MAGIC 	MBR_PROD_MNTH_KEY Double,
# MAGIC 	MBR_RSDNC_ZIP_KEY Double,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY Double,
# MAGIC 	PROD_CF_KEY Double,
# MAGIC 	RWRD_TYPE_KEY Double,
# MAGIC 	STNDRD_AGE_MNTH_KEY Double,
# MAGIC 	DSBRSMNT_CNT Double,
# MAGIC 	INCNTV_DSBRSMNT_RQST_AMT Double,
# MAGIC 	GRP_MBR_RNG_KEY Double,
# MAGIC 	RWRD_TYPE_CD STRING,
# MAGIC 	RWRD_TYPE_DESC STRING
# MAGIC         
# MAGIC         
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_INCNTV_DSBRSMNT
# MAGIC SELECT 
# MAGIC        EDL_RUN_ID,
# MAGIC 	    CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	PROD_KEY,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	DSBRSMNT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID,
# MAGIC 	HW_KEY,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	JAA_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	MBR_PROD_MNTH_KEY,
# MAGIC 	MBR_RSDNC_ZIP_KEY,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	RWRD_TYPE_KEY,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	DSBRSMNT_CNT,
# MAGIC 	INCNTV_DSBRSMNT_RQST_AMT,
# MAGIC 	GRP_MBR_RNG_KEY,
# MAGIC 	RWRD_TYPE_CD ,
# MAGIC 	RWRD_TYPE_DESC
# MAGIC         
# MAGIC          
# MAGIC  FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_HW_INCNTV_DSBRSMNT;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************


%%sql

--FACT_WBS_MBR_PRCG / FACT_WBS_MBR_PRCG_PGM

CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PGM
(
    EDL_LOAD_DTM DATE,
	SNAP_YEAR_MNTH_NBR Double,
	PROD_KEY Double,
	ZIP_KEY Double,
	CMPNY_CF_KEY Double,
	EDM_MBR_ACCT_KEY Double,
	EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
	EDM_CLNT_GRP_ACCT_KEY Double,
	FUNDG_CF_KEY Double,
	GRP_CNTRCT_SIZE_KEY Double,
	GRP_MBR_SIZE_KEY Double,
	GNDR_KEY Double,
	HW_KEY Double,
	INCRD_YEAR_MNTH_NBR Double,
	JAA_KEY Double,
	MBU_CF_KEY Double,
	MCID_EDM_MBR_ACCT_KEY Double,
	PFOL_YEAR_NBR Double,
	PROD_CF_KEY Double,
	STNDRD_AGE_MNTH_KEY Double,
	EOM_MBR_CNT Double,
	PRORTD_MBR_MNTH_CNT Double,
	SBSCRBR_CNT Double,
	COST_AMT Double,
	RVNU_AMT Double,
	PRCG_COST_PEPM_AMT Double,
	PRCG_COST_PMPM_AMT Double,
	PRCG_RVNU_PEPM_AMT Double,
	PRCG_RVNU_PMPM_AMT Double,
	GRP_MBR_RNG_KEY Double
);

INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PGM
SELECT  
    CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
	SNAP_YEAR_MNTH_NBR,
	PROD_KEY,
	ZIP_KEY,
	CMPNY_CF_KEY,
	EDM_MBR_ACCT_KEY,
	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
	EDM_CLNT_GRP_ACCT_KEY,
	FUNDG_CF_KEY,
	GRP_CNTRCT_SIZE_KEY,
	GRP_MBR_SIZE_KEY,
	GNDR_KEY,
	HW_KEY,
	INCRD_YEAR_MNTH_NBR,
	JAA_KEY,
	MBU_CF_KEY,
	MCID_EDM_MBR_ACCT_KEY,
	PFOL_YEAR_NBR,
	PROD_CF_KEY,
	STNDRD_AGE_MNTH_KEY,
	EOM_MBR_CNT,
	PRORTD_MBR_MNTH_CNT,
	SBSCRBR_CNT,
	COST_AMT,
	RVNU_AMT,
	PRCG_COST_PEPM_AMT,
	PRCG_COST_PMPM_AMT,
	PRCG_RVNU_PEPM_AMT,
	PRCG_RVNU_PMPM_AMT,
	GRP_MBR_RNG_KEY
	FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_PRCG_PGM;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql 
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD
# MAGIC (
# MAGIC         EDL_LOAD_DTM DATE,
# MAGIC         SNAP_YEAR_MNTH_NBR Double,
# MAGIC         PROD_KEY Double,
# MAGIC         ZIP_KEY Double,
# MAGIC         CMPNY_CF_KEY Double,
# MAGIC         EDM_MBR_ACCT_KEY Double,
# MAGIC         EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC         GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC         GNDR_KEY Double,
# MAGIC 	HW_KEY Double,
# MAGIC         INCRD_YEAR_MNTH_NBR Double,
# MAGIC         JAA_KEY Double,
# MAGIC         MBU_CF_KEY Double,
# MAGIC         MCID_EDM_MBR_ACCT_KEY Double,
# MAGIC         PFOL_YEAR_NBR Double,
# MAGIC         PROD_CF_KEY Double,
# MAGIC 	STNDRD_AGE_MNTH_KEY Double,
# MAGIC         EOM_MBR_CNT Double,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT Double,
# MAGIC         COST_AMT Double,
# MAGIC         RVNU_AMT Double,
# MAGIC         PRCG_COST_PEPM_AMT Double,
# MAGIC         PRCG_COST_PMPM_AMT Double,
# MAGIC         PRCG_RVNU_PEPM_AMT Double,
# MAGIC         PRCG_RVNU_PMPM_AMT Double,
# MAGIC         GRP_MBR_RNG_KEY Double
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD
# MAGIC SELECT
# MAGIC         CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC         SNAP_YEAR_MNTH_NBR ,
# MAGIC         PROD_KEY ,
# MAGIC         ZIP_KEY ,
# MAGIC         CMPNY_CF_KEY ,
# MAGIC         EDM_MBR_ACCT_KEY ,
# MAGIC         EDM_CLNT_GRP_SUBGRP_ACCT_KEY ,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY ,
# MAGIC 	FUNDG_CF_KEY ,
# MAGIC         GRP_CNTRCT_SIZE_KEY ,
# MAGIC 	GRP_MBR_SIZE_KEY ,
# MAGIC         GNDR_KEY ,
# MAGIC 	HW_KEY ,
# MAGIC         INCRD_YEAR_MNTH_NBR ,
# MAGIC         JAA_KEY ,
# MAGIC         MBU_CF_KEY ,
# MAGIC         MCID_EDM_MBR_ACCT_KEY,
# MAGIC         PFOL_YEAR_NBR ,
# MAGIC         PROD_CF_KEY ,
# MAGIC 	STNDRD_AGE_MNTH_KEY ,
# MAGIC         EOM_MBR_CNT ,
# MAGIC 	PRORTD_MBR_MNTH_CNT ,
# MAGIC 	SBSCRBR_CNT ,
# MAGIC         COST_AMT ,
# MAGIC         RVNU_AMT ,
# MAGIC         PRCG_COST_PEPM_AMT ,
# MAGIC         PRCG_COST_PMPM_AMT ,
# MAGIC         PRCG_RVNU_PEPM_AMT ,
# MAGIC         PRCG_RVNU_PMPM_AMT ,
# MAGIC         GRP_MBR_RNG_KEY
# MAGIC         
# MAGIC FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_PRCG_PROD;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql 
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD_CLS
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC     SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC     PROD_KEY Double,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC 	MBU_CF_KEY Double,
# MAGIC     ZIP_KEY Double,
# MAGIC     PROD_CF_KEY Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC     GNDR_KEY Double,
# MAGIC 	HW_KEY Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	PFOL_YEAR_NBR Double,
# MAGIC 	EOM_MBR_CNT Double,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT Double,
# MAGIC 	GRP_MBR_RNG_KEY Double
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD_CLS
# MAGIC SELECT
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC     SNAP_YEAR_MNTH_NBR ,
# MAGIC 	INCRD_YEAR_MNTH_NBR ,
# MAGIC     PROD_KEY ,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY ,
# MAGIC 	FUNDG_CF_KEY ,
# MAGIC 	MBU_CF_KEY ,
# MAGIC     ZIP_KEY ,
# MAGIC     PROD_CF_KEY ,
# MAGIC 	CMPNY_CF_KEY ,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY ,
# MAGIC 	GRP_CNTRCT_SIZE_KEY ,
# MAGIC 	GRP_MBR_SIZE_KEY ,
# MAGIC     GNDR_KEY ,
# MAGIC 	HW_KEY ,
# MAGIC 	JAA_KEY ,
# MAGIC 	PFOL_YEAR_NBR ,
# MAGIC 	EOM_MBR_CNT ,
# MAGIC 	PRORTD_MBR_MNTH_CNT ,
# MAGIC 	SBSCRBR_CNT ,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 	
# MAGIC FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_PROD_CLS;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql 
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD_SUBCLS
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC     SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC     PROD_KEY Double,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC     ZIP_KEY Double,
# MAGIC     MBU_CF_KEY Double,
# MAGIC     PROD_CF_KEY Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC     GNDR_KEY Double,
# MAGIC 	HW_KEY Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	PFOL_YEAR_NBR Double,
# MAGIC 	EOM_MBR_CNT Double,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT Double,
# MAGIC 	GRP_MBR_RNG_KEY Double
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD_SUBCLS
# MAGIC SELECT
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC     SNAP_YEAR_MNTH_NBR ,
# MAGIC 	INCRD_YEAR_MNTH_NBR ,
# MAGIC     PROD_KEY ,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY ,
# MAGIC 	FUNDG_CF_KEY ,
# MAGIC     ZIP_KEY ,
# MAGIC     MBU_CF_KEY ,
# MAGIC     PROD_CF_KEY ,
# MAGIC 	CMPNY_CF_KEY ,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY ,
# MAGIC 	GRP_CNTRCT_SIZE_KEY ,
# MAGIC 	GRP_MBR_SIZE_KEY ,
# MAGIC     GNDR_KEY ,
# MAGIC 	HW_KEY ,
# MAGIC 	JAA_KEY ,
# MAGIC 	PFOL_YEAR_NBR ,
# MAGIC 	EOM_MBR_CNT ,
# MAGIC 	PRORTD_MBR_MNTH_CNT ,
# MAGIC 	SBSCRBR_CNT ,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 	
# MAGIC FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_PROD_SUBCLS;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql 
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD_TYPE
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC     SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC     MBU_CF_KEY Double,
# MAGIC     ZIP_KEY Double,
# MAGIC     PROD_KEY Double,
# MAGIC     PROD_CF_KEY Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC     GNDR_KEY Double,
# MAGIC 	HW_KEY Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	PFOL_YEAR_NBR Double,
# MAGIC 	EOM_MBR_CNT Double,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT Double,
# MAGIC 	GRP_MBR_RNG_KEY Double
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_PROD_TYPE
# MAGIC SELECT
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC     SNAP_YEAR_MNTH_NBR ,
# MAGIC 	INCRD_YEAR_MNTH_NBR ,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY ,
# MAGIC 	FUNDG_CF_KEY ,
# MAGIC     MBU_CF_KEY ,
# MAGIC     ZIP_KEY ,
# MAGIC     PROD_KEY ,
# MAGIC     PROD_CF_KEY ,
# MAGIC 	CMPNY_CF_KEY ,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY ,
# MAGIC 	GRP_CNTRCT_SIZE_KEY ,
# MAGIC 	GRP_MBR_SIZE_KEY ,
# MAGIC     GNDR_KEY ,
# MAGIC 	HW_KEY ,
# MAGIC 	JAA_KEY ,
# MAGIC 	PFOL_YEAR_NBR ,
# MAGIC 	EOM_MBR_CNT ,
# MAGIC 	PRORTD_MBR_MNTH_CNT ,
# MAGIC 	SBSCRBR_CNT ,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 	
# MAGIC FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_PROD_TYPE;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_ELGBL_MBR_NEW
# MAGIC (
# MAGIC         --EDL_LOAD_DTM DATE,
# MAGIC 	PROD_KEY Double,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC 	EDM_MBR_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC 	GNDR_KEY Double,
# MAGIC 	--HW_KEY Double,
# MAGIC   PROD_ID STRING,
# MAGIC 	JAA_KEY Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC 	MBU_CF_KEY Double,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY Double,
# MAGIC 	PROD_CF_KEY Double,
# MAGIC 	STNDRD_AGE_MNTH_KEY Double,
# MAGIC 	ZIP_KEY Double,
# MAGIC 	GRP_MBR_RNG_KEY Double
# MAGIC 	--ROW_NUMBER DOUBLE
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_ELGBL_MBR_NEW
# MAGIC SELECT DISTINCT
# MAGIC   A.PROD_KEY,
# MAGIC   A.SNAP_YEAR_MNTH_NBR,
# MAGIC   A.CMPNY_CF_KEY,
# MAGIC   A.EDM_MBR_ACCT_KEY,
# MAGIC   A.EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC   A.EDM_CLNT_GRP_ACCT_KEY,
# MAGIC   A.FUNDG_CF_KEY,
# MAGIC   A.GRP_CNTRCT_SIZE_KEY,
# MAGIC   A.GRP_MBR_SIZE_KEY,
# MAGIC   A.GNDR_KEY,
# MAGIC   --A.HW_KEY,
# MAGIC   B.PROD_ID,
# MAGIC   A.JAA_KEY,
# MAGIC   A.INCRD_YEAR_MNTH_NBR,
# MAGIC   A.MBU_CF_KEY,
# MAGIC   A.MCID_EDM_MBR_ACCT_KEY,
# MAGIC   A.PROD_CF_KEY,
# MAGIC   A.STNDRD_AGE_MNTH_KEY,
# MAGIC   A.ZIP_KEY,
# MAGIC   A.GRP_MBR_RNG_KEY
# MAGIC 
# MAGIC FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBR_ELGBL A
# MAGIC left join GOLD_LAKEHOUSE.dbo.DIM_PRDA_HW_PKG_PGM B
# MAGIC ON A.HW_KEY = B.HW_KEY;
# MAGIC 


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df = spark.sql("SELECT count(*) FROM GOLD_LAKEHOUSE.dbo.fact_wbs_mbr_elgbl_mbr_new")
display(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
