# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "820ff289-52b1-4c8f-8705-a88c51f147ce",
# META       "default_lakehouse_name": "GOLD_LAKEHOUSE",
# META       "default_lakehouse_workspace_id": "890304bc-64e8-46be-93d9-8ea5a5a56669",
# META       "known_lakehouses": [
# META         {
# META           "id": "820ff289-52b1-4c8f-8705-a88c51f147ce"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInRead", "LEGACY")
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%pyspark
# MAGIC spark.conf.set("spark.sql.legacy.parquet.datetimeRebaseModeInRead", "CORRECTED")
# MAGIC spark.conf.set("spark.sql.legacy.parquet.int96RebaseModeInRead", "CORRECTED")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.ADIM_PRDA_DNTL_Membrshp
# MAGIC (
# MAGIC 
# MAGIC MCID INT,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCRD_YEAR_MNTH_NBR INT,
# MAGIC ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_MBR_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC EDW_BNFT_PKG_ID STRING,
# MAGIC SBSCRBR_IND STRING,
# MAGIC SBSCRBR_RLTNSHP_CD STRING,
# MAGIC MBU_CF_REL_CD STRING,
# MAGIC MPR_IND STRING,
# MAGIC RFR_IND STRING,
# MAGIC DNTL_PROD_KEY INT,
# MAGIC DNTL_PROD_SOR_CD STRING,
# MAGIC DNTL_CMPNY_CF_CD STRING,
# MAGIC DNTL_MBU_CF_CD STRING,
# MAGIC DNTL_FUNDG_CF_CD STRING,
# MAGIC DNTL_PROD_CF_CD STRING,
# MAGIC DNTL_MBRSHP_HCC_CD STRING,
# MAGIC DNTL_CNTRCT_TYPE_CD STRING,
# MAGIC DNTL_PROD_ACCUMN_PRD_CD STRING,
# MAGIC DNTL_EOM_MBR_CNT INT,
# MAGIC DNTL_GRP_CNTRCT_SIZE_NBR INT,
# MAGIC DNTL_GRP_MBR_SIZE_NBR INT,
# MAGIC DNTL_GRP_NGTV_CHNG_CNT INT,
# MAGIC DNTL_GRP_PSTV_CHNG_CNT INT,
# MAGIC DNTL_MBR_LPSE_CNT INT,
# MAGIC DNTL_MBR_NEW_SALE_CNT INT,
# MAGIC DNTL_PRORTD_MBR_MNTH_CNT INT,
# MAGIC DNTL_ADMNSTRTV_FEE_OTHR_RVNU_AMT INT,
# MAGIC DNTL_ANLYTC_ALWD_AMT INT,
# MAGIC DNTL_ANLYTC_CPTTN_AMT INT,
# MAGIC DNTL_ANLYTC_PAID_AMT INT,
# MAGIC DNTL_BILLD_CHRG_AMT INT,
# MAGIC DNTL_COINSRN_AMT INT,
# MAGIC DNTL_COB_SVNGS_AMT INT,
# MAGIC DNTL_CPAY_AMT INT,
# MAGIC DNTL_DDCTBL_AMT INT,
# MAGIC DNTL_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC DNTL_MLR_REBT_AMT INT,
# MAGIC DNTL_OTHR_BNFT_EXPNS_ITEMS_AMT INT,
# MAGIC DNTL_OTHR_MBR_PAID_AMT INT,
# MAGIC DNTL_RVNU_PREM_AMT INT,
# MAGIC DNTL_SELNG_EXPNS_AMT INT,
# MAGIC DNTL_MCID_EFCTV_DT DATE,
# MAGIC DNTL_MCID_TRMNTN_DT DATE,
# MAGIC DNTL_ACCT_CNTRL_EFCTV_DT DATE,
# MAGIC DNTL_ACCT_CNTRL_TRMNTN_DT DATE,
# MAGIC ITRTN_NBR INT,
# MAGIC CUBE_ITRTN_NBR INT,
# MAGIC DNTL_PNTRTN_IND STRING,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC MBR_RSDNC_ZIP_CD STRING,
# MAGIC STNDRD_AGE_MNTH_CD STRING,
# MAGIC GNDR_KEY INT,
# MAGIC UNWGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC UNWGTD_PRSPTV_RISK_NBR INT,
# MAGIC WGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC WGTD_PRSPTV_RISK_NBR INT,
# MAGIC DGTL_ELGBLTY_CD STRING,
# MAGIC DGTL_ELGBLTY_IND STRING,
# MAGIC VPC_PLT_IND STRING,
# MAGIC STPLS_EXPNS_AMT INT,
# MAGIC STPLS_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC STPLS_RVNU_PREM_AMT INT,
# MAGIC DNTL_NTWK_KEY INT,
# MAGIC CMN_KEY INT,
# MAGIC VPC_PLT_CTGRY_KEY INT,
# MAGIC GRNDFTHR_CD STRING,
# MAGIC GRNDFTHR_DESC STRING,
# MAGIC GRP_MBR_RNG_KEY INT
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.ADIM_PRDA_DNTL_Membrshp
# MAGIC SELECT 
# MAGIC 
# MAGIC     MCID,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDW_BNFT_PKG_ID,
# MAGIC 	SBSCRBR_IND,
# MAGIC 	SBSCRBR_RLTNSHP_CD,
# MAGIC 	MBU_CF_REL_CD,
# MAGIC 	MPR_IND,
# MAGIC 	RFR_IND,
# MAGIC 	DNTL_PROD_KEY,
# MAGIC 	DNTL_PROD_SOR_CD,
# MAGIC 	DNTL_CMPNY_CF_CD,
# MAGIC 	DNTL_MBU_CF_CD,
# MAGIC 	DNTL_FUNDG_CF_CD,
# MAGIC 	DNTL_PROD_CF_CD,
# MAGIC 	DNTL_MBRSHP_HCC_CD,
# MAGIC 	DNTL_CNTRCT_TYPE_CD,
# MAGIC 	DNTL_PROD_ACCUMN_PRD_CD,
# MAGIC 	DNTL_EOM_MBR_CNT,
# MAGIC 	DNTL_GRP_CNTRCT_SIZE_NBR,
# MAGIC 	DNTL_GRP_MBR_SIZE_NBR,
# MAGIC 	DNTL_GRP_NGTV_CHNG_CNT,
# MAGIC 	DNTL_GRP_PSTV_CHNG_CNT,
# MAGIC 	DNTL_MBR_LPSE_CNT,
# MAGIC 	DNTL_MBR_NEW_SALE_CNT,
# MAGIC 	DNTL_PRORTD_MBR_MNTH_CNT,
# MAGIC 	DNTL_ADMNSTRTV_FEE_OTHR_RVNU_AMT,
# MAGIC 	DNTL_ANLYTC_ALWD_AMT,
# MAGIC 	DNTL_ANLYTC_CPTTN_AMT,
# MAGIC 	DNTL_ANLYTC_PAID_AMT,
# MAGIC 	DNTL_BILLD_CHRG_AMT,
# MAGIC 	DNTL_COINSRN_AMT,
# MAGIC 	DNTL_COB_SVNGS_AMT,
# MAGIC 	DNTL_CPAY_AMT,
# MAGIC 	DNTL_DDCTBL_AMT,
# MAGIC 	DNTL_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	DNTL_MLR_REBT_AMT,
# MAGIC 	DNTL_OTHR_BNFT_EXPNS_ITEMS_AMT,
# MAGIC 	DNTL_OTHR_MBR_PAID_AMT,
# MAGIC 	DNTL_RVNU_PREM_AMT,
# MAGIC 	DNTL_SELNG_EXPNS_AMT,
# MAGIC 	DNTL_MCID_EFCTV_DT,
# MAGIC 	DNTL_MCID_TRMNTN_DT,
# MAGIC 	DNTL_ACCT_CNTRL_EFCTV_DT,
# MAGIC 	DNTL_ACCT_CNTRL_TRMNTN_DT,
# MAGIC 	ITRTN_NBR,
# MAGIC 	CUBE_ITRTN_NBR,
# MAGIC 	DNTL_PNTRTN_IND,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID,
# MAGIC 	MBR_RSDNC_ZIP_CD,
# MAGIC 	STNDRD_AGE_MNTH_CD,
# MAGIC 	GNDR_KEY,
# MAGIC 	UNWGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	UNWGTD_PRSPTV_RISK_NBR,
# MAGIC 	WGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	WGTD_PRSPTV_RISK_NBR,
# MAGIC 	DGTL_ELGBLTY_CD,
# MAGIC 	DGTL_ELGBLTY_IND,
# MAGIC 	VPC_PLT_IND,
# MAGIC 	STPLS_EXPNS_AMT,
# MAGIC 	STPLS_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	STPLS_RVNU_PREM_AMT,
# MAGIC 	DNTL_NTWK_KEY,
# MAGIC 	CMN_KEY,
# MAGIC 	VPC_PLT_CTGRY_KEY,
# MAGIC 	GRNDFTHR_CD,
# MAGIC 	GRNDFTHR_DESC,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 	
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.ADIM_PRDA_DNTL;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.ADIM_PRDA_MDCL_Membrshp
# MAGIC (
# MAGIC 
# MAGIC MCID INT,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCRD_YEAR_MNTH_NBR INT,
# MAGIC ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_MBR_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC EDW_BNFT_PKG_ID INT,
# MAGIC SBSCRBR_IND STRING,
# MAGIC SBSCRBR_RLTNSHP_CD STRING,
# MAGIC PROD_KEY INT,
# MAGIC MDCL_PROD_SOR_CD STRING,
# MAGIC MDCL_CMPNY_CF_CD STRING,
# MAGIC MDCL_MBU_CF_CD STRING,
# MAGIC MDCL_MBU_CF_REL_CD STRING,
# MAGIC MDCL_FUNDG_CF_CD STRING,
# MAGIC MDCL_PROD_CF_CD STRING,
# MAGIC MPR_IND STRING,
# MAGIC RFR_IND STRING,
# MAGIC MBRSHP_HCC_CD STRING,
# MAGIC MDCL_CNTRCT_TYPE_CD STRING,
# MAGIC MDCL_PROD_ACCUMN_PRD_CD STRING,
# MAGIC MDCL_EOM_MBR_CNT INT,
# MAGIC MDCL_GRP_CNTRCT_SIZE_NBR INT,
# MAGIC MDCL_GRP_MBR_SIZE_NBR INT,
# MAGIC MDCL_GRP_NGTV_CHNG_CNT INT,
# MAGIC MDCL_GRP_PSTV_CHNG_CNT INT,
# MAGIC MDCL_MBR_LAPSE_CNT INT,
# MAGIC MDCL_MBR_NEW_SALE_CNT INT,
# MAGIC MDCL_PRORTD_MBR_MNTH_CNT INT,
# MAGIC MDCL_ADMNSTRTV_FEES_OTHR_RVNU_AMT INT,
# MAGIC MDCL_ANLYTC_ALWD_AMT INT,
# MAGIC MDCL_ANLYTC_CPTTN_AMT INT,
# MAGIC MDCL_ANLYTC_PAID_AMT INT,
# MAGIC MDCL_BILLD_CHRG_AMT INT,
# MAGIC MDCL_COINSRN_AMT INT,
# MAGIC MDCL_COB_SVNGS_AMT INT,
# MAGIC MDCL_CPAY_AMT INT,
# MAGIC MDCL_DDCTBL_AMT INT,
# MAGIC MDCL_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC MDCL_MLR_REBT_AMT INT,
# MAGIC MDCL_OTHR_BNFT_EXPNS_ITEMS_AMT INT,
# MAGIC MDCL_OTHR_MBR_PAID_AMT INT,
# MAGIC MDCL_RVNU_PREM_AMT INT,
# MAGIC MDCL_SELNG_EXPNS_AMT INT,
# MAGIC MDCL_MCID_EFCTV_DT DATE,
# MAGIC MDCL_MCID_TRMNTN_DT DATE,
# MAGIC MDCL_ACCT_CNTRL_EFCTV_DT DATE,
# MAGIC MDCL_ACCT_CNTRL_TRMNTN_DT DATE,
# MAGIC CNFDNTL_INFO_SCRTY_LVL_CD STRING,
# MAGIC ITRTN_NBR INT,
# MAGIC CUBE_ITRTN_NBR INT,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC MBR_RSDNC_ZIP_CD STRING,
# MAGIC STNDRD_AGE_MNTH_CODE STRING,
# MAGIC GNDR_KEY INT,
# MAGIC UNWGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC UNWGTD_PRSPTV_RISK_NBR INT,
# MAGIC WGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC WGTD_PRSPTV_RISK_NBR INT,
# MAGIC DGTL_ELGBLTY_CD STRING,
# MAGIC DGTL_ELGBLTY_IND STRING,
# MAGIC VPC_PLT_IND STRING,
# MAGIC STPLS_EXPNS_AMT INT,
# MAGIC STPLS_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC STPLS_RVNU_PREM_AMT INT,
# MAGIC MDCL_NTWK_KEY INT,
# MAGIC CMN_KEY INT,
# MAGIC VPC_PLT_CTGRY_KEY INT,
# MAGIC GRNDFTHR_CD STRING,
# MAGIC GRNDFTHR_DESC STRING,
# MAGIC GRP_MBR_RNG_KEY INT
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.ADIM_PRDA_MDCL_Membrshp
# MAGIC SELECT 
# MAGIC 
# MAGIC     
# MAGIC 	MCID,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDW_BNFT_PKG_ID,
# MAGIC 	SBSCRBR_IND,
# MAGIC 	SBSCRBR_RLTNSHP_CD,
# MAGIC 	PROD_KEY,
# MAGIC 	MDCL_PROD_SOR_CD,
# MAGIC 	MDCL_CMPNY_CF_CD,
# MAGIC 	MDCL_MBU_CF_CD,
# MAGIC 	MDCL_MBU_CF_REL_CD,
# MAGIC 	MDCL_FUNDG_CF_CD,
# MAGIC 	MDCL_PROD_CF_CD,
# MAGIC 	MPR_IND,
# MAGIC 	RFR_IND,
# MAGIC 	MBRSHP_HCC_CD,
# MAGIC 	MDCL_CNTRCT_TYPE_CD,
# MAGIC 	MDCL_PROD_ACCUMN_PRD_CD,
# MAGIC 	MDCL_EOM_MBR_CNT,
# MAGIC 	MDCL_GRP_CNTRCT_SIZE_NBR,
# MAGIC 	MDCL_GRP_MBR_SIZE_NBR,
# MAGIC 	MDCL_GRP_NGTV_CHNG_CNT,
# MAGIC 	MDCL_GRP_PSTV_CHNG_CNT,
# MAGIC 	MDCL_MBR_LAPSE_CNT,
# MAGIC 	MDCL_MBR_NEW_SALE_CNT,
# MAGIC 	MDCL_PRORTD_MBR_MNTH_CNT,
# MAGIC 	MDCL_ADMNSTRTV_FEES_OTHR_RVNU_AMT,
# MAGIC 	MDCL_ANLYTC_ALWD_AMT,
# MAGIC 	MDCL_ANLYTC_CPTTN_AMT,
# MAGIC 	MDCL_ANLYTC_PAID_AMT,
# MAGIC 	MDCL_BILLD_CHRG_AMT,
# MAGIC 	MDCL_COINSRN_AMT,
# MAGIC 	MDCL_COB_SVNGS_AMT,
# MAGIC 	MDCL_CPAY_AMT,
# MAGIC 	MDCL_DDCTBL_AMT,
# MAGIC 	MDCL_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	MDCL_MLR_REBT_AMT,
# MAGIC 	MDCL_OTHR_BNFT_EXPNS_ITEMS_AMT,
# MAGIC 	MDCL_OTHR_MBR_PAID_AMT,
# MAGIC 	MDCL_RVNU_PREM_AMT,
# MAGIC 	MDCL_SELNG_EXPNS_AMT,
# MAGIC 	MDCL_MCID_EFCTV_DT,
# MAGIC 	MDCL_MCID_TRMNTN_DT,
# MAGIC 	MDCL_ACCT_CNTRL_EFCTV_DT,
# MAGIC 	MDCL_ACCT_CNTRL_TRMNTN_DT,
# MAGIC 	CNFDNTL_INFO_SCRTY_LVL_CD,
# MAGIC 	ITRTN_NBR,
# MAGIC 	CUBE_ITRTN_NBR,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID,
# MAGIC 	MBR_RSDNC_ZIP_CD,
# MAGIC 	STNDRD_AGE_MNTH_CODE,
# MAGIC 	GNDR_KEY,
# MAGIC 	UNWGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	UNWGTD_PRSPTV_RISK_NBR,
# MAGIC 	WGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	WGTD_PRSPTV_RISK_NBR,
# MAGIC 	DGTL_ELGBLTY_CD,
# MAGIC 	DGTL_ELGBLTY_IND,
# MAGIC 	VPC_PLT_IND,
# MAGIC 	STPLS_EXPNS_AMT,
# MAGIC 	STPLS_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	STPLS_RVNU_PREM_AMT,
# MAGIC 	MDCL_NTWK_KEY,
# MAGIC 	CMN_KEY,
# MAGIC 	VPC_PLT_CTGRY_KEY,
# MAGIC 	GRNDFTHR_CD,
# MAGIC 	GRNDFTHR_DESC,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 
# MAGIC 	
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.ADIM_PRDA_MDCL;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.ADIM_PRDA_RX_Membrshp
# MAGIC (
# MAGIC 
# MAGIC MCID INT,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCRD_YEAR_MNTH_NBR INT,
# MAGIC ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_MBR_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC EDW_BNFT_PKG_ID INT,
# MAGIC SBSCRBR_IND STRING,
# MAGIC SBSCRBR_RLTNSHP_CD STRING,
# MAGIC MBU_CF_REL_CD STRING,
# MAGIC MPR_IND STRING,
# MAGIC RFR_IND STRING,
# MAGIC RX_PROD_KEY INT,
# MAGIC RX_PROD_SOR_CD STRING,
# MAGIC RX_CMPNY_CF_CD STRING,
# MAGIC RX_MBU_CF_CD STRING,
# MAGIC RX_FUNDG_CF_CD STRING,
# MAGIC RX_PROD_CF_CD STRING,
# MAGIC RX_MBRSHP_HCC_CD STRING,
# MAGIC RX_CNTRCT_TYPE_CD STRING,
# MAGIC RX_PROD_ACCUMN_PRD_CD STRING,
# MAGIC RX_EOM_MBR_CNT INT,
# MAGIC RX_GRP_CNTRCT_SIZE_NBR INT,
# MAGIC RX_GRP_MBR_SIZE_NBR INT,
# MAGIC RX_GRP_NGTV_CHNG_CNT INT,
# MAGIC RX_GRP_PSTV_CHNG_CNT INT,
# MAGIC RX_MBR_LAPSE_CNT INT,
# MAGIC RX_MBR_NEW_SALE_CNT INT,
# MAGIC RX_PRORTD_MBR_MNTH_CNT INT,
# MAGIC RX_ADMNSTRTV_FEE_OTHR_RVNU_AMT INT,
# MAGIC RX_ANLYTC_ALWD_AMT INT,
# MAGIC RX_ANLYTC_CPTTN_AMT INT,
# MAGIC RX_ANLYTC_PAID_AMT INT,
# MAGIC RX_BILLD_CHRG_AMT INT,
# MAGIC RX_COINSRN_AMT INT,
# MAGIC RX_COB_SVNGS_AMT INT,
# MAGIC RX_CPAY_AMT INT,
# MAGIC RX_DDCTBL_AMT INT,
# MAGIC RX_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC RX_MLR_REBT_AMT INT,
# MAGIC RX_OTHR_BNFT_EXPNS_ITEMS_AMT INT,
# MAGIC RX_OTHR_MBR_PAID_AMT INT,
# MAGIC RX_RVNU_PREM_AMT INT,
# MAGIC RX_SELNG_EXPNS_AMT INT,
# MAGIC RX_MCID_EFCTV_DT DATE,
# MAGIC RX_MCID_TRMNTN_DT DATE,
# MAGIC RX_ACCT_CNTRL_EFCTV_DT DATE,
# MAGIC RX_ACCT_CNTRL_TRMNTN_DT DATE,
# MAGIC ITRTN_NBR INT,
# MAGIC CUBE_ITRTN_NBR INT,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC MBR_RSDNC_ZIP_CD STRING,
# MAGIC STNDRD_AGE_MNTH_CD STRING,
# MAGIC GNDR_KEY INT,
# MAGIC UNWGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC UNWGTD_PRSPTV_RISK_NBR INT,
# MAGIC WGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC WGTD_PRSPTV_RISK_NBR INT,
# MAGIC DGTL_ELGBLTY_CD STRING,
# MAGIC DGTL_ELGBLTY_IND STRING,
# MAGIC VPC_PLT_IND STRING,
# MAGIC STPLS_EXPNS_AMT INT,
# MAGIC STPLS_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC STPLS_RVNU_PREM_AMT INT,
# MAGIC RX_NTWK_KEY INT,
# MAGIC CMN_KEY INT,
# MAGIC VPC_PLT_CTGRY_KEY INT,
# MAGIC GRNDFTHR_CD STRING,
# MAGIC GRNDFTHR_DESC STRING,
# MAGIC GRP_MBR_RNG_KEY INT
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.ADIM_PRDA_RX_Membrshp
# MAGIC SELECT 
# MAGIC 
# MAGIC     MCID,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDW_BNFT_PKG_ID,
# MAGIC 	SBSCRBR_IND,
# MAGIC 	SBSCRBR_RLTNSHP_CD,
# MAGIC 	MBU_CF_REL_CD,
# MAGIC 	MPR_IND,
# MAGIC 	RFR_IND,
# MAGIC 	RX_PROD_KEY,
# MAGIC 	RX_PROD_SOR_CD,
# MAGIC 	RX_CMPNY_CF_CD,
# MAGIC 	RX_MBU_CF_CD,
# MAGIC 	RX_FUNDG_CF_CD,
# MAGIC 	RX_PROD_CF_CD,
# MAGIC 	RX_MBRSHP_HCC_CD,
# MAGIC 	RX_CNTRCT_TYPE_CD,
# MAGIC 	RX_PROD_ACCUMN_PRD_CD,
# MAGIC 	RX_EOM_MBR_CNT,
# MAGIC 	RX_GRP_CNTRCT_SIZE_NBR,
# MAGIC 	RX_GRP_MBR_SIZE_NBR,
# MAGIC 	RX_GRP_NGTV_CHNG_CNT,
# MAGIC 	RX_GRP_PSTV_CHNG_CNT,
# MAGIC 	RX_MBR_LAPSE_CNT,
# MAGIC 	RX_MBR_NEW_SALE_CNT,
# MAGIC 	RX_PRORTD_MBR_MNTH_CNT,
# MAGIC 	RX_ADMNSTRTV_FEE_OTHR_RVNU_AMT,
# MAGIC 	RX_ANLYTC_ALWD_AMT,
# MAGIC 	RX_ANLYTC_CPTTN_AMT,
# MAGIC 	RX_ANLYTC_PAID_AMT,
# MAGIC 	RX_BILLD_CHRG_AMT,
# MAGIC 	RX_COINSRN_AMT,
# MAGIC 	RX_COB_SVNGS_AMT,
# MAGIC 	RX_CPAY_AMT,
# MAGIC 	RX_DDCTBL_AMT,
# MAGIC 	RX_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	RX_MLR_REBT_AMT,
# MAGIC 	RX_OTHR_BNFT_EXPNS_ITEMS_AMT,
# MAGIC 	RX_OTHR_MBR_PAID_AMT,
# MAGIC 	RX_RVNU_PREM_AMT,
# MAGIC 	RX_SELNG_EXPNS_AMT,
# MAGIC 	RX_MCID_EFCTV_DT,
# MAGIC 	RX_MCID_TRMNTN_DT,
# MAGIC 	RX_ACCT_CNTRL_EFCTV_DT,
# MAGIC 	RX_ACCT_CNTRL_TRMNTN_DT,
# MAGIC 	ITRTN_NBR,
# MAGIC 	CUBE_ITRTN_NBR,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID,
# MAGIC 	MBR_RSDNC_ZIP_CD,
# MAGIC 	STNDRD_AGE_MNTH_CD,
# MAGIC 	GNDR_KEY,
# MAGIC 	UNWGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	UNWGTD_PRSPTV_RISK_NBR,
# MAGIC 	WGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	WGTD_PRSPTV_RISK_NBR,
# MAGIC 	DGTL_ELGBLTY_CD,
# MAGIC 	DGTL_ELGBLTY_IND,
# MAGIC 	VPC_PLT_IND,
# MAGIC 	STPLS_EXPNS_AMT,
# MAGIC 	STPLS_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	STPLS_RVNU_PREM_AMT,
# MAGIC 	RX_NTWK_KEY,
# MAGIC 	CMN_KEY,
# MAGIC 	VPC_PLT_CTGRY_KEY,
# MAGIC 	GRNDFTHR_CD,
# MAGIC 	GRNDFTHR_DESC,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 
# MAGIC 	
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.ADIM_PRDA_RX;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.ADIM_PRDA_VISN_Membrshp
# MAGIC (
# MAGIC 
# MAGIC MCID INT,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCRD_YEAR_MNTH_NBR INT,
# MAGIC ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC EDM_MBR_ACCT_KEY INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC EDW_BNFT_PKG_ID INT,
# MAGIC SBSCRBR_IND STRING,
# MAGIC SBSCRBR_RLTNSHP_CD STRING,
# MAGIC MBU_CF_REL_CD STRING,
# MAGIC MPR_IND STRING,
# MAGIC RFR_IND STRING,
# MAGIC VSN_PROD_KEY INT,
# MAGIC VSN_PROD_SOR_CD STRING,
# MAGIC VSN_CMPNY_CF_CD STRING,
# MAGIC VSN_MBU_CF_CD STRING,
# MAGIC VSN_FUNDG_CF_CD STRING,
# MAGIC VSN_PROD_CF_CD STRING,
# MAGIC VSN_MBRSHP_HCC_CD STRING,
# MAGIC VSN_CNTRCT_TYPE_CD STRING,
# MAGIC VSN_PROD_ACCUMN_PRD_CD STRING,
# MAGIC VSN_EOM_MBR_CNT INT,
# MAGIC VSN_GRP_CNTRCT_SIZE_NBR INT,
# MAGIC VSN_GRP_MBR_SIZE_NBR INT,
# MAGIC VSN_GRP_NGTV_CHNG_CNT INT,
# MAGIC VSN_GRP_PSTV_CHNG_CNT INT,
# MAGIC VSN_MBR_LAPSE_CNT INT,
# MAGIC VSN_MBR_NEW_SALE_CNT INT,
# MAGIC VSN_PRORTD_MBR_MNTH_CNT INT,
# MAGIC VSN_ADMNSTRTV_FEES_OTHR_RVNU_AMT INT,
# MAGIC VSN_ANLYTC_ALWD_AMT INT,
# MAGIC VSN_ANLYTC_CPTTN_AMT INT,
# MAGIC VSN_ANLYTC_PAID_AMT INT,
# MAGIC VSN_BILLD_CHRG_AMT INT,
# MAGIC VSN_COINSRN_AMT INT,
# MAGIC VSN_COB_SVNGS_AMT INT,
# MAGIC VSN_CPAY_AMT INT,
# MAGIC VSN_DDCTBL_AMT INT,
# MAGIC VSN_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC VSN_MLR_REBT_AMT INT,
# MAGIC VSN_OTHR_BNFT_EXPNS_ITEMS_AMT INT,
# MAGIC VSN_OTHR_MBR_PAID_AMT INT,
# MAGIC VSN_RVNU_PREM_AMT INT,
# MAGIC VSN_SELNG_EXPNS_AMT INT,
# MAGIC VSN_MCID_EFCTV_DT DATE,
# MAGIC VSN_MCID_TRMNTN_DT DATE,
# MAGIC VSN_ACCT_CNTRL_EFCTV_DT DATE,
# MAGIC VSN_ACCT_CNTRL_TRMNTN_DT DATE,
# MAGIC ITRTN_NBR INT,
# MAGIC CUBE_ITRTN_NBR INT,
# MAGIC VSN_PNTRTN_IND STRING,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC MBR_RSDNC_ZIP_CD STRING,
# MAGIC STNDRD_AGE_MNTH_CD STRING,
# MAGIC GNDR_CD INT,
# MAGIC UNWGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC UNWGTD_PRSPTV_RISK_NBR INT,
# MAGIC WGTD_RETROSPCTV_RISK_NBR INT,
# MAGIC WGTD_PRSPTV_RISK_NBR INT,
# MAGIC DGTL_ELGBLTY_CD STRING,
# MAGIC DGTL_ELGBLTY_IND STRING,
# MAGIC VPC_PLT_IND STRING,
# MAGIC STPLS_EXPNS_AMT INT,
# MAGIC STPLS_GNRL_ADMNSTRTV_EXPNS_AMT INT,
# MAGIC STPLS_RVNU_PREM_AMT INT,
# MAGIC VSN_NTWK_KEY INT,
# MAGIC CMN_KEY INT,
# MAGIC VPC_PLT_CTGRY_KEY INT,
# MAGIC GRNDFTHR_CD STRING,
# MAGIC GRNDFTHR_DESC STRING,
# MAGIC GRP_MBR_RNG_KEY INT
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.ADIM_PRDA_VISN_Membrshp
# MAGIC SELECT 
# MAGIC 
# MAGIC     MCID,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDW_BNFT_PKG_ID,
# MAGIC 	SBSCRBR_IND,
# MAGIC 	SBSCRBR_RLTNSHP_CD,
# MAGIC 	MBU_CF_REL_CD,
# MAGIC 	MPR_IND,
# MAGIC 	RFR_IND,
# MAGIC 	VSN_PROD_KEY,
# MAGIC 	VSN_PROD_SOR_CD,
# MAGIC 	VSN_CMPNY_CF_CD,
# MAGIC 	VSN_MBU_CF_CD,
# MAGIC 	VSN_FUNDG_CF_CD,
# MAGIC 	VSN_PROD_CF_CD,
# MAGIC 	VSN_MBRSHP_HCC_CD,
# MAGIC 	VSN_CNTRCT_TYPE_CD,
# MAGIC 	VSN_PROD_ACCUMN_PRD_CD,
# MAGIC 	VSN_EOM_MBR_CNT,
# MAGIC 	VSN_GRP_CNTRCT_SIZE_NBR,
# MAGIC 	VSN_GRP_MBR_SIZE_NBR,
# MAGIC 	VSN_GRP_NGTV_CHNG_CNT,
# MAGIC 	VSN_GRP_PSTV_CHNG_CNT,
# MAGIC 	VSN_MBR_LAPSE_CNT,
# MAGIC 	VSN_MBR_NEW_SALE_CNT,
# MAGIC 	VSN_PRORTD_MBR_MNTH_CNT,
# MAGIC 	VSN_ADMNSTRTV_FEES_OTHR_RVNU_AMT,
# MAGIC 	VSN_ANLYTC_ALWD_AMT,
# MAGIC 	VSN_ANLYTC_CPTTN_AMT,
# MAGIC 	VSN_ANLYTC_PAID_AMT,
# MAGIC 	VSN_BILLD_CHRG_AMT,
# MAGIC 	VSN_COINSRN_AMT,
# MAGIC 	VSN_COB_SVNGS_AMT,
# MAGIC 	VSN_CPAY_AMT,
# MAGIC 	VSN_DDCTBL_AMT,
# MAGIC 	VSN_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	VSN_MLR_REBT_AMT,
# MAGIC 	VSN_OTHR_BNFT_EXPNS_ITEMS_AMT,
# MAGIC 	VSN_OTHR_MBR_PAID_AMT,
# MAGIC 	VSN_RVNU_PREM_AMT,
# MAGIC 	VSN_SELNG_EXPNS_AMT,
# MAGIC 	VSN_MCID_EFCTV_DT,
# MAGIC 	VSN_MCID_TRMNTN_DT,
# MAGIC 	VSN_ACCT_CNTRL_EFCTV_DT,
# MAGIC 	VSN_ACCT_CNTRL_TRMNTN_DT,
# MAGIC 	ITRTN_NBR,
# MAGIC 	CUBE_ITRTN_NBR,
# MAGIC 	VSN_PNTRTN_IND,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID,
# MAGIC 	MBR_RSDNC_ZIP_CD,
# MAGIC 	STNDRD_AGE_MNTH_CD,
# MAGIC 	GNDR_CD,
# MAGIC 	UNWGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	UNWGTD_PRSPTV_RISK_NBR,
# MAGIC 	WGTD_RETROSPCTV_RISK_NBR,
# MAGIC 	WGTD_PRSPTV_RISK_NBR,
# MAGIC 	DGTL_ELGBLTY_CD,
# MAGIC 	DGTL_ELGBLTY_IND,
# MAGIC 	VPC_PLT_IND,
# MAGIC 	STPLS_EXPNS_AMT,
# MAGIC 	STPLS_GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	STPLS_RVNU_PREM_AMT,
# MAGIC 	VSN_NTWK_KEY,
# MAGIC 	CMN_KEY,
# MAGIC 	VPC_PLT_CTGRY_KEY,
# MAGIC 	GRNDFTHR_CD,
# MAGIC 	GRNDFTHR_DESC,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 
# MAGIC 	
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.ADIM_PRDA_VISN;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.ADIM_PRDA_GRP_PROD_STOP_LOSS_SMRY_Membrshp
# MAGIC (
# MAGIC 
# MAGIC     SNAP_YEAR_MNTH_NBR INT,
# MAGIC     INCRD_YEAR_MNTH_NBR INT,
# MAGIC     ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC     EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC     PROD_KEY INT,
# MAGIC     CMPNY_CF_KEY INT,
# MAGIC     MBU_CF_KEY INT,
# MAGIC     FUNDG_CF_KEY INT,
# MAGIC     PROD_CF_KEY INT,
# MAGIC     BRKR_ACCT_KEY INT,
# MAGIC     EOM_CNTRCT_CNT BIGINT,
# MAGIC     EOM_MBR_CNT BIGINT,
# MAGIC     EXPNS_AMT DECIMAL(18,2),
# MAGIC     GNRL_ADMNSTRTV_EXPNS_AMT DECIMAL(18,2),
# MAGIC     NON_RUN_IN_CLM_LMT_AMT DECIMAL(18,2),
# MAGIC     PRORTD_MBR_MNTH_CNT DECIMAL(18,2),
# MAGIC     RVNU_PREM_AMT DECIMAL(18,2),
# MAGIC     MBRSHP_HCC_CD STRING
# MAGIC 
# MAGIC  
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.ADIM_PRDA_GRP_PROD_STOP_LOSS_SMRY_Membrshp
# MAGIC SELECT 
# MAGIC     
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	ACCT_CNTRL_EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	PROD_KEY,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	BRKR_ACCT_KEY,
# MAGIC 	EOM_CNTRCT_CNT,
# MAGIC 	EOM_MBR_CNT,
# MAGIC 	EXPNS_AMT,
# MAGIC 	GNRL_ADMNSTRTV_EXPNS_AMT,
# MAGIC 	NON_RUN_IN_CLM_LMT_AMT,
# MAGIC 	PRORTD_MBR_MNTH_CNT,
# MAGIC 	RVNU_PREM_AMT,
# MAGIC     MBRSHP_HCC_CD
# MAGIC 
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.ADIM_PRDA_GRP_STOP_LOSS_SMRY;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC --FACT_PRDA_BHF_MBR
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_ADIM_PRDA_BHF_MBR_DTL_MEMBRSHP
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC 	CTGRY_NM STRING,
# MAGIC 	MCID_EDM_MBR_RANK_NBR INTEGER,
# MAGIC     SNAP_YEAR_MNTH_NBR INT,
# MAGIC 	INCRD_YEAR_MNTH_NBR INT,
# MAGIC 	EDM_MBR_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 	PROD_KEY INT,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC 	MCID BIGINT,
# MAGIC 	STNDRD_AGE_MNTH_KEY INT,
# MAGIC 	GNDR_KEY INT,
# MAGIC 	ZIP_KEY INT,
# MAGIC 	FUNDG_CF_KEY INT,
# MAGIC 	MBU_CF_KEY INT,
# MAGIC 	JAA_KEY INT,
# MAGIC 	PROD_CF_KEY INT,
# MAGIC 	CMPNY_CF_KEY INT,
# MAGIC 	BHFP_KEY INT,
# MAGIC 	CALL_CHAT_TYPE_KEY INT,
# MAGIC 	DGTL_STTS_KEY INT,
# MAGIC 	GSTTNL_DLVRY_AGE_KEY INT,
# MAGIC 	MBR_AGE_KEY INT,
# MAGIC 	LIFE_CTGRY_KEY INT,
# MAGIC 	BRTH_WT_KEY INT,
# MAGIC 	BHF_MBR_TYPE_KEY INT,
# MAGIC 	PRFLG_CMPLT_PHASE_KEY INT,
# MAGIC 	--DLVRY_MNTH_KEY DOUBLE,
# MAGIC 	MTRNTY_RISK_LVL_KEY INT,
# MAGIC 	BHF_RWRD_ACTV_PRFL_KEY INT,
# MAGIC 	BHF_DLVRY_CHK_IN_QSTNR_IND STRING,
# MAGIC 	BHF_INTRCTN_IND STRING,
# MAGIC 	BHF_PRGNNCY_LOSS_QSTNR_IND STRING,
# MAGIC 	BLK_MTRNL_IND STRING,
# MAGIC 	BRST_FEEDG_IND STRING,
# MAGIC 	EPDSCRN_IND STRING,
# MAGIC 	GSTTNL_HTN_IND STRING,
# MAGIC 	LGBTQ_IND STRING,
# MAGIC 	--OUTPT_VAL_CD STRING,
# MAGIC 	PRGNNCY_IND STRING,
# MAGIC 	BHF_RWRD_ACTV_PRFL_CNT DOUBLE,
# MAGIC 	BHF_RWRD_POST_DLVRY_QSTNR_CNT DOUBLE,
# MAGIC 	BHF_RWRD_PRE_DLVRY_QSTNR_CNT DOUBLE,
# MAGIC 	BHF_RWRD_PRGNNCY_SCRNG_CNT DOUBLE,
# MAGIC 	BHF_STSFCN_SCOR_NBR DOUBLE,
# MAGIC 	CARE_COCH_CHAT_CNT DOUBLE,
# MAGIC 	EMRGNCY_DEPT_VST_CNT DOUBLE,
# MAGIC 	GRP_CNTRCT_SIZE_NBR DOUBLE,
# MAGIC 	GRP_CNTRCT_SIZE_SORT_NBR DOUBLE,
# MAGIC 	GRP_MBR_SIZE_NBR DOUBLE,
# MAGIC 	GRP_MBR_SIZE_SORT_NBR DOUBLE,
# MAGIC 	DERIVD_SORT_GRP_MBR_SIZE_RNG_TXT STRING,
# MAGIC 	GSTTNL_DLVRY_AGE_NBR DOUBLE,
# MAGIC 	HLTH_PGM_RPRSNTV_CHAT_CNT DOUBLE,
# MAGIC 	NICU_AMT DOUBLE,
# MAGIC 	NICU_SPNT_DAYS_NBR DOUBLE,
# MAGIC 	TOTL_INCMNG_MNTHLY_TLPHN_CALLS_CNT DOUBLE,
# MAGIC 	TOTL_OUTGNG_MNTHLY_TLPHN_CALLS_CNT DOUBLE,
# MAGIC 	PRFL_CREAT_DT DATE,
# MAGIC     DGTL_RGSTRD_DT DATE,
# MAGIC     RGSTRD_DT DATE,
# MAGIC     MBR_GSTTNL_AGE_NBR DOUBLE,
# MAGIC 	GRP_MBR_RNG_KEY INT,
# MAGIC 	GRP_CNTRCT_SIZE_KEY INT,
# MAGIC 	GRP_MBR_SIZE_KEY INT,
# MAGIC 	--M_ID INTEGER,
# MAGIC 	AGE_YEAR_NBR INT,
# MAGIC 	MCID_RANK_NBR BIGINT
# MAGIC 	--MCID_INCRD_YEAR_MNTH_RANK_NBR DOUBLE
# MAGIC 	  -- NEW FLAG COLUMNS
# MAGIC     --PREGNANCY_LOSS_FLAG DOUBLE,
# MAGIC     --DELIVERY_CHECKIN_FLAG DOUBLE,
# MAGIC     --POSTNATAL_DEPRESSION_FLAG DOUBLE,
# MAGIC     --CATEGORY_NAME STRING
# MAGIC 	--RN INTEGER
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_ADIM_PRDA_BHF_MBR_DTL_MEMBRSHP
# MAGIC SELECT  
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	CTGRY_NM ,
# MAGIC 	MCID_EDM_MBR_RANK_NBR ,
# MAGIC         SNAP_YEAR_MNTH_NBR,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	PROD_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	MCID,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	ZIP_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	JAA_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	BHFP_KEY,
# MAGIC 	CALL_CHAT_TYPE_KEY,
# MAGIC 	DGTL_STTS_KEY,
# MAGIC 	GSTTNL_DLVRY_AGE_KEY,
# MAGIC 	MBR_AGE_KEY,
# MAGIC 	LIFE_CTGRY_KEY,
# MAGIC 	BRTH_WT_KEY,
# MAGIC 	BHF_MBR_TYPE_KEY,
# MAGIC 	PRFLG_CMPLT_PHASE_KEY,
# MAGIC 	--DLVRY_MNTH_KEY,
# MAGIC 	MTRNTY_RISK_LVL_KEY,
# MAGIC 	BHF_RWRD_ACTV_PRFL_KEY,
# MAGIC 	BHF_DLVRY_CHK_IN_QSTNR_IND,
# MAGIC 	BHF_INTRCTN_IND,
# MAGIC 	BHF_PRGNNCY_LOSS_QSTNR_IND,
# MAGIC 	BLK_MTRNL_IND,
# MAGIC 	BRST_FEEDG_IND,
# MAGIC 	EPDSCRN_IND,
# MAGIC 	GSTTNL_HTN_IND,
# MAGIC 	LGBTQ_IND,
# MAGIC 	--OUTPT_VAL_CD,
# MAGIC 	PRGNNCY_IND,
# MAGIC 	BHF_RWRD_ACTV_PRFL_CNT,
# MAGIC 	BHF_RWRD_POST_DLVRY_QSTNR_CNT,
# MAGIC 	BHF_RWRD_PRE_DLVRY_QSTNR_CNT,
# MAGIC 	BHF_RWRD_PRGNNCY_SCRNG_CNT,
# MAGIC 	BHF_STSFCN_SCOR_NBR,
# MAGIC 	CARE_COCH_CHAT_CNT,
# MAGIC 	EMRGNCY_DEPT_VST_CNT,
# MAGIC 	GRP_CNTRCT_SIZE_NBR,
# MAGIC 	GRP_CNTRCT_SIZE_SORT_NBR,
# MAGIC 	GRP_MBR_SIZE_NBR,
# MAGIC 	GRP_MBR_SIZE_SORT_NBR,
# MAGIC 	DERIVD_SORT_GRP_MBR_SIZE_RNG_TXT,
# MAGIC 	GSTTNL_DLVRY_AGE_NBR,
# MAGIC 	HLTH_PGM_RPRSNTV_CHAT_CNT,
# MAGIC 	NICU_AMT,
# MAGIC 	NICU_SPNT_DAYS_NBR,
# MAGIC 	TOTL_INCMNG_MNTHLY_TLPHN_CALLS_CNT,
# MAGIC 	TOTL_OUTGNG_MNTHLY_TLPHN_CALLS_CNT,
# MAGIC 	CAST(PRFL_CREAT_DT AS DATE) AS PRFL_CREAT_DT,
# MAGIC     CAST(DGTL_RGSTRD_DT AS DATE) AS DGTL_RGSTRD_DT,
# MAGIC     CAST(RGSTRD_DT AS DATE) AS DGTL_RGSTRD_DT,
# MAGIC     MBR_GSTTNL_AGE_NBR,
# MAGIC 	GRP_MBR_RNG_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY ,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC     --DENSE_RANK() OVER (ORDER BY FACT_PRDA_BHF_MBR.MCID ASC) AS M_ID,
# MAGIC 	AGE_YEAR_NBR,
# MAGIC 	MCID_RANK_NBR
# MAGIC 	--MCID_INCRD_YEAR_MNTH_RANK_NBR
# MAGIC 	--CASE WHEN BHF_PRGNNCY_LOSS_QSTNR_IND = 'Y' THEN 1 ELSE 0 END as PREGNANCY_LOSS_FLAG,
# MAGIC     --CASE WHEN BHF_DLVRY_CHK_IN_QSTNR_IND = 'Y' THEN 1 ELSE 0 END as DELIVERY_CHECKIN_FLAG,
# MAGIC     --CASE WHEN EPDSCRN_IND = 'Y' THEN 1 ELSE 0 END as POSTNATAL_DEPRESSION_FLAG,
# MAGIC 	--CASE WHEN BHF_DLVRY_CHK_IN_QSTNR_IND ='Y' THEN 'Delivery Check-in'
# MAGIC     --WHEN EPDSCRN_IND ='Y' THEN 'Post-Natal Depression (EPDS)'
# MAGIC     --WHEN BHF_PRGNNCY_LOSS_QSTNR_IND= 'Y'  THEN 'Pregnancy Loss/Deleting a Pregnancy'
# MAGIC    	--END CATEGORY_NAME
# MAGIC /*ROW_NUMBER() OVER (
# MAGIC         PARTITION BY MCID, INCRD_YEAR_MNTH_NBR
# MAGIC         ORDER BY CAST(EDL_LOAD_DTM AS DATE) DESC,    
# MAGIC                  COALESCE(LIFE_CTGRY_KEY, -1) DESC    
# MAGIC     ) AS RN*/
# MAGIC 	
# MAGIC 	
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_PRDA_BHF_MBR
# MAGIC 	--WHERE INCRD_YEAR_MNTH_NBR BETWEEN 
# MAGIC --CAST (date_format(add_months(current_date(),-6),'yyyyMM') AS DECIMAL(6,0)) and
# MAGIC --CAST (date_format(current_date(),'yyyyMM')AS DECIMAL(6,0))
# MAGIC 	


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Sales_Lapse_Membrshp
# MAGIC (
# MAGIC 
# MAGIC 
# MAGIC     INCRD_MNTH_END_DT DATE,
# MAGIC 	INCRD_YEAR_MNTH_NBR INT,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 	MDCL_PROD_KEY INT,
# MAGIC 	GRP_BGN_DT DATE,
# MAGIC 	GRP_END_DT DATE,
# MAGIC 	MBR_SALE_LPSE_CTGRY_TXT STRING,
# MAGIC 	MBU_CLS_INDIV_CD STRING,
# MAGIC 	MDCL_MBU_CF_CD STRING,
# MAGIC 	MDCL_FUNDG_CF_CD STRING,
# MAGIC 	MCID BIGINT,
# MAGIC 	MBR_MNTH_NBR INT,
# MAGIC 	SPAN_BGN_NBR INT,
# MAGIC 	SPAN_END_NBR INT,
# MAGIC 	SPAN_PREV_GRP_SALE_NBR INT,
# MAGIC 	SPAN_RTRN_NBR INT
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Sales_Lapse_Membrshp
# MAGIC SELECT 
# MAGIC     
# MAGIC 	INCRD_MNTH_END_DT,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	MDCL_PROD_KEY,
# MAGIC 	GRP_BGN_DT,
# MAGIC 	GRP_END_DT,
# MAGIC 	MBR_SALE_LPSE_CTGRY_TXT,
# MAGIC 	MBU_CLS_INDIV_CD,
# MAGIC 	MDCL_MBU_CF_CD,
# MAGIC 	MDCL_FUNDG_CF_CD,
# MAGIC 	MCID,
# MAGIC 	MBR_MNTH_NBR,
# MAGIC 	SPAN_BGN_NBR,
# MAGIC 	SPAN_END_NBR,
# MAGIC 	SPAN_PREV_GRP_SALE_NBR,
# MAGIC 	SPAN_RTRN_NBR
# MAGIC 	
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.FACT_PRDA_SALE_LPSE;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Sales_Lapse_Groups_Membrshp
# MAGIC (
# MAGIC 
# MAGIC 
# MAGIC     INCRD_MNTH_END_DT DATE,
# MAGIC 	INCRD_YEAR_MNTH_NBR INT,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 	SALES_LAPS_CATG_TXT STRING
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Sales_Lapse_Groups_Membrshp
# MAGIC SELECT 
# MAGIC     
# MAGIC 	INCRD_MNTH_END_DT,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	SALES_LAPS_CATG_TXT
# MAGIC 
# MAGIC 	
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.FACT_PRDA_SALE_LPSE_GRP;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_Membrshp
# MAGIC (
# MAGIC     EDL_LOAD_DTM DATE,
# MAGIC 	PROD_KEY Double,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	ZIP_KEY Double,
# MAGIC 	CMPNY_CF_KEY Double,
# MAGIC 	EDM_MBR_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC 	FUNDG_CF_KEY Double,
# MAGIC 	GNDR_KEY Double,
# MAGIC 	GRP_CNTRCT_SIZE_KEY Double,
# MAGIC 	GRP_MBR_SIZE_KEY Double,
# MAGIC 	HW_KEY Double,
# MAGIC 	INCRD_YEAR_MNTH_NBR Double,
# MAGIC 	JAA_KEY Double,
# MAGIC 	MBU_CF_KEY Double,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY Double,
# MAGIC 	PROD_CF_KEY Double,
# MAGIC 	STNDRD_AGE_MNTH_KEY Double,
# MAGIC 	EOM_MBR_CNT Double,
# MAGIC 	PRORTD_MBR_MNTH_CNT Double,
# MAGIC 	SBSCRBR_CNT Double,
# MAGIC 	GRP_MBR_RNG_KEY DOUBLE
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WBS_MBR_SUMRY_Membrshp
# MAGIC SELECT  
# MAGIC     CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	PROD_KEY,
# MAGIC 	SNAP_YEAR_MNTH_NBR,
# MAGIC 	ZIP_KEY,
# MAGIC 	CMPNY_CF_KEY,
# MAGIC 	EDM_MBR_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 	EDM_CLNT_GRP_ACCT_KEY,
# MAGIC 	FUNDG_CF_KEY,
# MAGIC 	GNDR_KEY,
# MAGIC 	GRP_CNTRCT_SIZE_KEY,
# MAGIC 	GRP_MBR_SIZE_KEY,
# MAGIC 	HW_KEY,
# MAGIC 	INCRD_YEAR_MNTH_NBR,
# MAGIC 	JAA_KEY,
# MAGIC 	MBU_CF_KEY,
# MAGIC 	MCID_EDM_MBR_ACCT_KEY,
# MAGIC 	PROD_CF_KEY,
# MAGIC 	STNDRD_AGE_MNTH_KEY,
# MAGIC 	EOM_MBR_CNT,
# MAGIC 	PRORTD_MBR_MNTH_CNT,
# MAGIC 	SBSCRBR_CNT,
# MAGIC 	GRP_MBR_RNG_KEY
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_WBS_MBRSHP;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }
