# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "820ff289-52b1-4c8f-8705-a88c51f147ce",
# META       "default_lakehouse_name": "GOLD_LAKEHOUSE",
# META       "default_lakehouse_workspace_id": "890304bc-64e8-46be-93d9-8ea5a5a56669",
# META       "known_lakehouses": [
# META         {
# META           "id": "820ff289-52b1-4c8f-8705-a88c51f147ce"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInRead", "LEGACY")
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY")
spark.conf.set("spark.sql.parquet.vorder.enabled", "true")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_INCDNT_SESN_EAP
# MAGIC (
# MAGIC 	SNAP_YEAR_MNTH_NBR INT,
# MAGIC     INCDNT_NBR STRING,
# MAGIC     RPTG_MNTH_NBR INT,
# MAGIC     EAP_SESN_MNTH_NBR INT,
# MAGIC  	PROD_NM STRING,
# MAGIC     GRP_CD STRING,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC     EAP_GRP_ID STRING,
# MAGIC     TOTL_SESN_CNT DOUBLE,
# MAGIC     INCDNT_PRSNT_PRBLM_KEY INT,
# MAGIC     EAP_SUBGRP_ID STRING,
# MAGIC     SESN_MDL_KEY INT,
# MAGIC     CALR_TYPE_KEY INT,
# MAGIC INCDNT_ACTY_KEY INT,
# MAGIC INCDNT_SRVC_TYPE_KEY INT,
# MAGIC INCDNT_PROV_TYPE_KEY INT,
# MAGIC INCDNT_ENTY_KEY DECIMAL,
# MAGIC INCDNT_ST_KEY INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC STDALN_CD STRING
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_INCDNT_SESN_EAP
# MAGIC SELECT  
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC     INCDNT_NBR,
# MAGIC     RPTG_MNTH_NBR,
# MAGIC     EAP_SESN_MNTH_NBR,
# MAGIC  	PROD_NM,
# MAGIC     GRP_CD,
# MAGIC     EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC     EAP_GRP_ID,
# MAGIC     TOTL_SESN_CNT,
# MAGIC     INCDNT_PRSNT_PRBLM_KEY,
# MAGIC     EAP_SUBGRP_ID,
# MAGIC     SESN_MDL_KEY,
# MAGIC     CALR_TYPE_KEY,
# MAGIC INCDNT_ACTY_KEY,
# MAGIC INCDNT_SRVC_TYPE_KEY,
# MAGIC INCDNT_PROV_TYPE_KEY,
# MAGIC INCDNT_ENTY_KEY,
# MAGIC INCDNT_ST_KEY,
# MAGIC FUNDG_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC STDALN_CD 
# MAGIC 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_INCDNT_SESN;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark",
# META   "frozen": false,
# META   "editable": true
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_WBS_PROD_OUTRCH_EAP
# MAGIC (
# MAGIC 
# MAGIC --KF_TMS DATE,
# MAGIC HW_KEY INT,
# MAGIC PROD_KEY INT,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCRD_YEAR_MNTH_NBR INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC CMPNY_CF_KEY INT,
# MAGIC EDM_CLNT_SUBGRP_ACCT_KEY INT,
# MAGIC EAP_PROD_KEY INT,
# MAGIC 
# MAGIC INCDNT_ST_KEY INT,
# MAGIC PRORTD_MBR_MNTH_CNT INT,
# MAGIC EAP_GRP_ID STRING,
# MAGIC STDALN_CD STRING,
# MAGIC CALR_TYPE_KEY INT,
# MAGIC INCDNT_ACTY_KEY INT,
# MAGIC INCDNT_PROV_TYPE_KEY INT,
# MAGIC INCDNT_PRSNT_PRBLM_KEY INT,
# MAGIC INCDNT_SRVC_TYPE_KEY INT,
# MAGIC INCDNT_ENTY_KEY INT,
# MAGIC EAP_SUBGRP_ID STRING,
# MAGIC SESN_MDL_KEY INT
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_WBS_PROD_OUTRCH_EAP
# MAGIC SELECT  
# MAGIC --KF_TMS,
# MAGIC HW_KEY,
# MAGIC PROD_KEY,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC INCRD_YEAR_MNTH_NBR,
# MAGIC FUNDG_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC CMPNY_CF_KEY,
# MAGIC EDM_CLNT_SUBGRP_ACCT_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC 
# MAGIC INCDNT_ST_KEY,
# MAGIC PRORTD_MBR_MNTH_CNT,
# MAGIC EAP_GRP_ID,
# MAGIC CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC -- STDALN_CD,
# MAGIC CALR_TYPE_KEY,
# MAGIC INCDNT_ACTY_KEY,
# MAGIC INCDNT_PROV_TYPE_KEY,
# MAGIC INCDNT_PRSNT_PRBLM_KEY,
# MAGIC INCDNT_SRVC_TYPE_KEY,
# MAGIC INCDNT_ENTY_KEY,
# MAGIC EAP_SUBGRP_ID,
# MAGIC SESN_MDL_KEY
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_WBS_PROD_OUTRCH;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_WBS_MBR_SMRY_PROD_SUBCLS_EAP
# MAGIC (
# MAGIC 
# MAGIC 
# MAGIC --KF_TMS DATE,
# MAGIC HW_KEY INT,
# MAGIC PROD_KEY INT,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCRD_YEAR_MNTH_NBR INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC CMPNY_CF_KEY INT,
# MAGIC EDM_CLNT_SUBGRP_ACCT_KEY INT,
# MAGIC EAP_PROD_KEY INT,
# MAGIC 
# MAGIC INCDNT_ST_KEY INT,
# MAGIC PRORTD_MBR_MNTH_CNT  DECIMAL(38,18),
# MAGIC STDALN_CD STRING,
# MAGIC EAP_GRP_ID STRING,
# MAGIC CALR_TYPE_KEY INT,
# MAGIC INCDNT_ACTY_KEY INT,
# MAGIC INCDNT_PROV_TYPE_KEY INT,
# MAGIC INCDNT_PRSNT_PRBLM_KEY INT,
# MAGIC INCDNT_SRVC_TYPE_KEY INT,
# MAGIC INCDNT_ENTY_KEY INT,
# MAGIC EAP_SUBGRP_ID STRING,
# MAGIC SESN_MDL_KEY INT
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_WBS_MBR_SMRY_PROD_SUBCLS_EAP
# MAGIC SELECT  
# MAGIC --KF_TMS,
# MAGIC HW_KEY,
# MAGIC PROD_KEY,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC INCRD_YEAR_MNTH_NBR,
# MAGIC FUNDG_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC CMPNY_CF_KEY,
# MAGIC EDM_CLNT_SUBGRP_ACCT_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC 
# MAGIC INCDNT_ST_KEY,
# MAGIC PRORTD_MBR_MNTH_CNT,
# MAGIC CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC -- STDALN_CD,
# MAGIC EAP_GRP_ID,
# MAGIC CALR_TYPE_KEY,
# MAGIC INCDNT_ACTY_KEY,
# MAGIC INCDNT_PROV_TYPE_KEY,
# MAGIC INCDNT_PRSNT_PRBLM_KEY,
# MAGIC INCDNT_SRVC_TYPE_KEY,
# MAGIC INCDNT_ENTY_KEY,
# MAGIC EAP_SUBGRP_ID,
# MAGIC SESN_MDL_KEY 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_WBS_MBR_SMRY_PROD_SUBCLS;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_WORK_MBR_MDCL_PROD_DTL_EAP
# MAGIC (
# MAGIC 
# MAGIC --KF_TMS DATE,
# MAGIC HW_KEY INT,
# MAGIC PROD_KEY INT,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCRD_YEAR_MNTH_NBR INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC CMPNY_CF_KEY INT,
# MAGIC EDM_CLNT_SUBGRP_ACCT_KEY INT,
# MAGIC EAP_PROD_KEY INT,
# MAGIC 
# MAGIC INCDNT_ST_KEY INT,
# MAGIC PRORTD_MBR_MNTH_CNT DECIMAL(38,18),
# MAGIC STDALN_CD STRING,
# MAGIC EAP_GRP_ID STRING,
# MAGIC CALR_TYPE_KEY INT,
# MAGIC INCDNT_ACTY_KEY INT,
# MAGIC INCDNT_PROV_TYPE_KEY INT,
# MAGIC INCDNT_PRSNT_PRBLM_KEY INT,
# MAGIC INCDNT_SRVC_TYPE_KEY INT,
# MAGIC INCDNT_ENTY_KEY INT,
# MAGIC EAP_SUBGRP_ID STRING,
# MAGIC SESN_MDL_KEY INT
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_WORK_MBR_MDCL_PROD_DTL_EAP
# MAGIC SELECT  
# MAGIC --KF_TMS,
# MAGIC HW_KEY,
# MAGIC PROD_KEY,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC INCRD_YEAR_MNTH_NBR,
# MAGIC FUNDG_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC CMPNY_CF_KEY,
# MAGIC EDM_CLNT_SUBGRP_ACCT_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC 
# MAGIC INCDNT_ST_KEY,
# MAGIC PRORTD_MBR_MNTH_CNT,
# MAGIC CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC -- STDALN_CD,
# MAGIC EAP_GRP_ID,
# MAGIC CALR_TYPE_KEY,
# MAGIC INCDNT_ACTY_KEY,
# MAGIC INCDNT_PROV_TYPE_KEY,
# MAGIC INCDNT_PRSNT_PRBLM_KEY,
# MAGIC INCDNT_SRVC_TYPE_KEY,
# MAGIC INCDNT_ENTY_KEY,
# MAGIC EAP_SUBGRP_ID,
# MAGIC SESN_MDL_KEY 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_WORK_MBR_MDCL_PROD_DTL;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_SPRVSR_RFRL_DTL_EAP
# MAGIC (
# MAGIC 
# MAGIC --KF_TMS DATE,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC EAP_GRP_ID STRING,
# MAGIC EAP_Subgroup_ID STRING,
# MAGIC CMPNY_CF_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC Incident_State_Code INT,
# MAGIC MCID_EDM_Member_Account_Key INT,
# MAGIC PROD_KEY INT,
# MAGIC EDM_Member_Account_Key INT,
# MAGIC CNSLT_TYPE_KEY INT,
# MAGIC EAP_Product_Key INT,
# MAGIC Master_Consumer_Identifier_MCID INT,
# MAGIC Member_Key STRING,
# MAGIC Management_Consultation_ID INT,
# MAGIC Standalone_Code STRING,
# MAGIC RPTG_MNTH_NBR INT,
# MAGIC TOTL_CNSLT_TM_CNT INT,
# MAGIC Supervisor_Referral_ID STRING,
# MAGIC Incident_Number STRING,
# MAGIC Member_Reference_Number STRING,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 
# MAGIC SESN_MDL_KEY INT,
# MAGIC RFRL_RSN_KEY INT
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_SPRVSR_RFRL_DTL_EAP
# MAGIC SELECT  
# MAGIC --KF_TMS,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC EAP_GRP_ID,
# MAGIC EAP_SUBGRP_ID,
# MAGIC CMPNY_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC FUNDG_CF_KEY,
# MAGIC INCDNT_ST_KEY,
# MAGIC MCID_EDM_MBR_ACCT_KEY,
# MAGIC PROD_KEY,
# MAGIC EDM_MBR_ACCT_KEY,
# MAGIC CNSLT_TYPE_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC MCID,
# MAGIC MBR_KEY,
# MAGIC MNGMNT_CNSLT_ID,
# MAGIC CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC -- STDALN_CD,
# MAGIC RPTG_MNTH_NBR,
# MAGIC TOTL_CNSLT_TM_CNT,
# MAGIC SUPR_RFRL_ID,
# MAGIC INCDNT_NBR,
# MAGIC MBR_RFRNC_NBR,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 
# MAGIC SESN_MDL_KEY,
# MAGIC RFRL_RSN_KEY
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_SPRVSR_RFRL_DTL;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_GRP_SUBGRP_EAP
# MAGIC (
# MAGIC 
# MAGIC --KF_TMS Date,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC EAP_GRP_ID STRING,
# MAGIC EAP_SUBGRP_ID STRING,
# MAGIC Company_Chart_Field_Code INT,
# MAGIC EAP_PROD_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC INCDNT_ST_KEY INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC Standalone_Code STRING,
# MAGIC ELGBL_MNTH_NBR INT,
# MAGIC Group_Employee_Count INT,
# MAGIC Group_Estimated_Member_Count INT,
# MAGIC Subgroup_Employee_Count INT,
# MAGIC Subgroup_Estimated_Member_Count INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 
# MAGIC SESN_MDL_KEY INT
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_GRP_SUBGRP_EAP
# MAGIC SELECT  
# MAGIC 
# MAGIC --KF_TMS,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC EAP_GRP_ID,
# MAGIC EAP_SUBGRP_ID,
# MAGIC CMPNY_CF_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC INCDNT_ST_KEY,
# MAGIC FUNDG_CF_KEY,
# MAGIC CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC -- STDALN_CD,
# MAGIC ELGBL_MNTH_NBR,
# MAGIC GRP_EMP_CNT,
# MAGIC GRP_MBR_CNT,
# MAGIC SUBGRP_EMP_CNT,
# MAGIC SUBGRP_MBR_CNT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 
# MAGIC SESN_MDL_KEY 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_GRP_SUBGRP;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_MBR_INCDNT_DTL_EAP
# MAGIC (
# MAGIC 
# MAGIC --KF_TMS Date,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC INCDNT_PRSNT_PRBLM_KEY INT,
# MAGIC INCDNT_MNTH_NBR INT,
# MAGIC INCDNT_NBR STRING,
# MAGIC INCDNT_ENTY_KEY INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC CMPNY_CF_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC EAP_GRP_ID STRING,
# MAGIC PROD_KEY INT,
# MAGIC EDM_CLNT_GRP_ACCT_KEY INT,
# MAGIC INCDNT_SRVC_TYPE_KEY INT,
# MAGIC CALR_TYPE_KEY INT,
# MAGIC INCDNT_PROV_TYPE_KEY INT,
# MAGIC INCDNT_CNSLG_TYPE_KEY INT,
# MAGIC INCDNT_ACTY_KEY INT,
# MAGIC 
# MAGIC Incident_Information_Source_Code INT,
# MAGIC MCID_EDM_MBR_ACCT_KEY INT,
# MAGIC Master_Consumer_Identifier_MCID INT,
# MAGIC Member_Reference_Number STRING,
# MAGIC EDM_MBR_ACCT_KEY INT,
# MAGIC EAP_SUBGRP_ID STRING,
# MAGIC Incident_State_Code INT,
# MAGIC Incident_Presenting_Problem_2_Code INT,
# MAGIC EAP_Product_Key INT,
# MAGIC SESN_CMPLTD_CNT INT,
# MAGIC Standalone_Code STRING,
# MAGIC SESN_MDL_KEY INT
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_MBR_INCDNT_DTL_EAP
# MAGIC SELECT  
# MAGIC 
# MAGIC --KF_TMS,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC INCDNT_PRSNT_PRBLM_KEY,
# MAGIC INCDNT_MNTH_NBR,
# MAGIC INCDNT_NBR,
# MAGIC INCDNT_ENTY_KEY,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC CMPNY_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC FUNDG_CF_KEY,
# MAGIC EAP_GRP_ID,
# MAGIC PROD_KEY,
# MAGIC EDM_CLNT_GRP_ACCT_KEY,
# MAGIC INCDNT_SRVC_TYPE_KEY,
# MAGIC CALR_TYPE_KEY,
# MAGIC INCDNT_PROV_TYPE_KEY,
# MAGIC INCDNT_CNSLG_TYPE_KEY,
# MAGIC INCDNT_ACTY_KEY,
# MAGIC 
# MAGIC INCDNT_INFO_SRC_KEY,
# MAGIC MCID_EDM_MBR_ACCT_KEY,
# MAGIC MCID,
# MAGIC MBR_RFRNC_NBR,
# MAGIC EDM_MBR_ACCT_KEY,
# MAGIC EAP_SUBGRP_ID,
# MAGIC INCDNT_ST_KEY,
# MAGIC INCDNT_PRSNT_PRBLM_2_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC SESN_CMPLTD_CNT,
# MAGIC CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC -- STDALN_CD,
# MAGIC SESN_MDL_KEY 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_MBR_INCDNT_DTL;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_EVNT_DTL_EAP
# MAGIC (
# MAGIC 
# MAGIC --KF_TMS Date,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC RPTG_MNTH_NBR INT,
# MAGIC Event_ID INT,
# MAGIC EAP_GRP_ID STRING,
# MAGIC EAP_Subgroup_ID STRING,
# MAGIC Company_Chart_Field_Code INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC Incident_State_Code INT,
# MAGIC Standalone_Code STRING,
# MAGIC SRVC_TYPE_KEY INT,
# MAGIC EAP_PROD_KEY INT,
# MAGIC Provider_Hours INT,
# MAGIC Participant_Count INT,
# MAGIC Provider_Cost_Amount INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 
# MAGIC Employer_Allocated_Hours DECIMAL(10,2),
# MAGIC SESN_MDL_KEY INT
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_EVNT_DTL_EAP
# MAGIC SELECT  
# MAGIC 
# MAGIC --KF_TMS,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC RPTG_MNTH_NBR,
# MAGIC EVNT_ID,
# MAGIC EAP_GRP_ID,
# MAGIC EAP_SUBGRP_ID,
# MAGIC CMPNY_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC FUNDG_CF_KEY,
# MAGIC INCDNT_ST_KEY,
# MAGIC  CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC 
# MAGIC -- STDALN_CD,
# MAGIC SRVC_TYPE_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC PROV_HOURS_NBR,
# MAGIC PRTCPNT_CNT,
# MAGIC PROV_COST_AMT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 
# MAGIC EMPLR_ALCTD_HOURS_NBR,
# MAGIC SESN_MDL_KEY 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_EVNT_DTL;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_MNGMNT_CNSLTTN_DTL_EAP
# MAGIC (
# MAGIC 
# MAGIC --KF_TMS Date,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC EAP_GRP_ID STRING,
# MAGIC EAP_SUBGRP_ID STRING,
# MAGIC Master_Consumer_Identifier_MCID INT,
# MAGIC Member_Key STRING,
# MAGIC MCID_EDM_Member_Account_Key INT,
# MAGIC PROD_KEY INT,
# MAGIC EDM_Member_Account_Key INT,
# MAGIC Company_Chart_Field_Code INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC INCDNT_ST_KEY INT,
# MAGIC EAP_PROD_KEY INT,
# MAGIC CNSLT_TYPE_KEY INT,
# MAGIC Management_Consultation_ID INT,
# MAGIC Standalone_Code STRING,
# MAGIC RPTG_MNTH_NBR INT,
# MAGIC Total_Consultation_Time INT,
# MAGIC Member_Reference_Number STRING,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC 
# MAGIC SESN_MDL_KEY INT
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_MNGMNT_CNSLTTN_DTL_EAP
# MAGIC SELECT  
# MAGIC 
# MAGIC --KF_TMS,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC EAP_GRP_ID,
# MAGIC EAP_SUBGRP_ID,
# MAGIC MCID,
# MAGIC MBR_KEY,
# MAGIC MCID_EDM_MBR_ACCT_KEY,
# MAGIC PROD_KEY,
# MAGIC EDM_MBR_ACCT_KEY,
# MAGIC CMPNY_CF_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC FUNDG_CF_KEY,
# MAGIC INCDNT_ST_KEY,
# MAGIC EAP_PROD_KEY,
# MAGIC CNSLT_TYPE_KEY,
# MAGIC MNGMNT_CNSLT_ID,
# MAGIC 
# MAGIC    CASE WHEN STDALN_CD = 'YES' THEN 'YES' ELSE 'NO' END AS STDALN_CD,
# MAGIC 
# MAGIC -- STDALN_CD,
# MAGIC RPTG_MNTH_NBR,
# MAGIC TOTL_CNSLT_TM_CNT,
# MAGIC MBR_RFRNC_NBR,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC 
# MAGIC SESN_MDL_KEY 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_MNGMNT_CNSLTTN_DTL;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_EAP_SRVY_DTL_EAP
# MAGIC (
# MAGIC 
# MAGIC 
# MAGIC --KF_TMS DATE,
# MAGIC SNAP_YEAR_MNTH_NBR INT,
# MAGIC RPTG_MNTH_NBR INT,
# MAGIC QSTNR_MBR_RSPNS_ID STRING,
# MAGIC QSTNR_ID STRING,
# MAGIC CREATD_DTM DATE,
# MAGIC LAST_MDFD_DTM DATE,
# MAGIC -- QSTNR_NM STRING,
# MAGIC EAP_MBR_RFRNC_NBR STRING,
# MAGIC SRVY_TYPE_NM STRING,
# MAGIC -- RSRC_TYPE_TXT STRING,
# MAGIC OUTRCH_ID STRING,
# MAGIC -- RSPNDG_MBR_TYPE_TXT STRING,
# MAGIC -- OUTRCH_CNTCT_TYPE_TXT STRING,
# MAGIC OUTRCH_CMPLTD_DT DATE,
# MAGIC OUTRCH_SENT_DT DATE,
# MAGIC OUTRCH_RMNDR_DT DATE,
# MAGIC INCDNT_NBR STRING,
# MAGIC -- CNVRSTN_CNTCT_TYPE_TXT STRING,
# MAGIC -- OUTRCH_STTS_TXT STRING,
# MAGIC -- OUTRCH_DLVRY_STTS_TXT STRING,
# MAGIC ITEM_LNK_ID STRING,
# MAGIC -- QSTN_TXT STRING,
# MAGIC -- QSTN_ANSWR_TXT STRING,
# MAGIC ITEM_2_LNK_ID STRING,
# MAGIC -- QSTN_2_TXT STRING,
# MAGIC -- QSTN_ANSWR_2_TXT STRING,
# MAGIC EAP_GRP_ID STRING,
# MAGIC EAP_SUBGRP_ID STRING,
# MAGIC ST_KEY INT,
# MAGIC 
# MAGIC SESN_CMPLTD_CNT INT,
# MAGIC EAP_PROD_KEY INT,
# MAGIC MBU_CF_KEY INT,
# MAGIC FUNDG_CF_KEY INT,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY INT,
# MAGIC -- WOS_KEY INT,
# MAGIC WOS_MATCH_IND INT,
# MAGIC -- PHQ_KEY INT,
# MAGIC PHQ_MATCH_IND INT,
# MAGIC -- GAD_KEY INT,
# MAGIC GAD_MATCH_IND INT,
# MAGIC PRSNT_PRBLM_KEY INT,
# MAGIC PHQ_TYPE_CD STRING,
# MAGIC WOS_TYPE_CD STRING,
# MAGIC GAD_TYPE_CD STRING,
# MAGIC SRVY_ACTV_IND STRING,
# MAGIC OUTRCH_TYPE STRING,
# MAGIC STDALN_CD STRING,
# MAGIC MBR_INCDNT_KEY STRING,
# MAGIC SESN_MDL_KEY INT
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_EAP_SRVY_DTL_EAP
# MAGIC SELECT  
# MAGIC 
# MAGIC 
# MAGIC --KF_TMS,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC RPTG_MNTH_NBR,
# MAGIC QSTNR_MBR_RSPNS_ID,
# MAGIC QSTNR_ID,
# MAGIC CREATD_DTM,
# MAGIC LAST_MDFD_DTM,
# MAGIC -- QSTNR_NM,
# MAGIC EAP_MBR_RFRNC_NBR,
# MAGIC SRVY_TYPE_NM,
# MAGIC -- RSRC_TYPE_TXT,
# MAGIC OUTRCH_ID,
# MAGIC -- RSPNDG_MBR_TYPE_TXT,
# MAGIC -- OUTRCH_CNTCT_TYPE_TXT,
# MAGIC OUTRCH_CMPLTD_DT,
# MAGIC OUTRCH_SENT_DT,
# MAGIC OUTRCH_RMNDR_DT,
# MAGIC INCDNT_NBR,
# MAGIC -- CNVRSTN_CNTCT_TYPE_TXT,
# MAGIC -- OUTRCH_STTS_TXT,
# MAGIC -- OUTRCH_DLVRY_STTS_TXT,
# MAGIC ITEM_LNK_ID,
# MAGIC -- QSTN_TXT,
# MAGIC -- QSTN_ANSWR_TXT,
# MAGIC ITEM_2_LNK_ID,
# MAGIC -- QSTN_2_TXT,
# MAGIC -- QSTN_ANSWR_2_TXT,
# MAGIC EAP_GRP_ID,
# MAGIC EAP_SUBGRP_ID,
# MAGIC ST_KEY,
# MAGIC 
# MAGIC SESN_CMPLTD_CNT,
# MAGIC EAP_PROD_KEY,
# MAGIC MBU_CF_KEY,
# MAGIC FUNDG_CF_KEY,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY,
# MAGIC WOS_KEY,
# MAGIC PHQ_KEY,
# MAGIC GAD_KEY,
# MAGIC PRSNT_PRBLM_KEY,
# MAGIC PHQ_TYPE_CD,
# MAGIC WOS_TYPE_CD,
# MAGIC GAD_TYPE_CD,
# MAGIC SRVY_ACTV_IND,
# MAGIC OUTRCH_TYPE,
# MAGIC STDALN_CD,
# MAGIC MBR_INCDNT_KEY,
# MAGIC SESN_MDL_KEY 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.FACT_EAP_SRVY_DTL;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }
