# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "820ff289-52b1-4c8f-8705-a88c51f147ce",
# META       "default_lakehouse_name": "GOLD_LAKEHOUSE",
# META       "default_lakehouse_workspace_id": "890304bc-64e8-46be-93d9-8ea5a5a56669",
# META       "known_lakehouses": [
# META         {
# META           "id": "820ff289-52b1-4c8f-8705-a88c51f147ce"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Welcome to your new notebook
# Type here in the cell editor to add code!
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInRead", "LEGACY")
spark.conf.set("spark.sql.parquet.datetimeRebaseModeInWrite", "LEGACY")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# ### HWBS DIMS

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.gender (
# MAGIC     Gender STRING,
# MAGIC     GNDR_CD STRING,
# MAGIC     GNDR_KEY DOUBLE
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.gender
# MAGIC SELECT 
# MAGIC GNDR_NM ,
# MAGIC GNDR_CD,
# MAGIC GNDR_KEY
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_GNDR;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Product_Chart_Field(
# MAGIC     
# MAGIC     Product_Chart_Field STRING,
# MAGIC     Product_Chart_Field_Cd STRING,
# MAGIC     PROD_CF_KEY DOUBLE
# MAGIC     
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Product_Chart_Field
# MAGIC SELECT 
# MAGIC     PROD_CF_NM ,
# MAGIC     PROD_CF_CD,
# MAGIC     PROD_CF_KEY
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_PROD_CF;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Member_Account_HWBS
# MAGIC (
# MAGIC 	Member_Account_Key INT,
# MAGIC 	--Subscriber_Account_Key INT,
# MAGIC 	--Member_Original_Effective_Dt DATE,
# MAGIC 	--Health_Card_Id INT,
# MAGIC 	--MBRSHP_SOR_CD STRING,
# MAGIC 	--Subscriber_Id STRING,
# MAGIC 	--Medicaid_Nbr Double,
# MAGIC 	--Medicare_Nbr Double,
# MAGIC 	--MBR_SQNC_NBR Double,
# MAGIC 	MCID Double,
# MAGIC 	--Prefix STRING,
# MAGIC 	--First_Nm STRING,
# MAGIC 	--Suffix_STRING,
# MAGIC 	--Middle_Initial STRING,
# MAGIC 	--Last_Nm STRING,
# MAGIC 	--Member_Birth_Dt DATE,
# MAGIC 	--Deceased_Dt DATE,
# MAGIC     GNDR_CD STRING
# MAGIC 	--Language_Cd STRING,
# MAGIC 	--Member_Relationship_Cd STRING,
# MAGIC 	--Marital_Status_Cd STRING,
# MAGIC 	--Race STRING,
# MAGIC 	--Member_key STRING,
# MAGIC 	--Security_Level_Cd STRING,
# MAGIC 	--MBR_SQNC_ID STRING
# MAGIC 	--SBSCRBR_RLTNSHP_CD STRING,
# MAGIC 	--SBSCRBR_RLTNSHP_NM STRING,
# MAGIC 	--SBSCRBR_RLTNSHP_DESC STRING,
# MAGIC 	--RACE_ETHNCTY_CD STRING,
# MAGIC 	--RACE_ETHNCTY_IMPTD_IND STRING
# MAGIC 	);
# MAGIC 	
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Member_Account_HWBS
# MAGIC SELECT  
# MAGIC 	EDM_MBR_ACCT_KEY ,
# MAGIC 	--SBSCRBR_EDM_MBR_ACCT_KEY,
# MAGIC 	--MBR_ORGNL_EFCTV_DT ,
# MAGIC 	--HC_ID,
# MAGIC 	--MBRSHP_SOR_CD ,
# MAGIC 	--SBSCRBR_ID ,
# MAGIC 	--MDCD_NBR,
# MAGIC 	--MEDCR_NBR,
# MAGIC 	--MBR_SQNC_NBR ,
# MAGIC 	MCID ,
# MAGIC 	--PRFX_NM ,
# MAGIC 	--FRST_NM,
# MAGIC 	--SFX_NM ,
# MAGIC 	--MID_INIT_NM,
# MAGIC 	--LAST_NM,
# MAGIC 	--MBR_BRTH_DT,
# MAGIC 	--CAST(DCESD_DT AS DATE) AS DCESD_DT,
# MAGIC 	GNDR_CD
# MAGIC 	--LANG_CD ,
# MAGIC 	--MBR_RLTNSHP_CD,
# MAGIC 	--MRTL_STTS_CD,
# MAGIC 	--RACE_CD ,
# MAGIC 	--MBR_KEY ,
# MAGIC 	--SCRTY_LVL_CD ,
# MAGIC 	--MBR_SQNC_ID ,
# MAGIC 	--SBSCRBR_RLTNSHP_CD ,
# MAGIC 	--SBSCRBR_RLTNSHP_NM ,
# MAGIC 	--SBSCRBR_RLTNSHP_DESC ,
# MAGIC 	--RACE_ETHNCTY_CD ,
# MAGIC 	--RACE_ETHNCTY_IMPTD_IND
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_MBR_ACCT;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Member_Account
# MAGIC (
# MAGIC 	Member_Account_Key INT,
# MAGIC 	Subscriber_Account_Key INT,
# MAGIC 	Member_Original_Effective_Dt DATE,
# MAGIC 	Health_Card_Id STRING,
# MAGIC 	MBRSHP_SOR_CD STRING,
# MAGIC 	Subscriber_Id STRING,
# MAGIC 	Medicaid_Nbr STRING,
# MAGIC 	Medicare_Nbr STRING,
# MAGIC 	MBR_SQNC_NBR STRING,
# MAGIC 	MCID Double,
# MAGIC 	Prefix STRING,
# MAGIC 	First_Nm STRING,
# MAGIC 	Suffix STRING,
# MAGIC 	Middle_Initial STRING,
# MAGIC 	Last_Nm STRING,
# MAGIC 	Member_Birth_Dt DATE,
# MAGIC 	Deceased_Dt DATE,
# MAGIC     GNDR_CD STRING,
# MAGIC 	Language_Cd STRING,
# MAGIC 	Marital_Status_Cd  STRING,
# MAGIC 	Race STRING,
# MAGIC 	Member_key STRING,
# MAGIC 	Security_Level_Cd STRING,
# MAGIC 	MBR_SQNC_ID STRING,
# MAGIC 	SBSCRBR_RLTNSHP_CD STRING,
# MAGIC 	SBSCRBR_RLTNSHP_NM STRING,
# MAGIC 	SBSCRBR_RLTNSHP_DESC STRING,
# MAGIC 	RACE_ETHNCTY_CD STRING,
# MAGIC 	RACE_ETHNCTY_IMPTD_IND STRING
# MAGIC 	);
# MAGIC 	
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Member_Account
# MAGIC SELECT  
# MAGIC 	EDM_MBR_ACCT_KEY ,
# MAGIC 	SBSCRBR_EDM_MBR_ACCT_KEY,
# MAGIC 	MBR_ORGNL_EFCTV_DT ,
# MAGIC 	HC_ID,
# MAGIC 	MBRSHP_SOR_CD ,
# MAGIC 	SBSCRBR_ID ,
# MAGIC 	MDCD_NBR,
# MAGIC 	MEDCR_NBR,
# MAGIC 	MBR_SQNC_NBR ,
# MAGIC 	MCID ,
# MAGIC 	PRFX_NM ,
# MAGIC 	FRST_NM,
# MAGIC 	SFX_NM ,
# MAGIC 	MID_INIT_NM,
# MAGIC 	LAST_NM,
# MAGIC 	MBR_BRTH_DT,
# MAGIC 	CAST(DCESD_DT AS DATE) AS DCESD_DT,
# MAGIC 	GNDR_CD,
# MAGIC 	LANG_CD ,
# MAGIC 	MRTL_STTS_CD,
# MAGIC 	RACE_CD ,
# MAGIC 	MBR_KEY ,
# MAGIC 	SCRTY_LVL_CD ,
# MAGIC 	MBR_SQNC_ID ,
# MAGIC 	SBSCRBR_RLTNSHP_CD ,
# MAGIC 	SBSCRBR_RLTNSHP_NM ,
# MAGIC 	SBSCRBR_RLTNSHP_DESC ,
# MAGIC 	RACE_ETHNCTY_CD ,
# MAGIC 	RACE_ETHNCTY_IMPTD_IND
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_MBR_ACCT;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_TXNMY_HWBS
# MAGIC (
# MAGIC HW_KEY INT,
# MAGIC --PKG_KEY INT,
# MAGIC HW_PROD_KEY INT,
# MAGIC BUY_UP_PGM_IND STRING,
# MAGIC PGM_ID STRING,
# MAGIC Program_Name STRING,
# MAGIC MRKTG_PROD_NM STRING,
# MAGIC Program_Type STRING,
# MAGIC Program_Class STRING,
# MAGIC Program_Sub_Class STRING,
# MAGIC PGM_BU_NM STRING,
# MAGIC RCRD_STTS_CD STRING,
# MAGIC PFOL_YEAR_NBR Double,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC BNFT_PKG_ID STRING,
# MAGIC Package_Type STRING,
# MAGIC Package_Class STRING,
# MAGIC Portfolio STRING,
# MAGIC --ST_CD STRING,
# MAGIC --FUNDG_CLS_TXT STRING,
# MAGIC MBU_CLS_TXT STRING,
# MAGIC --TMPLT_EFCTV_DT DATE,
# MAGIC --TMPLT_TRMNTN_DT DATE,
# MAGIC --TMPLT_NM STRING,
# MAGIC --TMPLT_YEAR_NBR Double,
# MAGIC INCNTV_PKG_TYPE_TXT STRING,
# MAGIC INCNTV_PKG_CAP_AMT Double,
# MAGIC INCNTV_PKG_CLS_TXT STRING,
# MAGIC INCNTV_PKG_NM STRING,
# MAGIC --DSBRSMNT_TYPE_TXT STRING,
# MAGIC --OPT_ID STRING,
# MAGIC --OPT_NM STRING,
# MAGIC --HLTH_PGM_BNFT_PKG_EFCTV_DT DATE,
# MAGIC --HLTH_PGM_BNFT_PKG_TRMNTN_DT DATE,
# MAGIC --BNFT_PKG_EFCTV_DT DATE,
# MAGIC --BNFT_PKG_TRMNTN_DT DATE,
# MAGIC --EHP_SALES_PKG_NM STRING,
# MAGIC PGM_LVL_IDFCTN_NM STRING,
# MAGIC PGM_RPTG_IND STRING,
# MAGIC HWBS_Product_ID STRING,
# MAGIC HWBS_Product_Name STRING,
# MAGIC HWBS_Reporting_Product_Name STRING,
# MAGIC HWBS_Product_Type STRING,
# MAGIC HWBS_Product_Class STRING,
# MAGIC HWBS_Product_Sub_Class STRING,
# MAGIC HWBS_Product_Business_Unit_Name STRING,
# MAGIC HWBS_Product_Reporting_Indicator STRING,
# MAGIC HWBS_Product_Level_Identification_Name STRING
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_TXNMY_HWBS
# MAGIC SELECT  
# MAGIC HW_KEY ,
# MAGIC --PKG_KEY ,
# MAGIC HW_PROD_KEY ,
# MAGIC BUY_UP_PGM_IND ,
# MAGIC PGM_ID ,
# MAGIC RPTG_PGM_NM ,
# MAGIC MRKTG_PROD_NM ,
# MAGIC PGM_TYPE_DESC ,
# MAGIC PGM_CLS_DESC ,
# MAGIC PGM_SUB_CLS_DESC ,
# MAGIC PGM_BU_NM ,
# MAGIC RCRD_STTS_CD ,
# MAGIC PFOL_YEAR_NBR ,
# MAGIC HLTH_PGM_BNFT_PKG_ID ,
# MAGIC BNFT_PKG_ID ,
# MAGIC PKG_TYPE_NM ,
# MAGIC PKG_CLS_NM ,
# MAGIC PFOL_NM ,
# MAGIC --ST_CD ,
# MAGIC --FUNDG_CLS_TXT ,
# MAGIC MBU_CLS_TXT ,
# MAGIC --CAST(TMPLT_EFCTV_DT AS DATE) AS TMPLT_EFCTV_DT,
# MAGIC --CAST(TMPLT_TRMNTN_DT AS DATE) AS TMPLT_TRMNTN_DT ,
# MAGIC --TMPLT_NM ,
# MAGIC --TMPLT_YEAR_NBR ,
# MAGIC INCNTV_PKG_TYPE_TXT ,
# MAGIC INCNTV_PKG_CAP_AMT ,
# MAGIC INCNTV_PKG_CLS_TXT ,
# MAGIC INCNTV_PKG_NM ,
# MAGIC --DSBRSMNT_TYPE_TXT ,
# MAGIC --OPT_ID ,
# MAGIC --OPT_NM ,
# MAGIC --CAST(HLTH_PGM_BNFT_PKG_EFCTV_DT AS DATE) AS  HLTH_PGM_BNFT_PKG_EFCTV_DT ,
# MAGIC --CAST(HLTH_PGM_BNFT_PKG_TRMNTN_DT AS DATE) AS HLTH_PGM_BNFT_PKG_TRMNTN_DT ,
# MAGIC --CAST(BNFT_PKG_EFCTV_DT AS DATE) AS  BNFT_PKG_EFCTV_DT ,
# MAGIC --CAST(BNFT_PKG_TRMNTN_DT AS DATE) AS BNFT_PKG_TRMNTN_DT ,
# MAGIC --EHP_SALES_PKG_NM ,
# MAGIC PGM_LVL_IDFCTN_NM ,
# MAGIC PGM_RPTG_IND ,
# MAGIC PROD_ID ,
# MAGIC PROD_NM ,
# MAGIC RPTG_PROD_NM ,
# MAGIC PROD_TYPE_DESC ,
# MAGIC PROD_CLS_DESC ,
# MAGIC PROD_SUB_CLS_DESC ,
# MAGIC PROD_BU_NM ,
# MAGIC PROD_RPTG_IND ,
# MAGIC PROD_LVL_IDFCTN_NM
# MAGIC 
# MAGIC FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_HW_PKG_PGM;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_TXNMY
# MAGIC (
# MAGIC HW_KEY INT,
# MAGIC PKG_KEY INT,
# MAGIC HW_PROD_KEY INT,
# MAGIC BUY_UP_PGM_IND STRING,
# MAGIC PGM_ID STRING,
# MAGIC Program_Name STRING,
# MAGIC MRKTG_PROD_NM STRING,
# MAGIC Program_Type STRING,
# MAGIC Program_Class STRING,
# MAGIC Program_Sub_Class STRING,
# MAGIC PGM_BU_NM STRING,
# MAGIC RCRD_STTS_CD STRING,
# MAGIC PFOL_YEAR_NBR Double,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC BNFT_PKG_ID STRING,
# MAGIC Package_Type STRING,
# MAGIC Package_Class STRING,
# MAGIC Portfolio STRING,
# MAGIC ST_CD STRING,
# MAGIC FUNDG_CLS_TXT STRING,
# MAGIC MBU_CLS_TXT STRING,
# MAGIC TMPLT_EFCTV_DT DATE,
# MAGIC TMPLT_TRMNTN_DT DATE,
# MAGIC TMPLT_NM STRING,
# MAGIC TMPLT_YEAR_NBR Double,
# MAGIC INCNTV_PKG_TYPE_TXT STRING,
# MAGIC INCNTV_PKG_CAP_AMT Double,
# MAGIC INCNTV_PKG_CLS_TXT STRING,
# MAGIC INCNTV_PKG_NM STRING,
# MAGIC DSBRSMNT_TYPE_TXT STRING,
# MAGIC OPT_ID STRING,
# MAGIC OPT_NM STRING,
# MAGIC HLTH_PGM_BNFT_PKG_EFCTV_DT DATE,
# MAGIC HLTH_PGM_BNFT_PKG_TRMNTN_DT DATE,
# MAGIC BNFT_PKG_EFCTV_DT DATE,
# MAGIC BNFT_PKG_TRMNTN_DT DATE,
# MAGIC EHP_SALES_PKG_NM STRING,
# MAGIC PGM_LVL_IDFCTN_NM STRING,
# MAGIC PGM_RPTG_IND STRING,
# MAGIC HWBS_Product_ID STRING,
# MAGIC HWBS_Product_Name STRING,
# MAGIC HWBS_Reporting_Product_Name STRING,
# MAGIC HWBS_Product_Type STRING,
# MAGIC HWBS_Product_Class STRING,
# MAGIC HWBS_Product_Sub_Class STRING,
# MAGIC HWBS_Product_Business_Unit_Name STRING,
# MAGIC HWBS_Product_Reporting_Indicator STRING,
# MAGIC HWBS_Product_Level_Identification_Name STRING
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.WORK_MBR_HW_TXNMY
# MAGIC SELECT  
# MAGIC HW_KEY ,
# MAGIC PKG_KEY ,
# MAGIC HW_PROD_KEY ,
# MAGIC BUY_UP_PGM_IND ,
# MAGIC PGM_ID ,
# MAGIC RPTG_PGM_NM ,
# MAGIC MRKTG_PROD_NM ,
# MAGIC PGM_TYPE_DESC ,
# MAGIC PGM_CLS_DESC ,
# MAGIC PGM_SUB_CLS_DESC ,
# MAGIC PGM_BU_NM ,
# MAGIC RCRD_STTS_CD ,
# MAGIC PFOL_YEAR_NBR ,
# MAGIC HLTH_PGM_BNFT_PKG_ID ,
# MAGIC BNFT_PKG_ID ,
# MAGIC PKG_TYPE_NM ,
# MAGIC PKG_CLS_NM ,
# MAGIC PFOL_NM ,
# MAGIC ST_CD ,
# MAGIC FUNDG_CLS_TXT ,
# MAGIC MBU_CLS_TXT ,
# MAGIC CAST(TMPLT_EFCTV_DT AS DATE) AS TMPLT_EFCTV_DT,
# MAGIC CAST(TMPLT_TRMNTN_DT AS DATE) AS TMPLT_TRMNTN_DT ,
# MAGIC TMPLT_NM ,
# MAGIC TMPLT_YEAR_NBR ,
# MAGIC INCNTV_PKG_TYPE_TXT ,
# MAGIC INCNTV_PKG_CAP_AMT ,
# MAGIC INCNTV_PKG_CLS_TXT ,
# MAGIC INCNTV_PKG_NM ,
# MAGIC DSBRSMNT_TYPE_TXT ,
# MAGIC OPT_ID ,
# MAGIC OPT_NM ,
# MAGIC CAST(HLTH_PGM_BNFT_PKG_EFCTV_DT AS DATE) AS  HLTH_PGM_BNFT_PKG_EFCTV_DT ,
# MAGIC CAST(HLTH_PGM_BNFT_PKG_TRMNTN_DT AS DATE) AS HLTH_PGM_BNFT_PKG_TRMNTN_DT ,
# MAGIC CAST(BNFT_PKG_EFCTV_DT AS DATE) AS  BNFT_PKG_EFCTV_DT ,
# MAGIC CAST(BNFT_PKG_TRMNTN_DT AS DATE) AS BNFT_PKG_TRMNTN_DT ,
# MAGIC EHP_SALES_PKG_NM ,
# MAGIC PGM_LVL_IDFCTN_NM ,
# MAGIC PGM_RPTG_IND ,
# MAGIC PROD_ID ,
# MAGIC PROD_NM ,
# MAGIC RPTG_PROD_NM ,
# MAGIC PROD_TYPE_DESC ,
# MAGIC PROD_CLS_DESC ,
# MAGIC PROD_SUB_CLS_DESC ,
# MAGIC PROD_BU_NM ,
# MAGIC PROD_RPTG_IND ,
# MAGIC PROD_LVL_IDFCTN_NM
# MAGIC 
# MAGIC FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_HW_PKG_PGM;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Client_HWBS
# MAGIC (
# MAGIC SNAP_YEAR_MNTH_NBR Double,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC --CLNT_GRP_SUBGRP_SOR_CD STRING,
# MAGIC Client_Group_Subgroup_ID STRING,
# MAGIC Client_Group_Subgroup STRING,
# MAGIC EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC Client_Group_ID STRING,
# MAGIC Client_Group STRING,
# MAGIC --ACCT_CNTRL_CLNT_GRP_ID STRING,
# MAGIC --ACCT_CNTRL_CLNT_GRP_NM STRING,
# MAGIC SIC_CD STRING,
# MAGIC SIC STRING,
# MAGIC --SIC_GRP_CD STRING,
# MAGIC SIC_Group STRING
# MAGIC --ELGBL_GRP_SIZE_NBR Double,
# MAGIC --RNWL_MNTH_NBR Double
# MAGIC --UNDRWRTG_STRT_MNTH_NBR Double
# MAGIC --CLNT_GRP_SUBGRP_EFCTV_DT DATE,
# MAGIC --CLNT_GRP_SUBGRP_TRMNTN_DT DATE,
# MAGIC --CLNT_GRP_EFCTV_DT DATE,
# MAGIC --CLNT_GRP_TRMNTN_DT DATE,
# MAGIC --ACCT_CNTRL_CLNT_GRP_SOR_CD STRING,
# MAGIC --ACCT_CNTRL_CLNT_GRP_EFCTV_DT DATE,
# MAGIC --ACCT_CNTRL_CLNT_GRP_TRMNTN_DT DATE
# MAGIC );
# MAGIC 
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Client_HWBS
# MAGIC SELECT
# MAGIC SNAP_YEAR_MNTH_NBR ,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY ,
# MAGIC --CLNT_GRP_SUBGRP_SOR_CD ,
# MAGIC CLNT_GRP_SUBGRP_ID ,
# MAGIC CLNT_GRP_SUBGRP_NM ,
# MAGIC EDM_CLNT_GRP_ACCT_KEY ,
# MAGIC CLNT_GRP_ID ,
# MAGIC CLNT_GRP_NM ,
# MAGIC --ACCT_CNTRL_CLNT_GRP_ID ,
# MAGIC --ACCT_CNTRL_CLNT_GRP_NM ,
# MAGIC SIC_CD ,
# MAGIC SIC_DESC ,
# MAGIC --SIC_GRP_CD ,
# MAGIC SIC_GRP_NM 
# MAGIC --ELGBL_GRP_SIZE_NBR ,
# MAGIC --RNWL_MNTH_NBR 
# MAGIC --UNDRWRTG_STRT_MNTH_NBR 
# MAGIC --CAST(CLNT_GRP_SUBGRP_EFCTV_DT AS DATE) AS CLNT_GRP_SUBGRP_EFCTV_DT,
# MAGIC --CAST(CLNT_GRP_SUBGRP_TRMNTN_DT AS DATE) AS CLNT_GRP_SUBGRP_TRMNTN_DT,
# MAGIC --CAST(CLNT_GRP_EFCTV_DT AS DATE) AS CLNT_GRP_EFCTV_DT,
# MAGIC --CAST(CLNT_GRP_TRMNTN_DT AS DATE) AS CLNT_GRP_TRMNTN_DT,
# MAGIC --ACCT_CNTRL_CLNT_GRP_SOR_CD ,
# MAGIC --CAST(ACCT_CNTRL_CLNT_GRP_EFCTV_DT AS DATE) AS ACCT_CNTRL_CLNT_GRP_EFCTV_DT,
# MAGIC --CAST(ACCT_CNTRL_CLNT_GRP_TRMNTN_DT AS DATE) AS ACCT_CNTRL_CLNT_GRP_TRMNTN_DT
# MAGIC 
# MAGIC FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_CLNT_GRP_SUBGRP;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Client
# MAGIC (
# MAGIC SNAP_YEAR_MNTH_NBR Double,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY Double,
# MAGIC CLNT_GRP_SUBGRP_SOR_CD STRING,
# MAGIC Client_Group_Subgroup_ID STRING,
# MAGIC Client_Group_Subgroup STRING,
# MAGIC EDM_CLNT_GRP_ACCT_KEY Double,
# MAGIC Client_Group_ID STRING,
# MAGIC Client_Group STRING,
# MAGIC ACCT_CNTRL_CLNT_GRP_ID STRING,
# MAGIC ACCT_CNTRL_CLNT_GRP_NM STRING,
# MAGIC SIC_CD STRING,
# MAGIC SIC STRING,
# MAGIC SIC_GRP_CD STRING,
# MAGIC SIC_Group STRING,
# MAGIC ELGBL_GRP_SIZE_NBR Double,
# MAGIC RNWL_MNTH_NBR Double,
# MAGIC UNDRWRTG_STRT_MNTH_NBR Double,
# MAGIC CLNT_GRP_SUBGRP_EFCTV_DT DATE,
# MAGIC CLNT_GRP_SUBGRP_TRMNTN_DT DATE,
# MAGIC CLNT_GRP_EFCTV_DT DATE,
# MAGIC CLNT_GRP_TRMNTN_DT DATE,
# MAGIC ACCT_CNTRL_CLNT_GRP_SOR_CD STRING,
# MAGIC ACCT_CNTRL_CLNT_GRP_EFCTV_DT DATE,
# MAGIC ACCT_CNTRL_CLNT_GRP_TRMNTN_DT DATE
# MAGIC );
# MAGIC 
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Client
# MAGIC SELECT
# MAGIC SNAP_YEAR_MNTH_NBR ,
# MAGIC EDM_CLNT_GRP_SUBGRP_ACCT_KEY ,
# MAGIC CLNT_GRP_SUBGRP_SOR_CD ,
# MAGIC CLNT_GRP_SUBGRP_ID ,
# MAGIC CLNT_GRP_SUBGRP_NM ,
# MAGIC EDM_CLNT_GRP_ACCT_KEY ,
# MAGIC CLNT_GRP_ID ,
# MAGIC CLNT_GRP_NM ,
# MAGIC ACCT_CNTRL_CLNT_GRP_ID ,
# MAGIC ACCT_CNTRL_CLNT_GRP_NM ,
# MAGIC SIC_CD ,
# MAGIC SIC_DESC ,
# MAGIC SIC_GRP_CD ,
# MAGIC SIC_GRP_NM ,
# MAGIC ELGBL_GRP_SIZE_NBR ,
# MAGIC RNWL_MNTH_NBR ,
# MAGIC UNDRWRTG_STRT_MNTH_NBR, 
# MAGIC CAST(CLNT_GRP_SUBGRP_EFCTV_DT AS DATE) AS CLNT_GRP_SUBGRP_EFCTV_DT,
# MAGIC CAST(CLNT_GRP_SUBGRP_TRMNTN_DT AS DATE) AS CLNT_GRP_SUBGRP_TRMNTN_DT,
# MAGIC CAST(CLNT_GRP_EFCTV_DT AS DATE) AS CLNT_GRP_EFCTV_DT,
# MAGIC CAST(CLNT_GRP_TRMNTN_DT AS DATE) AS CLNT_GRP_TRMNTN_DT,
# MAGIC ACCT_CNTRL_CLNT_GRP_SOR_CD ,
# MAGIC CAST(ACCT_CNTRL_CLNT_GRP_EFCTV_DT AS DATE) AS ACCT_CNTRL_CLNT_GRP_EFCTV_DT,
# MAGIC CAST(ACCT_CNTRL_CLNT_GRP_TRMNTN_DT AS DATE) AS ACCT_CNTRL_CLNT_GRP_TRMNTN_DT
# MAGIC 
# MAGIC FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_CLNT_GRP_SUBGRP;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE or REPLACE TABLE GOLD_LAKEHOUSE.dbo.Med_LKUP_PROD_KEY_HWBS
# MAGIC (
# MAGIC PROD_KEY Double,
# MAGIC --PROD_SOR_CD Double,
# MAGIC --MBRSHP_SOR_CD STRING,
# MAGIC --PROD_TYPE_CD STRING,
# MAGIC --CNTRCT_ID STRING,
# MAGIC --HOSP_BCV_ID STRING,
# MAGIC --PHRMCY_BCV_ID STRING,
# MAGIC --PRFSNL_BCV_ID STRING,
# MAGIC --MJR_MDCL_BCV_ID STRING,
# MAGIC BNFT_CVRG_ID STRING,
# MAGIC BNFT_PKG_ID STRING,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC HIOS_PLAN_ID STRING,
# MAGIC PROD_ACCUMN_PRD_CD STRING,
# MAGIC --PROD_EFCTV_DT DATE,
# MAGIC --PROD_TRMNTN_DT DATE,
# MAGIC --PROD_ETL_SQNC_NBR Double,
# MAGIC MBU_CF_CD STRING,
# MAGIC PROD_CF_CD STRING,
# MAGIC --PKG_NBR STRING,
# MAGIC --PROD_ID STRING,
# MAGIC PGM_ID STRING,
# MAGIC --CMS_CNTRCT_NBR STRING,
# MAGIC --CMS_PLAN_BNFT_PKG_ID STRING,
# MAGIC --SRC_MBR_PRFL_CD STRING,
# MAGIC --PRCHSR_ORG_NBR STRING,
# MAGIC --RLTD_PRCHSR_ORG_NBR STRING,
# MAGIC --SRC_ST_AID_PGM_CD STRING,
# MAGIC --MDCD_RISK_PPLTN_CD STRING,
# MAGIC --RTL_GNRC_MNDTRY_IND STRING,
# MAGIC RCRD_STTS_CD STRING,
# MAGIC SNAP_YEAR_MNTH_NBR Double
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Med_LKUP_PROD_KEY_HWBS
# MAGIC SELECT
# MAGIC PROD_KEY ,
# MAGIC --PROD_SOR_CD ,
# MAGIC --MBRSHP_SOR_CD ,
# MAGIC --PROD_TYPE_CD ,
# MAGIC --CNTRCT_ID ,
# MAGIC --HOSP_BCV_ID ,
# MAGIC --PHRMCY_BCV_ID ,
# MAGIC --PRFSNL_BCV_ID ,
# MAGIC --MJR_MDCL_BCV_ID ,
# MAGIC BNFT_CVRG_ID ,
# MAGIC BNFT_PKG_ID ,
# MAGIC HLTH_PGM_BNFT_PKG_ID ,
# MAGIC HIOS_PLAN_ID ,
# MAGIC PROD_ACCUMN_PRD_CD,
# MAGIC --CAST(PROD_EFCTV_DT AS DATE) AS  PROD_EFCTV_DT,
# MAGIC --CAST(PROD_TRMNTN_DT AS DATE) AS  PROD_TRMNTN_DT ,
# MAGIC --PROD_ETL_SQNC_NBR ,
# MAGIC MBU_CF_CD ,
# MAGIC PROD_CF_CD ,
# MAGIC --PKG_NBR ,
# MAGIC --PROD_ID ,
# MAGIC PGM_ID ,
# MAGIC --CMS_CNTRCT_NBR ,
# MAGIC --CMS_PLAN_BNFT_PKG_ID ,
# MAGIC --SRC_MBR_PRFL_CD ,
# MAGIC --PRCHSR_ORG_NBR ,
# MAGIC --RLTD_PRCHSR_ORG_NBR ,
# MAGIC --SRC_ST_AID_PGM_CD ,
# MAGIC --MDCD_RISK_PPLTN_CD ,
# MAGIC --RTL_GNRC_MNDTRY_IND ,
# MAGIC RCRD_STTS_CD ,
# MAGIC SNAP_YEAR_MNTH_NBR
# MAGIC FROM GOLD_LAKEHOUSE.dbo.LKUP_PROD_KEY;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE or REPLACE TABLE GOLD_LAKEHOUSE.dbo.Med_LKUP_PROD_KEY
# MAGIC (
# MAGIC PROD_KEY Double,
# MAGIC PROD_SOR_CD Double,
# MAGIC MBRSHP_SOR_CD STRING,
# MAGIC PROD_TYPE_CD STRING,
# MAGIC CNTRCT_ID STRING,
# MAGIC HOSP_BCV_ID STRING,
# MAGIC PHRMCY_BCV_ID STRING,
# MAGIC PRFSNL_BCV_ID STRING,
# MAGIC MJR_MDCL_BCV_ID STRING,
# MAGIC BNFT_CVRG_ID STRING,
# MAGIC BNFT_PKG_ID STRING,
# MAGIC HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC HIOS_PLAN_ID STRING,
# MAGIC PROD_ACCUMN_PRD_CD STRING,
# MAGIC PROD_EFCTV_DT DATE,
# MAGIC PROD_TRMNTN_DT DATE,
# MAGIC PROD_ETL_SQNC_NBR Double,
# MAGIC MBU_CF_CD STRING,
# MAGIC PROD_CF_CD STRING,
# MAGIC PKG_NBR STRING,
# MAGIC PROD_ID STRING,
# MAGIC PGM_ID STRING,
# MAGIC CMS_CNTRCT_NBR STRING,
# MAGIC CMS_PLAN_BNFT_PKG_ID STRING,
# MAGIC SRC_MBR_PRFL_CD STRING,
# MAGIC PRCHSR_ORG_NBR STRING,
# MAGIC RLTD_PRCHSR_ORG_NBR STRING,
# MAGIC SRC_ST_AID_PGM_CD STRING,
# MAGIC MDCD_RISK_PPLTN_CD STRING,
# MAGIC RTL_GNRC_MNDTRY_IND STRING,
# MAGIC RCRD_STTS_CD STRING,
# MAGIC SNAP_YEAR_MNTH_NBR Double
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Med_LKUP_PROD_KEY
# MAGIC SELECT
# MAGIC PROD_KEY ,
# MAGIC PROD_SOR_CD ,
# MAGIC MBRSHP_SOR_CD ,
# MAGIC PROD_TYPE_CD ,
# MAGIC CNTRCT_ID ,
# MAGIC HOSP_BCV_ID ,
# MAGIC PHRMCY_BCV_ID ,
# MAGIC PRFSNL_BCV_ID ,
# MAGIC MJR_MDCL_BCV_ID ,
# MAGIC BNFT_CVRG_ID ,
# MAGIC BNFT_PKG_ID ,
# MAGIC HLTH_PGM_BNFT_PKG_ID ,
# MAGIC HIOS_PLAN_ID ,
# MAGIC PROD_ACCUMN_PRD_CD,
# MAGIC CAST(PROD_EFCTV_DT AS DATE) AS  PROD_EFCTV_DT,
# MAGIC CAST(PROD_TRMNTN_DT AS DATE) AS  PROD_TRMNTN_DT ,
# MAGIC PROD_ETL_SQNC_NBR ,
# MAGIC MBU_CF_CD ,
# MAGIC PROD_CF_CD ,
# MAGIC PKG_NBR ,
# MAGIC PROD_ID ,
# MAGIC PGM_ID ,
# MAGIC CMS_CNTRCT_NBR ,
# MAGIC CMS_PLAN_BNFT_PKG_ID ,
# MAGIC SRC_MBR_PRFL_CD ,
# MAGIC PRCHSR_ORG_NBR ,
# MAGIC RLTD_PRCHSR_ORG_NBR ,
# MAGIC SRC_ST_AID_PGM_CD ,
# MAGIC MDCD_RISK_PPLTN_CD ,
# MAGIC RTL_GNRC_MNDTRY_IND ,
# MAGIC RCRD_STTS_CD ,
# MAGIC SNAP_YEAR_MNTH_NBR
# MAGIC FROM GOLD_LAKEHOUSE.dbo.LKUP_PROD_KEY;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Medical_Product_HWBS
# MAGIC (
# MAGIC 	--EDL_LOAD_DTM DATE,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	PROD_KEY Double,
# MAGIC 	--PROD_EFCTV_DT DATE,
# MAGIC 	--PROD_TRMNTN_DT DATE,
# MAGIC 	--MRKT_AVLBLTY_EFCTV_DT DATE,
# MAGIC 	--MRKT_AVLBLTY_TRMNTN_DT DATE,
# MAGIC 	PFOL_YEAR_NBR Double,
# MAGIC 	PROD_NM STRING,
# MAGIC 	PGM_NM STRING,
# MAGIC 	PGM_DESC STRING,
# MAGIC 	--PROD_SOR_CD STRING,
# MAGIC 	PROD_SOR_DESC STRING,
# MAGIC 	--PROD_TYPE_CD STRING,
# MAGIC 	--PROD_TYPE_DESC STRING,
# MAGIC 	--PROD_ACCUMN_PRD_CD STRING,
# MAGIC 	--PROD_ACCUMN_PRD_NM STRING,
# MAGIC 	--BNFT_GRP_CD STRING,
# MAGIC 	BNFT_GRP_SHRT_DESC STRING,
# MAGIC 	--BNFT_GRP_LONG_DESC STRING,
# MAGIC 	--BNFT_CLS_CD STRING,
# MAGIC 	BNFT_CLS_SHRT_DESC STRING,
# MAGIC 	--BNFT_CLS_LONG_DESC STRING,
# MAGIC 	--PROD_CD STRING,
# MAGIC 	PROD_SHRT_DESC STRING,
# MAGIC 	--PROD_LONG_DESC STRING,
# MAGIC 	--PROD_SGMNT_CD STRING,
# MAGIC 	--PROD_SGMNT_LONG_DESC STRING,
# MAGIC 	PROD_SGMNT_SHRT_DESC STRING,
# MAGIC 	--SUB_PROD_CD STRING,
# MAGIC 	SUB_PROD_SHRT_DESC STRING,
# MAGIC 	--SUB_PROD_LONG_DESC STRING,
# MAGIC 	--PROD_SUB_SGMNT_CD STRING,
# MAGIC 	PROD_SUB_SGMNT_SHRT_DESC STRING,
# MAGIC 	--PROD_SUB_SGMNT_LONG_DESC STRING,
# MAGIC 	--METL_CD STRING,
# MAGIC 	METL_SHRT_DESC STRING,
# MAGIC 	--METL_LONG_DESC STRING,
# MAGIC 	--DTL_PROD_CD STRING,
# MAGIC 	DTL_PROD_SHRT_DESC STRING,
# MAGIC 	--DTL_PROD_LONG_DESC STRING,
# MAGIC 	--PROD_LINE_CD STRING,
# MAGIC 	PROD_LINE_SHRT_DESC STRING,
# MAGIC 	--PROD_LINE_LONG_DESC STRING,
# MAGIC 	--CERTFN_CD STRING,
# MAGIC 	CERTFN_SHRT_DESC STRING,
# MAGIC 	--CERTFN_LONG_DESC STRING,
# MAGIC 	--HCR_CD STRING,
# MAGIC 	HCR_SHRT_DESC STRING,
# MAGIC 	--HCR_LONG_DESC STRING,
# MAGIC 	--EXCHNG_CLS_CD STRING,
# MAGIC 	EXCHNG_CLS_SHRT_DESC STRING,
# MAGIC 	--EXCHNG_CLS_LONG_DESC STRING,
# MAGIC 	--EXCHNG_TYPE_CD STRING,
# MAGIC 	EXCHNG_TYPE_SHRT_DESC STRING,
# MAGIC 	--EXCHNG_TYPE_LONG_DESC STRING,
# MAGIC 	--CDHP_CLS_CD STRING,
# MAGIC 	CDHP_CLS_SHRT_DESC STRING,
# MAGIC 	--CDHP_CLS_LONG_DESC STRING,
# MAGIC 	--CDHP_SUB_CLS_CD STRING,
# MAGIC 	CDHP_SUB_CLS_SHRT_DESC STRING,
# MAGIC 	--CDHP_SUB_CLS_LONG_DESC STRING,
# MAGIC 	--CDHP_TYPE_CD STRING,
# MAGIC 	CDHP_TYPE_SHRT_DESC STRING,
# MAGIC 	--CDHP_TYPE_LONG_DESC STRING,
# MAGIC 	--MBRSHP_AGRGT_CD STRING,
# MAGIC 	--MBRSHP_AGRGT_NM STRING,
# MAGIC 	--BASE_PROD_KEY Double,
# MAGIC 	BNFT_PKG_TYPE_CD STRING,
# MAGIC 	BNFT_PKG_TYPE_NM STRING,
# MAGIC 	--CNTRCT_PBP_SGMNT_CD STRING,
# MAGIC 	--CNTRCT_PBP_SGMNT_SHRT_DESC STRING,
# MAGIC 	--CNTRCT_PBP_SGMNT_LONG_DESC STRING,
# MAGIC 	--CNTRCT_PBP_CD STRING,
# MAGIC 	--CNTRCT_PBP_SHRT_DESC STRING,
# MAGIC 	--CNTRCT_PBP_LONG_DESC STRING,
# MAGIC 	--PROD_GRP_CD STRING,
# MAGIC 	PROD_GRP_SHRT_DESC STRING,
# MAGIC 	--PROD_GRP_LONG_DESC STRING,
# MAGIC 	--PROD_SUB_GRP_CD STRING,
# MAGIC 	PROD_SUB_GRP_SHRT_DESC STRING,
# MAGIC 	--PROD_SUB_GRP_LONG_DESC STRING,
# MAGIC 	--PROD_CLS_CD STRING,
# MAGIC 	PROD_CLS_SHRT_DESC STRING,
# MAGIC 	--PROD_CLS_LONG_DESC STRING,
# MAGIC 	--PROD_SUB_CLS_CD STRING,
# MAGIC 	PROD_SUB_CLS_SHRT_DESC STRING,
# MAGIC 	--PROD_SUB_CLS_LONG_DESC STRING,
# MAGIC 	--PROV_CLBRTN_PROD_CD STRING,
# MAGIC 	--PROV_CLBRTN_PROD_SHRT_DESC STRING,
# MAGIC 	--PROV_CLBRTN_PROD_LONG_DESC STRING,
# MAGIC 	--DGTL_ENBL_CD STRING,
# MAGIC 	DGTL_ENBL_NM STRING,
# MAGIC 	--HPP_PGM_CD STRING,
# MAGIC 	HPP_PGM_NM STRING,
# MAGIC 	--AHP_PRTNR_CD STRING,
# MAGIC 	--AHP_PRTNR_NM STRING,
# MAGIC 	--AHP_IND STRING,
# MAGIC 	--AHP_FNC_IND STRING,
# MAGIC 	ACA_EXCHNG_NM STRING,
# MAGIC 	MEWA_ACA_EXCHNG_NM STRING,
# MAGIC 	IS_BRNDD_IND STRING,
# MAGIC 	VPC_Enabled_Indicator STRING,
# MAGIC 	DERIVD_DGTL_ENBL_NM STRING,
# MAGIC 	VPC_Type STRING,
# MAGIC 	VPC_Category STRING,
# MAGIC 	VPC_Enabled_Type_Sort STRING
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Medical_Product_HWBS
# MAGIC 
# MAGIC SELECT
# MAGIC     --CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	SNAP_YEAR_MNTH_NBR ,
# MAGIC 	PROD_KEY ,
# MAGIC 	--CAST(PROD_EFCTV_DT AS DATE) AS PROD_EFCTV_DT,
# MAGIC 	--CAST(PROD_TRMNTN_DT AS DATE) AS PROD_TRMNTN_DT, 
# MAGIC 	--CAST(MRKT_AVLBLTY_EFCTV_DT AS DATE) AS MRKT_AVLBLTY_EFCTV_DT,
# MAGIC 	--CAST(MRKT_AVLBLTY_TRMNTN_DT AS DATE) AS MRKT_AVLBLTY_TRMNTN_DT,
# MAGIC 	PFOL_YEAR_NBR ,
# MAGIC 	PROD_NM ,
# MAGIC 	PGM_NM ,
# MAGIC 	PGM_DESC ,
# MAGIC 	--PROD_SOR_CD ,
# MAGIC 	PROD_SOR_DESC ,
# MAGIC 	--PROD_TYPE_CD ,
# MAGIC 	--PROD_TYPE_DESC ,
# MAGIC 	--PROD_ACCUMN_PRD_CD ,
# MAGIC 	--PROD_ACCUMN_PRD_NM ,
# MAGIC 	--BNFT_GRP_CD ,
# MAGIC 	BNFT_GRP_SHRT_DESC ,
# MAGIC 	--BNFT_GRP_LONG_DESC ,
# MAGIC 	--BNFT_CLS_CD ,
# MAGIC 	BNFT_CLS_SHRT_DESC ,
# MAGIC 	--BNFT_CLS_LONG_DESC ,
# MAGIC 	--PROD_CD ,
# MAGIC 	PROD_SHRT_DESC ,
# MAGIC 	--PROD_LONG_DESC ,
# MAGIC 	--PROD_SGMNT_CD ,
# MAGIC 	--PROD_SGMNT_LONG_DESC ,
# MAGIC 	PROD_SGMNT_SHRT_DESC ,
# MAGIC 	--SUB_PROD_CD ,
# MAGIC 	SUB_PROD_SHRT_DESC ,
# MAGIC 	--SUB_PROD_LONG_DESC ,
# MAGIC 	--PROD_SUB_SGMNT_CD ,
# MAGIC 	PROD_SUB_SGMNT_SHRT_DESC ,
# MAGIC 	--PROD_SUB_SGMNT_LONG_DESC ,
# MAGIC 	--METL_CD ,
# MAGIC 	METL_SHRT_DESC ,
# MAGIC 	--METL_LONG_DESC ,
# MAGIC 	--DTL_PROD_CD ,
# MAGIC 	DTL_PROD_SHRT_DESC ,
# MAGIC 	--DTL_PROD_LONG_DESC ,
# MAGIC 	--PROD_LINE_CD ,
# MAGIC 	PROD_LINE_SHRT_DESC ,
# MAGIC 	--PROD_LINE_LONG_DESC ,
# MAGIC 	--CERTFN_CD ,
# MAGIC 	CERTFN_SHRT_DESC ,
# MAGIC 	--CERTFN_LONG_DESC ,
# MAGIC 	--HCR_CD ,
# MAGIC 	HCR_SHRT_DESC ,
# MAGIC 	--HCR_LONG_DESC ,
# MAGIC 	--EXCHNG_CLS_CD ,
# MAGIC 	EXCHNG_CLS_SHRT_DESC ,
# MAGIC 	--EXCHNG_CLS_LONG_DESC ,
# MAGIC 	--EXCHNG_TYPE_CD ,
# MAGIC 	EXCHNG_TYPE_SHRT_DESC ,
# MAGIC 	--EXCHNG_TYPE_LONG_DESC ,
# MAGIC 	--CDHP_CLS_CD ,
# MAGIC 	CDHP_CLS_SHRT_DESC ,
# MAGIC 	--CDHP_CLS_LONG_DESC ,
# MAGIC 	--CDHP_SUB_CLS_CD ,
# MAGIC 	CDHP_SUB_CLS_SHRT_DESC ,
# MAGIC 	--CDHP_SUB_CLS_LONG_DESC ,
# MAGIC 	--CDHP_TYPE_CD ,
# MAGIC 	CDHP_TYPE_SHRT_DESC ,
# MAGIC 	--CDHP_TYPE_LONG_DESC ,
# MAGIC 	--MBRSHP_AGRGT_CD ,
# MAGIC 	--MBRSHP_AGRGT_NM ,
# MAGIC 	--BASE_PROD_KEY ,
# MAGIC 	BNFT_PKG_TYPE_CD ,
# MAGIC 	BNFT_PKG_TYPE_NM ,
# MAGIC 	--CNTRCT_PBP_SGMNT_CD ,
# MAGIC 	--CNTRCT_PBP_SGMNT_SHRT_DESC ,
# MAGIC 	--CNTRCT_PBP_SGMNT_LONG_DESC ,
# MAGIC 	--CNTRCT_PBP_CD ,
# MAGIC 	--CNTRCT_PBP_SHRT_DESC ,
# MAGIC 	--CNTRCT_PBP_LONG_DESC ,
# MAGIC 	--PROD_GRP_CD ,
# MAGIC 	PROD_GRP_SHRT_DESC ,
# MAGIC 	--PROD_GRP_LONG_DESC ,
# MAGIC 	--PROD_SUB_GRP_CD ,
# MAGIC 	PROD_SUB_GRP_SHRT_DESC ,
# MAGIC 	--PROD_SUB_GRP_LONG_DESC ,
# MAGIC 	--PROD_CLS_CD ,
# MAGIC 	PROD_CLS_SHRT_DESC ,
# MAGIC 	--PROD_CLS_LONG_DESC ,
# MAGIC 	--PROD_SUB_CLS_CD ,
# MAGIC 	PROD_SUB_CLS_SHRT_DESC ,
# MAGIC 	--PROD_SUB_CLS_LONG_DESC ,
# MAGIC 	--PROV_CLBRTN_PROD_CD ,
# MAGIC 	--PROV_CLBRTN_PROD_SHRT_DESC ,
# MAGIC 	--PROV_CLBRTN_PROD_LONG_DESC ,
# MAGIC 	--DGTL_ENBL_CD ,
# MAGIC 	DGTL_ENBL_NM ,
# MAGIC 	--HPP_PGM_CD ,
# MAGIC 	HPP_PGM_NM ,
# MAGIC 	--AHP_PRTNR_CD ,
# MAGIC 	--AHP_PRTNR_NM ,
# MAGIC 	--AHP_IND ,
# MAGIC 	--AHP_FNC_IND ,
# MAGIC 	ACA_EXCHNG_NM ,
# MAGIC 	MEWA_ACA_EXCHNG_NM ,
# MAGIC 	IS_BRNDD_IND ,
# MAGIC 	VPC_ENBLD_NM ,
# MAGIC 	DERIVD_DGTL_ENBL_NM ,
# MAGIC 	VPC_TYPE_NM ,
# MAGIC 	VPC_CTGRY_NM ,
# MAGIC 	VPC_ENBLD_TYPE_SORT_IND 
# MAGIC 	
# MAGIC  FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_PROD;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Medical_Product
# MAGIC (
# MAGIC 	--EDL_LOAD_DTM DATE,
# MAGIC 	SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	PROD_KEY Double,
# MAGIC 	PROD_EFCTV_DT DATE,
# MAGIC 	PROD_TRMNTN_DT DATE,
# MAGIC 	MRKT_AVLBLTY_EFCTV_DT DATE,
# MAGIC 	MRKT_AVLBLTY_TRMNTN_DT DATE,
# MAGIC 	PFOL_YEAR_NBR Double,
# MAGIC 	PROD_NM STRING,
# MAGIC 	PGM_NM STRING,
# MAGIC 	PGM_DESC STRING,
# MAGIC 	PROD_SOR_CD STRING,
# MAGIC 	PROD_SOR_DESC STRING,
# MAGIC 	PROD_TYPE_CD STRING,
# MAGIC 	PROD_TYPE_DESC STRING,
# MAGIC 	PROD_ACCUMN_PRD_CD STRING,
# MAGIC 	PROD_ACCUMN_PRD_NM STRING,
# MAGIC 	BNFT_GRP_CD STRING,
# MAGIC 	BNFT_GRP_SHRT_DESC STRING,
# MAGIC 	BNFT_GRP_LONG_DESC STRING,
# MAGIC 	BNFT_CLS_CD STRING,
# MAGIC 	BNFT_CLS_SHRT_DESC STRING,
# MAGIC 	BNFT_CLS_LONG_DESC STRING,
# MAGIC 	PROD_CD STRING,
# MAGIC 	PROD_SHRT_DESC STRING,
# MAGIC 	PROD_LONG_DESC STRING,
# MAGIC 	PROD_SGMNT_CD STRING,
# MAGIC 	PROD_SGMNT_LONG_DESC STRING,
# MAGIC 	PROD_SGMNT_SHRT_DESC STRING,
# MAGIC 	SUB_PROD_CD STRING,
# MAGIC 	SUB_PROD_SHRT_DESC STRING,
# MAGIC 	SUB_PROD_LONG_DESC STRING,
# MAGIC 	PROD_SUB_SGMNT_CD STRING,
# MAGIC 	PROD_SUB_SGMNT_SHRT_DESC STRING,
# MAGIC 	PROD_SUB_SGMNT_LONG_DESC STRING,
# MAGIC 	METL_CD STRING,
# MAGIC 	METL_SHRT_DESC STRING,
# MAGIC 	METL_LONG_DESC STRING,
# MAGIC 	DTL_PROD_CD STRING,
# MAGIC 	DTL_PROD_SHRT_DESC STRING,
# MAGIC 	DTL_PROD_LONG_DESC STRING,
# MAGIC 	PROD_LINE_CD STRING,
# MAGIC 	PROD_LINE_SHRT_DESC STRING,
# MAGIC 	PROD_LINE_LONG_DESC STRING,
# MAGIC 	CERTFN_CD STRING,
# MAGIC 	CERTFN_SHRT_DESC STRING,
# MAGIC 	CERTFN_LONG_DESC STRING,
# MAGIC 	HCR_CD STRING,
# MAGIC 	HCR_SHRT_DESC STRING,
# MAGIC 	HCR_LONG_DESC STRING,
# MAGIC 	EXCHNG_CLS_CD STRING,
# MAGIC 	EXCHNG_CLS_SHRT_DESC STRING,
# MAGIC 	EXCHNG_CLS_LONG_DESC STRING,
# MAGIC 	EXCHNG_TYPE_CD STRING,
# MAGIC 	EXCHNG_TYPE_SHRT_DESC STRING,
# MAGIC 	EXCHNG_TYPE_LONG_DESC STRING,
# MAGIC 	CDHP_CLS_CD STRING,
# MAGIC 	CDHP_CLS_SHRT_DESC STRING,
# MAGIC 	CDHP_CLS_LONG_DESC STRING,
# MAGIC 	CDHP_SUB_CLS_CD STRING,
# MAGIC 	CDHP_SUB_CLS_SHRT_DESC STRING,
# MAGIC 	CDHP_SUB_CLS_LONG_DESC STRING,
# MAGIC 	CDHP_TYPE_CD STRING,
# MAGIC 	CDHP_TYPE_SHRT_DESC STRING,
# MAGIC 	CDHP_TYPE_LONG_DESC STRING,
# MAGIC 	MBRSHP_AGRGT_CD STRING,
# MAGIC 	MBRSHP_AGRGT_NM STRING,
# MAGIC 	BASE_PROD_KEY Double,
# MAGIC 	BNFT_PKG_TYPE_CD STRING,
# MAGIC 	BNFT_PKG_TYPE_NM STRING,
# MAGIC 	CNTRCT_PBP_SGMNT_CD STRING,
# MAGIC 	CNTRCT_PBP_SGMNT_SHRT_DESC STRING,
# MAGIC 	CNTRCT_PBP_SGMNT_LONG_DESC STRING,
# MAGIC 	CNTRCT_PBP_CD STRING,
# MAGIC 	CNTRCT_PBP_SHRT_DESC STRING,
# MAGIC 	CNTRCT_PBP_LONG_DESC STRING,
# MAGIC 	PROD_GRP_CD STRING,
# MAGIC 	PROD_GRP_SHRT_DESC STRING,
# MAGIC     PROD_GRP_LONG_DESC STRING,
# MAGIC 	PROD_SUB_GRP_CD STRING,
# MAGIC 	PROD_SUB_GRP_SHRT_DESC STRING,
# MAGIC 	PROD_SUB_GRP_LONG_DESC STRING,
# MAGIC 	PROD_CLS_CD STRING,
# MAGIC 	PROD_CLS_SHRT_DESC STRING,
# MAGIC 	PROD_CLS_LONG_DESC STRING,
# MAGIC 	PROD_SUB_CLS_CD STRING,
# MAGIC 	PROD_SUB_CLS_SHRT_DESC STRING,
# MAGIC 	PROD_SUB_CLS_LONG_DESC STRING,
# MAGIC 	PROV_CLBRTN_PROD_CD STRING,
# MAGIC 	PROV_CLBRTN_PROD_SHRT_DESC STRING,
# MAGIC 	PROV_CLBRTN_PROD_LONG_DESC STRING,
# MAGIC 	DGTL_ENBL_CD STRING,
# MAGIC 	DGTL_ENBL_NM STRING,
# MAGIC 	HPP_PGM_CD STRING,
# MAGIC 	HPP_PGM_NM STRING,
# MAGIC 	AHP_PRTNR_CD STRING,
# MAGIC 	AHP_PRTNR_NM STRING,
# MAGIC 	AHP_IND STRING,
# MAGIC 	AHP_FNC_IND STRING,
# MAGIC 	ACA_EXCHNG_NM STRING,
# MAGIC 	MEWA_ACA_EXCHNG_NM STRING,
# MAGIC 	IS_BRNDD_IND STRING,
# MAGIC 	VPC_Enabled_Indicator STRING,
# MAGIC 	DERIVD_DGTL_ENBL_NM STRING,
# MAGIC 	VPC_Type STRING,
# MAGIC 	VPC_Category STRING,
# MAGIC 	VPC_Enabled_Type_Sort STRING
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Medical_Product
# MAGIC 
# MAGIC SELECT
# MAGIC     --CAST(EDL_LOAD_DTM AS DATE) AS EDL_LOAD_DTM,
# MAGIC 	SNAP_YEAR_MNTH_NBR ,
# MAGIC 	PROD_KEY ,
# MAGIC 	CAST(PROD_EFCTV_DT AS DATE) AS PROD_EFCTV_DT,
# MAGIC 	CAST(PROD_TRMNTN_DT AS DATE) AS PROD_TRMNTN_DT, 
# MAGIC 	CAST(MRKT_AVLBLTY_EFCTV_DT AS DATE) AS MRKT_AVLBLTY_EFCTV_DT,
# MAGIC 	CAST(MRKT_AVLBLTY_TRMNTN_DT AS DATE) AS MRKT_AVLBLTY_TRMNTN_DT,
# MAGIC 	PFOL_YEAR_NBR ,
# MAGIC 	PROD_NM ,
# MAGIC 	PGM_NM ,
# MAGIC 	PGM_DESC ,
# MAGIC    PROD_SOR_CD ,
# MAGIC 	PROD_SOR_DESC ,
# MAGIC 	PROD_TYPE_CD ,
# MAGIC 	PROD_TYPE_DESC ,
# MAGIC 	PROD_ACCUMN_PRD_CD ,
# MAGIC 	PROD_ACCUMN_PRD_NM ,
# MAGIC 	BNFT_GRP_CD ,
# MAGIC 	BNFT_GRP_SHRT_DESC ,
# MAGIC 	BNFT_GRP_LONG_DESC ,
# MAGIC 	BNFT_CLS_CD ,
# MAGIC 	BNFT_CLS_SHRT_DESC ,
# MAGIC 	BNFT_CLS_LONG_DESC ,
# MAGIC 	PROD_CD ,
# MAGIC 	PROD_SHRT_DESC ,
# MAGIC 	PROD_LONG_DESC ,
# MAGIC 	PROD_SGMNT_CD ,
# MAGIC 	PROD_SGMNT_LONG_DESC ,
# MAGIC 	PROD_SGMNT_SHRT_DESC ,
# MAGIC 	SUB_PROD_CD ,
# MAGIC 	SUB_PROD_SHRT_DESC ,
# MAGIC 	SUB_PROD_LONG_DESC ,
# MAGIC 	PROD_SUB_SGMNT_CD ,
# MAGIC 	PROD_SUB_SGMNT_SHRT_DESC ,
# MAGIC 	PROD_SUB_SGMNT_LONG_DESC ,
# MAGIC 	METL_CD ,
# MAGIC 	METL_SHRT_DESC ,
# MAGIC 	METL_LONG_DESC ,
# MAGIC 	DTL_PROD_CD ,
# MAGIC 	DTL_PROD_SHRT_DESC ,
# MAGIC 	DTL_PROD_LONG_DESC ,
# MAGIC 	PROD_LINE_CD ,
# MAGIC 	PROD_LINE_SHRT_DESC ,
# MAGIC 	PROD_LINE_LONG_DESC ,
# MAGIC 	CERTFN_CD ,
# MAGIC 	CERTFN_SHRT_DESC ,
# MAGIC 	CERTFN_LONG_DESC ,
# MAGIC 	HCR_CD ,
# MAGIC 	HCR_SHRT_DESC ,
# MAGIC 	HCR_LONG_DESC ,
# MAGIC 	EXCHNG_CLS_CD ,
# MAGIC 	EXCHNG_CLS_SHRT_DESC ,
# MAGIC 	EXCHNG_CLS_LONG_DESC ,
# MAGIC 	EXCHNG_TYPE_CD ,
# MAGIC 	EXCHNG_TYPE_SHRT_DESC ,
# MAGIC 	EXCHNG_TYPE_LONG_DESC ,
# MAGIC 	CDHP_CLS_CD ,
# MAGIC 	CDHP_CLS_SHRT_DESC ,
# MAGIC 	CDHP_CLS_LONG_DESC ,
# MAGIC 	CDHP_SUB_CLS_CD ,
# MAGIC 	CDHP_SUB_CLS_SHRT_DESC ,
# MAGIC 	CDHP_SUB_CLS_LONG_DESC ,
# MAGIC 	CDHP_TYPE_CD ,
# MAGIC 	CDHP_TYPE_SHRT_DESC ,
# MAGIC 	CDHP_TYPE_LONG_DESC ,
# MAGIC 	MBRSHP_AGRGT_CD ,
# MAGIC 	MBRSHP_AGRGT_NM ,
# MAGIC 	BASE_PROD_KEY ,
# MAGIC 	BNFT_PKG_TYPE_CD ,
# MAGIC 	BNFT_PKG_TYPE_NM ,
# MAGIC 	CNTRCT_PBP_SGMNT_CD ,
# MAGIC 	CNTRCT_PBP_SGMNT_SHRT_DESC ,
# MAGIC 	CNTRCT_PBP_SGMNT_LONG_DESC ,
# MAGIC 	CNTRCT_PBP_CD ,
# MAGIC 	CNTRCT_PBP_SHRT_DESC ,
# MAGIC 	CNTRCT_PBP_LONG_DESC ,
# MAGIC 	PROD_GRP_CD ,
# MAGIC 	PROD_GRP_SHRT_DESC ,
# MAGIC 	PROD_GRP_LONG_DESC ,
# MAGIC 	PROD_SUB_GRP_CD ,
# MAGIC 	PROD_SUB_GRP_SHRT_DESC ,
# MAGIC 	PROD_SUB_GRP_LONG_DESC ,
# MAGIC 	PROD_CLS_CD ,
# MAGIC 	PROD_CLS_SHRT_DESC ,
# MAGIC 	PROD_CLS_LONG_DESC ,
# MAGIC 	PROD_SUB_CLS_CD ,
# MAGIC 	PROD_SUB_CLS_SHRT_DESC ,
# MAGIC 	PROD_SUB_CLS_LONG_DESC ,
# MAGIC 	PROV_CLBRTN_PROD_CD ,
# MAGIC 	PROV_CLBRTN_PROD_SHRT_DESC ,
# MAGIC 	PROV_CLBRTN_PROD_LONG_DESC ,
# MAGIC 	DGTL_ENBL_CD ,
# MAGIC 	DGTL_ENBL_NM ,
# MAGIC 	HPP_PGM_CD ,
# MAGIC 	HPP_PGM_NM ,
# MAGIC 	AHP_PRTNR_CD ,
# MAGIC 	AHP_PRTNR_NM ,
# MAGIC 	AHP_IND ,
# MAGIC 	AHP_FNC_IND ,
# MAGIC 	ACA_EXCHNG_NM ,
# MAGIC 	MEWA_ACA_EXCHNG_NM ,
# MAGIC 	IS_BRNDD_IND ,
# MAGIC 	VPC_ENBLD_NM ,
# MAGIC 	DERIVD_DGTL_ENBL_NM ,
# MAGIC 	VPC_TYPE_NM ,
# MAGIC 	VPC_CTGRY_NM ,
# MAGIC 	VPC_ENBLD_TYPE_SORT_IND 
# MAGIC 	
# MAGIC  FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_PROD;


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.SFACT_PROD_MDCL_ADDNL_HWBS
# MAGIC (
# MAGIC     SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	PROD_KEY Double,
# MAGIC 	--BNFT_PKG_KEY Double,
# MAGIC 	--INN_ENTRPR_PLAN_ID STRING,
# MAGIC 	--OON_ENTRPR_PLAN_ID STRING,
# MAGIC 	--LGL_ENTY_KEY Double,
# MAGIC 	NON_NRW_NTWK_KEY Double,
# MAGIC 	--NRW_NTWK_1_KEY Double,
# MAGIC 	--NRW_NTWK_2_KEY Double,
# MAGIC 	--NRW_NTWK_3_KEY Double,
# MAGIC 	OOA_NTWK_KEY Double,
# MAGIC 	--PLAN_KEY Double,
# MAGIC 	--INN_STRCTR_PLAN_KEY Double,
# MAGIC 	--OON_STRCTR_PLAN_KEY Double,
# MAGIC 	--PFOL_KEY Double,
# MAGIC 	--PFOL_BRNDNG_KEY Double,
# MAGIC 	PROD_ID STRING,
# MAGIC 	--PROD_PFOL_KEY Double,
# MAGIC 	PROD_FMLY_KEY Double,
# MAGIC 	--PRVT_EXCHNG_KEY Double,
# MAGIC 	--ALT_PROD_1_ID STRING,
# MAGIC 	--ALT_PROD_2_ID STRING,
# MAGIC 	--ALT_PROD_3_ID STRING,
# MAGIC 	--ALT_PROD_4_ID STRING,
# MAGIC 	--BNFT_KEY_ID STRING,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID STRING
# MAGIC 	--DNTL_EMBDD_PLAN_ID STRING,
# MAGIC 	--VSN_EMBDD_PLAN_ID STRING,
# MAGIC 	--LGCY_PROD_ID STRING
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.SFACT_PROD_MDCL_ADDNL_HWBS
# MAGIC 
# MAGIC SELECT
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC 	PROD_KEY,
# MAGIC 	--BNFT_PKG_KEY,
# MAGIC 	--INN_ENTRPR_PLAN_ID,
# MAGIC 	--OON_ENTRPR_PLAN_ID,
# MAGIC 	--LGL_ENTY_KEY,
# MAGIC 	NON_NRW_NTWK_KEY,
# MAGIC 	--NRW_NTWK_1_KEY,
# MAGIC 	--NRW_NTWK_2_KEY,
# MAGIC 	--NRW_NTWK_3_KEY,
# MAGIC 	OOA_NTWK_KEY,
# MAGIC 	--PLAN_KEY,
# MAGIC 	--INN_STRCTR_PLAN_KEY,
# MAGIC 	--OON_STRCTR_PLAN_KEY,
# MAGIC 	--PFOL_KEY,
# MAGIC 	--PFOL_BRNDNG_KEY,
# MAGIC 	PROD_ID,
# MAGIC 	--PROD_PFOL_KEY,
# MAGIC 	PROD_FMLY_KEY,
# MAGIC 	--PRVT_EXCHNG_KEY,
# MAGIC 	--ALT_PROD_1_ID,
# MAGIC 	--ALT_PROD_2_ID,
# MAGIC 	--ALT_PROD_3_ID,
# MAGIC 	--ALT_PROD_4_ID,
# MAGIC 	--BNFT_KEY_ID,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID
# MAGIC 	--DNTL_EMBDD_PLAN_ID,
# MAGIC 	--VSN_EMBDD_PLAN_ID,
# MAGIC 	--LGCY_PROD_ID
# MAGIC  
# MAGIC  FROM GOLD_LAKEHOUSE.dbo.WORK_SFACT_PROD_MDCL_ADDNL_PA_CUBE;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.SFACT_PROD_MDCL_ADDNL
# MAGIC (
# MAGIC     SNAP_YEAR_MNTH_NBR Double,
# MAGIC 	PROD_KEY Double,
# MAGIC 	BNFT_PKG_KEY Double,
# MAGIC 	INN_ENTRPR_PLAN_ID STRING,
# MAGIC 	OON_ENTRPR_PLAN_ID STRING,
# MAGIC 	LGL_ENTY_KEY Double,
# MAGIC 	NON_NRW_NTWK_KEY Double,
# MAGIC 	NRW_NTWK_1_KEY Double,
# MAGIC 	NRW_NTWK_2_KEY Double,
# MAGIC 	NRW_NTWK_3_KEY Double,
# MAGIC 	OOA_NTWK_KEY Double,
# MAGIC 	PLAN_KEY Double,
# MAGIC 	INN_STRCTR_PLAN_KEY Double,
# MAGIC 	OON_STRCTR_PLAN_KEY Double,
# MAGIC 	PFOL_KEY Double,
# MAGIC 	PFOL_BRNDNG_KEY Double,
# MAGIC 	PROD_ID STRING,
# MAGIC 	PROD_PFOL_KEY Double,
# MAGIC 	PROD_FMLY_KEY Double,
# MAGIC 	PRVT_EXCHNG_KEY Double,
# MAGIC 	ALT_PROD_1_ID STRING,
# MAGIC 	ALT_PROD_2_ID STRING,
# MAGIC 	ALT_PROD_3_ID STRING,
# MAGIC 	ALT_PROD_4_ID STRING,
# MAGIC 	BNFT_KEY_ID STRING,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID STRING,
# MAGIC 	DNTL_EMBDD_PLAN_ID STRING,
# MAGIC 	VSN_EMBDD_PLAN_ID STRING,
# MAGIC 	LGCY_PROD_ID STRING
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.SFACT_PROD_MDCL_ADDNL
# MAGIC 
# MAGIC SELECT
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC 	PROD_KEY,
# MAGIC 	BNFT_PKG_KEY,
# MAGIC 	INN_ENTRPR_PLAN_ID,
# MAGIC 	OON_ENTRPR_PLAN_ID,
# MAGIC 	LGL_ENTY_KEY,
# MAGIC 	NON_NRW_NTWK_KEY,
# MAGIC 	NRW_NTWK_1_KEY,
# MAGIC 	NRW_NTWK_2_KEY,
# MAGIC 	NRW_NTWK_3_KEY,
# MAGIC 	OOA_NTWK_KEY,
# MAGIC 	PLAN_KEY,
# MAGIC 	INN_STRCTR_PLAN_KEY,
# MAGIC 	OON_STRCTR_PLAN_KEY,
# MAGIC 	PFOL_KEY,
# MAGIC 	PFOL_BRNDNG_KEY,
# MAGIC 	PROD_ID,
# MAGIC 	PROD_PFOL_KEY,
# MAGIC 	PROD_FMLY_KEY,
# MAGIC 	PRVT_EXCHNG_KEY,
# MAGIC 	ALT_PROD_1_ID,
# MAGIC 	ALT_PROD_2_ID,
# MAGIC 	ALT_PROD_3_ID,
# MAGIC 	ALT_PROD_4_ID,
# MAGIC 	BNFT_KEY_ID,
# MAGIC 	HLTH_PGM_BNFT_PKG_ID,
# MAGIC 	DNTL_EMBDD_PLAN_ID,
# MAGIC 	VSN_EMBDD_PLAN_ID,
# MAGIC 	LGCY_PROD_ID
# MAGIC  
# MAGIC  FROM GOLD_LAKEHOUSE.dbo.WORK_SFACT_PROD_MDCL_ADDNL_PA_CUBE;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE_ACTVTY_HWBS
# MAGIC (
# MAGIC 	 
# MAGIC 	RWRD_TYPE_KEY DOUBLE,
# MAGIC 	RWRD_TYPE_CD STRING,
# MAGIC 	RWRD_TYPE_DESC STRING,
# MAGIC 	ACCT_CTGRY_CD STRING,
# MAGIC 	ACTVTY_SRC_NM STRING,
# MAGIC 	ACTVTY_NM STRING,
# MAGIC 	ACTVTY_VNDR_NM STRING,
# MAGIC 	MLSTN_NM STRING,
# MAGIC 	RWRD_CTGRY_NM STRING
# MAGIC 
# MAGIC 	);
# MAGIC 	
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE_ACTVTY_HWBS
# MAGIC SELECT  
# MAGIC 	RWRD_TYPE_KEY ,
# MAGIC 	RWRD_TYPE_CD ,
# MAGIC 	RWRD_TYPE_DESC ,
# MAGIC 	ACCT_CTGRY_CD ,
# MAGIC 	ACTVTY_SRC_NM ,
# MAGIC 	ACTVTY_NM ,
# MAGIC 	ACTVTY_VNDR_NM ,
# MAGIC 	MLSTN_NM ,
# MAGIC 	RWRD_CTGRY_NM 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE
# MAGIC 
# MAGIC WHERE RWRD_CTGRY_NM  = 'ACTVTY';


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Incurred_Month_HWBS
# MAGIC (
# MAGIC     
# MAGIC     DT DATE,
# MAGIC     --BUS_DAY_OF_MNTH_NBR Double,
# MAGIC     --CY_AND_WEEK_NBR Double,
# MAGIC     --DT_NBR Double,
# MAGIC     --DAY_OF_MNTH_NBR Double,
# MAGIC     --DAY_OF_WEEK_NM STRING,
# MAGIC     --DAY_OF_WEEK_NBR Double,
# MAGIC     --DAY_OF_WEEK_SHRT_NM STRING,
# MAGIC     --DAY_TYPE_CD STRING,
# MAGIC     --FED_HOLDY_IND STRING,
# MAGIC     --HALF_YEAR_CD STRING,
# MAGIC     --HALF_YEAR_NM STRING,
# MAGIC     --HALF_YEAR_NBR Double,
# MAGIC     --HOLDY_CD STRING,
# MAGIC     --JULIAN_DT_OF_YEAR_NBR Double,
# MAGIC     --MNTH_OF_YEAR_NM STRING,
# MAGIC     --MNTH_OF_YEAR_NBR Double,
# MAGIC     MNTH_OF_YEAR_SHRT_NM STRING,
# MAGIC     --QTR_OF_YEAR_NBR Double,
# MAGIC     --WEEK_OF_YEAR_NBR Double,
# MAGIC     --YEAR_AND_HALF_YEAR_NBR Double,
# MAGIC     --YEAR_AND_QTR_NBR Double,
# MAGIC       Incurred_Year_Month_Nbr Double,
# MAGIC     YEAR_NBR Double,
# MAGIC     --DAY_TYPE_CD_NM STRING,
# MAGIC     --YEAR_AND_HALF_YEAR_NM STRING,
# MAGIC     --YEAR_AND_MNTH_NM STRING,
# MAGIC     --YEAR_AND_QTR_NM STRING,
# MAGIC     Incurred_Month_Begin_Dt DATE,
# MAGIC     Incurred_Month_EndDt DATE,
# MAGIC     DefaultYearMonth STRING,
# MAGIC     INCRD_MNTH_YEAR_DASHBAORD STRING,
# MAGIC     MONTH_DIFFERENCE INTEGER,
# MAGIC     YEAR_MONTH_SORT INTEGER
# MAGIC 
# MAGIC    
# MAGIC    
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Incurred_Month_HWBS
# MAGIC 
# MAGIC SELECT 
# MAGIC    
# MAGIC    CAST(DT AS DATE) AS DT,
# MAGIC     --BUS_DAY_OF_MNTH_NBR,
# MAGIC     --CY_AND_WEEK_NB--R,
# MAGIC     --DT_NBR,
# MAGIC     --DAY_OF_MNTH_NBR,
# MAGIC     --DAY_OF_WEEK_NM,
# MAGIC     --DAY_OF_WEEK_NBR,
# MAGIC     --DAY_OF_WEEK_SHRT_NM,
# MAGIC     --DAY_TYPE_CD,
# MAGIC     --FED_HOLDY_IND,
# MAGIC     --HALF_YEAR_CD,
# MAGIC     --HALF_YEAR_NM,
# MAGIC     --HALF_YEAR_NBR,
# MAGIC     --HOLDY_CD,
# MAGIC     --JULIAN_DT_OF_YEAR_NBR,
# MAGIC     --MNTH_OF_YEAR_NM,
# MAGIC     --MNTH_OF_YEAR_NBR,
# MAGIC     MNTH_OF_YEAR_SHRT_NM,
# MAGIC     --QTR_OF_YEAR_NBR,
# MAGIC     --WEEK_OF_YEAR_NBR,
# MAGIC     --YEAR_AND_HALF_YEAR_NBR,
# MAGIC     --YEAR_AND_QTR_NBR,
# MAGIC     YEAR_MNTH_NBR,
# MAGIC    YEAR_NBR,
# MAGIC    -- DAY_TYPE_CD_NM,
# MAGIC     --YEAR_AND_HALF_YEAR_NM,
# MAGIC     --YEAR_AND_MNTH_NM,
# MAGIC     --YEAR_AND_QTR_NM,
# MAGIC     CAST(MNTH_BGN_DT AS DATE) AS MNTH_BGN_DT,
# MAGIC     CAST(MNTH_END_DT AS DATE) AS MNTH_END_DT,
# MAGIC     DFLT_YEAR_MNTH_TXT,
# MAGIC    --(SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1 WHERE YEAR_MNTH_NBR < (SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1) ) AS LATEST_INCRD_MNTH,
# MAGIC    --CASE 
# MAGIC     --WHEN YEAR_MNTH_NBR = (SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1 WHERE YEAR_MNTH_NBR < (SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1)) THEN 'Current'
# MAGIC     --WHEN YEAR_MNTH_NBR > (SELECT MAX(YEAR_MNTH_NBR)FROM HWBS_LH.DIM_PRDA_DT_1 WHERE YEAR_MNTH_NBR < (SELECT MAX(YEAR_MNTH_NBR) FROM 
# MAGIC     --HWBS_LH.DIM_PRDA_DT_1)) THEN 'Current + 1 Month (Advanced)'
# MAGIC     --ELSE 'Previous'
# MAGIC     --END AS LATEST_INCRD_MNTH_IND --
# MAGIC 
# MAGIC         CONCAT (
# MAGIC       MNTH_OF_YEAR_SHRT_NM, "'",CAST(CAST(YEAR_NBR AS INT)AS STRING)
# MAGIC     )AS INCRD_MNTH_YEAR_DASHBAORD,
# MAGIC 
# MAGIC   DATEDIFF(
# MAGIC     MONTH,
# MAGIC     TO_DATE(MNTH_BGN_DT),
# MAGIC     MAX(TO_DATE(MNTH_BGN_DT)) OVER ()
# MAGIC   ) AS MONTH_DIFFERENCE,
# MAGIC   (YEAR_NBR* 100 + MNTH_OF_YEAR_NBR) as YEAR_MONTH_SORT
# MAGIC 
# MAGIC     
# MAGIC 
# MAGIC    FROM  GOLD_LAKEHOUSE.dbo.DIM_PRDA_DT;
# MAGIC 
# MAGIC 
# MAGIC    


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE_DSBRSMNT_HWBS
# MAGIC (
# MAGIC 	 
# MAGIC 	RWRD_TYPE_KEY DOUBLE,
# MAGIC 	RWRD_TYPE_CD STRING,
# MAGIC 	RWRD_TYPE_DESC STRING,
# MAGIC 	ACCT_CTGRY_CD STRING,
# MAGIC 	ACTVTY_SRC_NM STRING,
# MAGIC 	ACTVTY_NM STRING,
# MAGIC 	ACTVTY_VNDR_NM STRING,
# MAGIC 	MLSTN_NM STRING,
# MAGIC 	RWRD_CTGRY_NM STRING
# MAGIC 
# MAGIC 	);
# MAGIC 	
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE_DSBRSMNT_HWBS
# MAGIC SELECT  
# MAGIC 	RWRD_TYPE_KEY ,
# MAGIC 	RWRD_TYPE_CD ,
# MAGIC 	RWRD_TYPE_DESC ,
# MAGIC 	ACCT_CTGRY_CD ,
# MAGIC 	ACTVTY_SRC_NM ,
# MAGIC 	ACTVTY_NM ,
# MAGIC 	ACTVTY_VNDR_NM ,
# MAGIC 	MLSTN_NM ,
# MAGIC 	RWRD_CTGRY_NM 
# MAGIC 
# MAGIC 	FROM GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE
# MAGIC 
# MAGIC WHERE RWRD_CTGRY_NM  = 'DSBRSMNT';


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Group_MBR_Range(
# MAGIC     
# MAGIC     GRP_MBR_SIZE_KEY DECIMAL (18,6),
# MAGIC     GRP_MBR_SIZE_NBR DECIMAL(18,6),
# MAGIC     MDCL_GRP_MBR_SIZE_NBR_Range STRING
# MAGIC     
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Group_MBR_Range
# MAGIC SELECT 
# MAGIC     GRP_MBR_SIZE_KEY,
# MAGIC     GRP_MBR_SIZE_NBR,
# MAGIC     SORT_GRP_MBR_SIZE_RNG_TXT
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_GRP_MBR_SIZE;      


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Group_Derived_MBR_Range
# MAGIC (
# MAGIC     
# MAGIC     GRP_MBR_RNG_KEY DECIMAL (18,6),
# MAGIC     GRP_MBR_SIZE_NBR DECIMAL(18,6),
# MAGIC     Group_Size_Range STRING
# MAGIC     
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Group_Derived_MBR_Range
# MAGIC SELECT 
# MAGIC     GRP_MBR_RNG_KEY,
# MAGIC     GRP_MBR_SIZE_NBR,
# MAGIC     DERIVD_SORT_GRP_MBR_SIZE_RNG_TXT
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_GRP_MBR_RNG; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Group_Contract_Range
# MAGIC 
# MAGIC (
# MAGIC     --KF_TMS TIMESTAMP,
# MAGIC     GRP_CNTRCT_SIZE_KEY DECIMAL (18,6),
# MAGIC     GRP_CNTRCT_SIZE_NBR DECIMAL(18,6),
# MAGIC     MDCL_GRP_CNTRCT_SIZE_NBR_Range STRING
# MAGIC     
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Group_Contract_Range
# MAGIC SELECT 
# MAGIC    -- KF_TMS, 
# MAGIC     GRP_CNTRCT_SIZE_KEY ,
# MAGIC     GRP_CNTRCT_SIZE_NBR,
# MAGIC     SORT_GRP_CNTRCT_SIZE_RNG_TXT
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_GRP_CNTRCT_SIZE; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Standard_Age
# MAGIC (
# MAGIC     
# MAGIC --EDL_LOAD_DTM	datetime2
# MAGIC --EDL_RUN_ID	STRING
# MAGIC --EDL_SOR_CD	STRING
# MAGIC KF_TMS	TIMESTAMP,
# MAGIC --EDL_SCRTY_LVL_CD	STRING
# MAGIC --EDL_LOB_CD	STRING
# MAGIC --EDL_EXTRNL_LOAD_CD	STRING
# MAGIC --EDL_CREAT_DTM	datetime2
# MAGIC --EDL_INCRMNTL_LOAD_DTM	datetime2
# MAGIC STNDRD_AGE_MNTH_KEY	DECIMAL (18,6),
# MAGIC --SNAP_YEAR_MNTH_NBR	DECIMAL (18,6),
# MAGIC AGE_MNTH_CD	STRING,
# MAGIC Age_Month_Nm	STRING,
# MAGIC Member_Age_Month	DECIMAL (18,6),
# MAGIC AGE_YEAR_CD	STRING,
# MAGIC Age_Year_Nm	STRING,
# MAGIC Member_Age_Year	DECIMAL (18,6),
# MAGIC AGE_BNCHMRK_RNG_CD	STRING,
# MAGIC Member_Age_Benchmark	STRING,
# MAGIC AGE_STNDRD_RNG_MSTR_CD	STRING,
# MAGIC Member_Age 	STRING,
# MAGIC AGE_CNDTN_RNG_CD	STRING,
# MAGIC Member_Age_Condition	STRING,
# MAGIC AGE_TRND_RNG_CD	STRING,
# MAGIC Member_Age_Trend	STRING,
# MAGIC OU_21_YEAR_CD	STRING,
# MAGIC Member_Over_Under_21_Years STRING,
# MAGIC OU_26_YEAR_CD	STRING,
# MAGIC Member_Over_Under_26_Years	STRING,
# MAGIC OU_65_YEAR_CD	STRING,
# MAGIC Member_Over_Under_65_Years	STRING,
# MAGIC MBR_AGE_RNG_NBR	DECIMAL (18,6),
# MAGIC MBR_AGE_SORT_NBR	DECIMAL (18,6)
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Standard_Age
# MAGIC 
# MAGIC SELECT 
# MAGIC --EDL_LOAD_DTM,
# MAGIC --EDL_RUN_ID,
# MAGIC --EDL_SOR_CD,
# MAGIC KF_TMS,
# MAGIC --EDL_SCRTY_LVL_CD,
# MAGIC --EDL_LOB_CD,
# MAGIC --EDL_EXTRNL_LOAD_CD,
# MAGIC --EDL_CREAT_DTM,
# MAGIC --EDL_INCRMNTL_LOAD_DTM,
# MAGIC STNDRD_AGE_MNTH_KEY,
# MAGIC --SNAP_YEAR_MNTH_NBR,
# MAGIC AGE_MNTH_CD,
# MAGIC AGE_MNTH_NM,
# MAGIC AGE_MNTH_NBR,
# MAGIC AGE_YEAR_CD,
# MAGIC AGE_YEAR_NM,
# MAGIC AGE_YEAR_NBR,
# MAGIC AGE_BNCHMRK_RNG_CD,
# MAGIC AGE_BNCHMRK_RNG_NM,
# MAGIC AGE_STNDRD_RNG_MSTR_CD,
# MAGIC AGE_STNDRD_RNG_MSTR_NM,
# MAGIC AGE_CNDTN_RNG_CD,
# MAGIC AGE_CNDTN_RNG_NM,
# MAGIC AGE_TRND_RNG_CD,
# MAGIC AGE_TRND_RNG_NM,
# MAGIC OU_21_YEAR_CD,
# MAGIC OU_21_YEAR_NM,
# MAGIC OU_26_YEAR_CD,
# MAGIC OU_26_YEAR_NM,
# MAGIC OU_65_YEAR_CD,
# MAGIC OU_65_YEAR_NM,
# MAGIC MBR_AGE_RNG_NBR,
# MAGIC MBR_AGE_SORT_NBR
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_STNDRD_AGE_MNTH; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Incurred_Month
# MAGIC (
# MAGIC     
# MAGIC     DT DATE,
# MAGIC     Incurred_Business_Day_of_Month_Nbr Double,
# MAGIC     Incurred_Calendar_Year_and_Week_Nbr Double,
# MAGIC     Incurred_Date_Nbr Double,
# MAGIC     Incurred_Day_of_Month_Nbr Double,
# MAGIC     Incurred_Day_of_Week_Nm STRING,
# MAGIC     Incurred_Day_of_Week_Nbr Double,
# MAGIC     Incurred_Day_of_Week_Short_Nm STRING,
# MAGIC     DAY_TYPE_CD STRING,
# MAGIC     Incurred_Federal_Holiday_Ind STRING,
# MAGIC     HALF_YEAR_CD STRING,
# MAGIC     Incurred_Half_Year_Nm STRING,
# MAGIC     Incurred_Half_Year_Nbr Double,
# MAGIC     HOLDY_CD STRING,
# MAGIC     Incurred_Julian_Dt_of_Year_Nbr Double,
# MAGIC     Incurred_Month_of_Year_Nm STRING,
# MAGIC     Incurred_Month_of_Year_Nbr Double,
# MAGIC     Incurred_Month_of_Year_Short_Nm STRING,
# MAGIC     Incurred_Quarter_of_Year_Nbr Double,
# MAGIC     Incurred_Week_of_Year_Nbr Double,
# MAGIC     Incurred_Year_and_Half_Year_Nbr Double,
# MAGIC     Incurred_Year_and_Quarter_Nbr Double,
# MAGIC     Incurred_Year_Month_Nbr Double,
# MAGIC     Incurred_Year Double,
# MAGIC     Incurred_Day_Type STRING,
# MAGIC     Incurred_Year_and_Half_Year_Nm STRING,
# MAGIC     Incurred_Year_and_Month_Nm STRING,
# MAGIC     Incurred_Year_and_Quarter_Nm STRING,
# MAGIC     Incurred_Month_Begin_Dt DATE,
# MAGIC     Incurred_Month_EndDt DATE,
# MAGIC     DefaultYearMonth STRING,
# MAGIC     INCRD_MNTH_YEAR_DASHBAORD STRING,
# MAGIC     MONTH_DIFFERENCE INTEGER,
# MAGIC     YEAR_MONTH_SORT INTEGER
# MAGIC    
# MAGIC    
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Incurred_Month
# MAGIC 
# MAGIC SELECT 
# MAGIC    
# MAGIC    CAST(DT AS DATE) AS DT,
# MAGIC     BUS_DAY_OF_MNTH_NBR,
# MAGIC     CY_AND_WEEK_NBR,
# MAGIC     DT_NBR,
# MAGIC     DAY_OF_MNTH_NBR,
# MAGIC     DAY_OF_WEEK_NM,
# MAGIC     DAY_OF_WEEK_NBR,
# MAGIC     DAY_OF_WEEK_SHRT_NM,
# MAGIC     DAY_TYPE_CD,
# MAGIC     FED_HOLDY_IND,
# MAGIC     HALF_YEAR_CD,
# MAGIC     HALF_YEAR_NM,
# MAGIC     HALF_YEAR_NBR,
# MAGIC     HOLDY_CD,
# MAGIC     JULIAN_DT_OF_YEAR_NBR,
# MAGIC     MNTH_OF_YEAR_NM,
# MAGIC     MNTH_OF_YEAR_NBR,
# MAGIC     MNTH_OF_YEAR_SHRT_NM,
# MAGIC     QTR_OF_YEAR_NBR,
# MAGIC     WEEK_OF_YEAR_NBR,
# MAGIC     YEAR_AND_HALF_YEAR_NBR,
# MAGIC     YEAR_AND_QTR_NBR,
# MAGIC     YEAR_MNTH_NBR,
# MAGIC     YEAR_NBR,
# MAGIC     DAY_TYPE_CD_NM,
# MAGIC     YEAR_AND_HALF_YEAR_NM,
# MAGIC     YEAR_AND_MNTH_NM,
# MAGIC     YEAR_AND_QTR_NM,
# MAGIC     CAST(MNTH_BGN_DT AS DATE) AS MNTH_BGN_DT,
# MAGIC     CAST(MNTH_END_DT AS DATE) AS MNTH_END_DT,
# MAGIC     DFLT_YEAR_MNTH_TXT,
# MAGIC    --(SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1 WHERE YEAR_MNTH_NBR < (SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1) ) AS LATEST_INCRD_MNTH,
# MAGIC    --CASE 
# MAGIC     --WHEN YEAR_MNTH_NBR = (SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1 WHERE YEAR_MNTH_NBR < (SELECT MAX(YEAR_MNTH_NBR) FROM HWBS_LH.DIM_PRDA_DT_1)) THEN 'Current'
# MAGIC     --WHEN YEAR_MNTH_NBR > (SELECT MAX(YEAR_MNTH_NBR)FROM HWBS_LH.DIM_PRDA_DT_1 WHERE YEAR_MNTH_NBR < (SELECT MAX(YEAR_MNTH_NBR) FROM 
# MAGIC     --HWBS_LH.DIM_PRDA_DT_1)) THEN 'Current + 1 Month (Advanced)'
# MAGIC     --ELSE 'Previous'
# MAGIC     --END AS LATEST_INCRD_MNTH_IND --
# MAGIC 
# MAGIC     
# MAGIC 
# MAGIC     CONCAT (
# MAGIC       MNTH_OF_YEAR_SHRT_NM, "'",CAST(CAST(YEAR_NBR AS INT)AS STRING)
# MAGIC     )AS INCRD_MNTH_YEAR_DASHBAORD,
# MAGIC 
# MAGIC   DATEDIFF(
# MAGIC     MONTH,
# MAGIC     TO_DATE(MNTH_BGN_DT),
# MAGIC     MAX(TO_DATE(MNTH_BGN_DT)) OVER ()
# MAGIC   ) AS MONTH_DIFFERENCE,
# MAGIC 
# MAGIC   (YEAR_NBR* 100 + MNTH_OF_YEAR_NBR) as YEAR_MONTH_SORT
# MAGIC     FROM  GOLD_LAKEHOUSE.dbo.DIM_PRDA_DT;
# MAGIC   


# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Funding_Chart_Field
# MAGIC (
# MAGIC     
# MAGIC --EDL_LOAD_DTM	TIMESTAMP
# MAGIC FUNDG_CF_KEY	DOUBLE,
# MAGIC --SNAP_YEAR_MNTH_NBR	DOUBLE,
# MAGIC Funding_Chart_Field_Cd	STRING,
# MAGIC Funding_Chart_Field	STRING,
# MAGIC Funding_Chart_Field_Type_Cd	STRING,
# MAGIC Funding_Type STRING,
# MAGIC Funding_Sub_Class_Cd	STRING,
# MAGIC Funding_Sub_Class	STRING,
# MAGIC Funding_Class_Cd	STRING,
# MAGIC Funding_Class	STRING,
# MAGIC FUNDG_CLS_LONG_DESC	STRING,
# MAGIC Funding_Type_Dashboard	STRING,
# MAGIC MEWA_IND	STRING,
# MAGIC ABF_IND	STRING    
# MAGIC 
# MAGIC );
# MAGIC 
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Funding_Chart_Field
# MAGIC 
# MAGIC SELECT 
# MAGIC --EDL_LOAD_DTM
# MAGIC FUNDG_CF_KEY,
# MAGIC --SNAP_YEAR_MNTH_NBR,
# MAGIC FUNDG_CF_CD,
# MAGIC FUNDG_CF_NM,
# MAGIC FUNDG_CF_TYPE_CD,
# MAGIC FUNDG_CF_TYPE_SHRT_DESC,
# MAGIC FUNDG_SUB_CLS_CD,
# MAGIC FUNDG_SUB_CLS_SHRT_DESC,
# MAGIC FUNDG_CLS_CD,
# MAGIC FUNDG_CLS_SHRT_DESC,
# MAGIC FUNDG_CLS_LONG_DESC,
# MAGIC FUNDG_TYPE_DSHBRD_NM,
# MAGIC MEWA_IND,
# MAGIC ABF_IND
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_FUNDG_CF; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Company_Chart_Field
# MAGIC 
# MAGIC (
# MAGIC   
# MAGIC --EDL_LOAD_DTM	TIMESTAMP
# MAGIC --EDL_RUN_ID	STRING
# MAGIC --EDL_SOR_CD	STRING
# MAGIC --KF_TMS	TIMESTAMP,
# MAGIC --EDL_SCRTY_LVL_CD	STRING
# MAGIC --EDL_LOB_CD	STRING
# MAGIC --EDL_EXTRNL_LOAD_CD	STRING
# MAGIC --EDL_CREAT_DTM	TIMESTAMP
# MAGIC --EDL_INCRMNTL_LOAD_DTM	TIMESTAMP
# MAGIC CMPNY_CF_KEY	DOUBLE,
# MAGIC SNAP_YEAR_MNTH_NBR	DOUBLE,
# MAGIC Company_Chart_Field_Cd STRING,
# MAGIC Company_Chart_Field	STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Company_Chart_Field
# MAGIC SELECT 
# MAGIC --EDL_LOAD_DTM	
# MAGIC --EDL_RUN_ID	
# MAGIC --EDL_SOR_CD	
# MAGIC --KF_TMS,
# MAGIC --EDL_SCRTY_LVL_CD	STRING
# MAGIC --EDL_LOB_CD	STRING
# MAGIC --EDL_EXTRNL_LOAD_CD	STRING
# MAGIC --EDL_CREAT_DTM	TIMESTAMP
# MAGIC --EDL_INCRMNTL_LOAD_DTM	TIMESTAMP
# MAGIC CMPNY_CF_KEY,
# MAGIC SNAP_YEAR_MNTH_NBR,
# MAGIC CMPNY_CF_CD	,
# MAGIC CMPNY_CF_NM
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_CMPNY_CF; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.MBU_Chart_Field
# MAGIC (
# MAGIC --EDL_LOAD_DTM	TIMESTAMP
# MAGIC --EDL_RUN_ID	STRING
# MAGIC --EDL_SOR_CD	STRING
# MAGIC KF_TMS	TIMESTAMP,
# MAGIC --EDL_SCRTY_LVL_CD	STRING
# MAGIC --EDL_LOB_CD	STRING
# MAGIC --EDL_EXTRNL_LOAD_CD	STRING
# MAGIC --EDL_CREAT_DTM	TIMESTAMP
# MAGIC --EDL_INCRMNTL_LOAD_DTM	TIMESTAMP
# MAGIC MBU_CF_KEY	DOUBLE,
# MAGIC --SNAP_YEAR_MNTH_NBR	DOUBLE
# MAGIC MBU_CF_CD STRING,
# MAGIC MBU_Chart_Field STRING,
# MAGIC MBU_BRND_TYPE_CD STRING,
# MAGIC MBU_Brand_Type STRING,
# MAGIC MBU_BRND_TYPE_LONG_DESC	STRING,
# MAGIC PROD_LINE_CD	STRING,
# MAGIC PROD_LINE_SHRT_DESC	STRING,
# MAGIC PROD_LINE_LONG_DESC	STRING,
# MAGIC Service_Area_State_Cd STRING,
# MAGIC Service_Area_State_Shortdesc STRING,
# MAGIC SRVCAREA_ST_LONG_DESC STRING,
# MAGIC LOB_CD STRING,
# MAGIC LOB STRING,
# MAGIC LOB_LONG_DESC STRING,
# MAGIC MBU_Sub_Class_Cd STRING,
# MAGIC MBU_Sub_Class STRING,
# MAGIC MBU_SUB_CLS_LONG_DESC STRING,
# MAGIC MBU_Class_Cd STRING,
# MAGIC MBU_Class STRING,
# MAGIC MBU_CLS_LONG_DESC STRING,
# MAGIC MBU_TYPE_CD	STRING,
# MAGIC MBU_TYPE STRING,
# MAGIC MBU_TYPE_LONG_DESC STRING,
# MAGIC MBU_Class_FullForm STRING,
# MAGIC MBU_Class_Sort DOUBLE,
# MAGIC BLCD_IND STRING,
# MAGIC MBU_CLS_DASHBOARD_NM STRING,
# MAGIC MBU_SUB_CLS_DASHBOARD_NM STRING,
# MAGIC STDNT_IND STRING,
# MAGIC PRFSNL_EMPLR_ORG_IND STRING,
# MAGIC LBR_AND_TRST_IND STRING,
# MAGIC CA_CHCE_IND	STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.MBU_Chart_Field
# MAGIC 
# MAGIC SELECT
# MAGIC --EDL_LOAD_DTM
# MAGIC --EDL_RUN_ID
# MAGIC --EDL_SOR_CD
# MAGIC KF_TMS,
# MAGIC --EDL_SCRTY_LVL_CD
# MAGIC --EDL_LOB_CD
# MAGIC --EDL_EXTRNL_LOAD_CD
# MAGIC --EDL_CREAT_DTM
# MAGIC --EDL_INCRMNTL_LOAD_DTM
# MAGIC MBU_CF_KEY,
# MAGIC --SNAP_YEAR_MNTH_NBR,
# MAGIC MBU_CF_CD,
# MAGIC MBU_CF_NM,
# MAGIC MBU_BRND_TYPE_CD,
# MAGIC MBU_BRND_TYPE_SHRT_DESC,
# MAGIC MBU_BRND_TYPE_LONG_DESC,
# MAGIC PROD_LINE_CD,
# MAGIC PROD_LINE_SHRT_DESC,
# MAGIC PROD_LINE_LONG_DESC,
# MAGIC SRVCAREA_ST_CD,
# MAGIC SRVCAREA_ST_SHRT_DESC,
# MAGIC SRVCAREA_ST_LONG_DESC,
# MAGIC LOB_CD,
# MAGIC LOB_SHRT_DESC,
# MAGIC LOB_LONG_DESC,
# MAGIC MBU_SUB_CLS_CD,
# MAGIC MBU_SUB_CLS_SHRT_DESC,
# MAGIC MBU_SUB_CLS_LONG_DESC,
# MAGIC MBU_CLS_CD,
# MAGIC MBU_CLS_SHRT_DESC,
# MAGIC MBU_CLS_LONG_DESC,
# MAGIC MBU_TYPE_CD,
# MAGIC MBU_TYPE_SHRT_DESC,
# MAGIC MBU_TYPE_LONG_DESC,
# MAGIC MBU_CF_CLS_NM,
# MAGIC MBU_CF_CLS_SORT_ORDR_NBR,
# MAGIC BLCD_IND,
# MAGIC MBU_CLS_DASHBOARD_NM,
# MAGIC MBU_SUB_CLS_DASHBOARD_NM,
# MAGIC STDNT_IND,
# MAGIC PRFSNL_EMPLR_ORG_IND,
# MAGIC LBR_AND_TRST_IND,
# MAGIC CA_CHCE_IND
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_MBU_CF; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Group_Zip
# MAGIC 
# MAGIC (
# MAGIC --EDL_LOAD_DTM	TIMESTAMP,
# MAGIC --EDL_RUN_ID	STRING,
# MAGIC --EDL_SOR_CD	STRING,
# MAGIC KF_TMS	TIMESTAMP,
# MAGIC --EDL_SCRTY_LVL_CD	STRING,
# MAGIC --EDL_LOB_CD	STRING,
# MAGIC --EDL_EXTRNL_LOAD_CD	STRING,
# MAGIC --EDL_CREAT_DTM	TIMESTAMP,
# MAGIC --EDL_INCRMNTL_LOAD_DTM	TIMESTAMP,
# MAGIC --SNAP_YEAR_MNTH_NBR	DOUBLE,
# MAGIC ZIP_KEY	DOUBLE,
# MAGIC Group_Zip STRING,
# MAGIC Group_City STRING,
# MAGIC Group_State_Abbreviation STRING,
# MAGIC Group_Latitude	DOUBLE,
# MAGIC Group_Longitude	DOUBLE,
# MAGIC Group_FIPS_County_Cd STRING,
# MAGIC Group_FIPS_County STRING,
# MAGIC Group_State	STRING,
# MAGIC RUC_CD	STRING,
# MAGIC RUC_DESC STRING,
# MAGIC RU_CD	STRING,
# MAGIC RU_NM	STRING,
# MAGIC AREA_PPLTN_CD	STRING,
# MAGIC AREA_PPLTN_NM	STRING,
# MAGIC NATL_ADI_RANK_NBR	DOUBLE,
# MAGIC ST_ADI_RANK_NBR	DOUBLE,
# MAGIC CBSA_CD	STRING,
# MAGIC CBSA_NM	STRING,
# MAGIC CNSUS_DVSN_CD	STRING,
# MAGIC CNSUS_DVSN_NM	STRING,
# MAGIC CNSUS_RGN_CD	STRING,
# MAGIC CNSUS_RGN_NM	STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Group_Zip
# MAGIC SELECT
# MAGIC --EDL_LOAD_DTM
# MAGIC --EDL_RUN_ID
# MAGIC --EDL_SOR_CD
# MAGIC KF_TMS,
# MAGIC --EDL_SCRTY_LVL_CD
# MAGIC --EDL_LOB_CD
# MAGIC --EDL_EXTRNL_LOAD_CD
# MAGIC --EDL_CREAT_DTM
# MAGIC --EDL_INCRMNTL_LOAD_DTM
# MAGIC --SNAP_YEAR_MNTH_NBR
# MAGIC ZIP_KEY,
# MAGIC ZIP_CD,
# MAGIC CITY_NM,
# MAGIC ST_CD,
# MAGIC LATD_NBR,
# MAGIC LNGTD_NBR,
# MAGIC FIPS_CNTRY_CD,
# MAGIC FIPS_CNTRY_NM,
# MAGIC ST_NM,
# MAGIC RUC_CD,
# MAGIC RUC_DESC,
# MAGIC RU_CD,
# MAGIC RU_NM,
# MAGIC AREA_PPLTN_CD,
# MAGIC AREA_PPLTN_NM,
# MAGIC NATL_ADI_RANK_NBR,
# MAGIC ST_ADI_RANK_NBR,
# MAGIC CBSA_CD,
# MAGIC CBSA_NM,
# MAGIC CNSUS_DVSN_CD,
# MAGIC CNSUS_DVSN_NM,
# MAGIC CNSUS_RGN_CD,
# MAGIC CNSUS_RGN_NM
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_ZIP; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE_HWBS
# MAGIC 
# MAGIC (
# MAGIC --EDL_LOAD_DTM	TIMESTAMP,
# MAGIC --EDL_RUN_ID	STRING,
# MAGIC --EDL_SOR_CD	STRING,
# MAGIC KF_TMS	TIMESTAMP,
# MAGIC --EDL_SCRTY_LVL_CD	STRING,
# MAGIC --EDL_LOB_CD	STRING,
# MAGIC --EDL_EXTRNL_LOAD_CD	STRING,
# MAGIC --EDL_CREAT_DTM	TIMESTAMP,
# MAGIC --EDL_INCRMNTL_LOAD_DTM	TIMESTAMP,
# MAGIC --SNAP_YEAR_MNTH_NBR	DOUBLE,
# MAGIC RWRD_TYPE_KEY	DOUBLE,
# MAGIC RWRD_TYPE_CD	STRING,
# MAGIC RWRD_TYPE_DESC	STRING,
# MAGIC ACCT_CTGRY_CD	STRING,
# MAGIC ACTVTY_SRC_NM	STRING,
# MAGIC ACTVTY_NM	STRING,
# MAGIC ACTVTY_VNDR_NM	STRING,
# MAGIC MLSTN_NM	STRING,
# MAGIC RWRD_CTGRY_NM	STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE_HWBS
# MAGIC SELECT
# MAGIC --EDL_LOAD_DTM
# MAGIC --EDL_RUN_ID
# MAGIC --EDL_SOR_CD
# MAGIC KF_TMS,
# MAGIC --EDL_SCRTY_LVL_CD
# MAGIC --EDL_LOB_CD
# MAGIC --EDL_EXTRNL_LOAD_CD
# MAGIC --EDL_CREAT_DTM
# MAGIC --EDL_INCRMNTL_LOAD_DTM
# MAGIC --SNAP_YEAR_MNTH_NBR,
# MAGIC RWRD_TYPE_KEY,
# MAGIC RWRD_TYPE_CD,
# MAGIC RWRD_TYPE_DESC,
# MAGIC ACCT_CTGRY_CD,
# MAGIC ACTVTY_SRC_NM,
# MAGIC ACTVTY_NM,
# MAGIC ACTVTY_VNDR_NM,
# MAGIC MLSTN_NM,
# MAGIC RWRD_CTGRY_NM
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_RWRD_TYPE; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.JAA
# MAGIC (
# MAGIC --EDL_LOAD_DTM	TIMESTAMP,
# MAGIC --EDL_RUN_ID	STRING,
# MAGIC --EDL_SOR_CD	STRING,
# MAGIC KF_TMS	TIMESTAMP,
# MAGIC --EDL_SCRTY_LVL_CD	STRING,
# MAGIC --EDL_LOB_CD	STRING,
# MAGIC --EDL_EXTRNL_LOAD_CD	STRING,
# MAGIC --EDL_CREAT_DTM	TIMESTAMP,
# MAGIC --EDL_INCRMNTL_LOAD_DTM	TIMESTAMP,
# MAGIC JAA_KEY	DOUBLE,
# MAGIC FUNDG_and_MBU_CD STRING,
# MAGIC JAA_IND	STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.JAA
# MAGIC SELECT
# MAGIC --EDL_LOAD_DTM
# MAGIC --EDL_RUN_ID
# MAGIC --EDL_SOR_CD
# MAGIC KF_TMS,
# MAGIC --EDL_SCRTY_LVL_CD
# MAGIC --EDL_LOB_CD
# MAGIC --EDL_EXTRNL_LOAD_CD
# MAGIC --EDL_CREAT_DTM
# MAGIC --EDL_INCRMNTL_LOAD_DTM
# MAGIC JAA_KEY,
# MAGIC JAA_CD,
# MAGIC JAA_NM
# MAGIC from GOLD_LAKEHOUSE.dbo.DIM_PRDA_JAA; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Med_Network
# MAGIC (
# MAGIC NTWK_KEY DOUBLE,
# MAGIC LOB_PARTN_ID DOUBLE,
# MAGIC NTWK_ID STRING,
# MAGIC NTWK_NM STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Med_Network
# MAGIC 
# MAGIC SELECT
# MAGIC NTWK_KEY,
# MAGIC LOB_PARTN_ID,
# MAGIC NTWK_ID,
# MAGIC NTWK_NM
# MAGIC from GOLD_LAKEHOUSE.dbo.WORK_DIM_NTWK_CUBE; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Med_NTWK_LKUP_LVL1
# MAGIC (
# MAGIC Network_Number	STRING,
# MAGIC LOB_PARTN_ID	DOUBLE,
# MAGIC Network_Name	STRING,
# MAGIC Network_State	STRING,
# MAGIC PPO_EPO_IND	STRING,
# MAGIC HMO_POS_IND	STRING,
# MAGIC LG_Ind	STRING,
# MAGIC SG_Ind STRING,
# MAGIC IND_IND STRING,
# MAGIC Geographical_Coverage	STRING,
# MAGIC Supports_GK	STRING,
# MAGIC Broad_Network	STRING,
# MAGIC Tiered_Network	STRING,
# MAGIC HPN	STRING,
# MAGIC Anthem_Link	STRING,
# MAGIC LCOM STRING,
# MAGIC NEHP	STRING,
# MAGIC BlueCard_PPO	STRING,
# MAGIC JAA	STRING,
# MAGIC ACTV_IND	STRING,
# MAGIC TRRTRL_RGN_TXT	STRING,
# MAGIC NATL_BSNS_SGMNT_IND	STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Med_NTWK_LKUP_LVL1
# MAGIC SELECT
# MAGIC NTWK_NBR,
# MAGIC LOB_PARTN_ID,
# MAGIC NTWK_NM,
# MAGIC ST_RGN_CD_NM,
# MAGIC PPO_EPO_IND,
# MAGIC HMO_POS_IND,
# MAGIC LG_IND,
# MAGIC SG_IND,
# MAGIC INDIV_IND,
# MAGIC GGRPHCL_CVRG_AREA_TXT,
# MAGIC SPRT_GTKPR_IND,
# MAGIC BROAD_NTWK_IND,
# MAGIC TIERD_NTWK_IND,
# MAGIC HPN_IND,
# MAGIC ATH_LINK_IND,
# MAGIC LCOM_IND,
# MAGIC NEHP_IND,
# MAGIC BLCD_PPO_IND,
# MAGIC JNT_ADMNSTR_ACCT_IND_TXT,
# MAGIC ACTV_IND,
# MAGIC TRRTRL_RGN_TXT,
# MAGIC NATL_BSNS_SGMNT_IND
# MAGIC from GOLD_LAKEHOUSE.dbo.WORK_NTWK_PA_CUBE; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.Med_NTWK_LKUP_LVL2 
# MAGIC (
# MAGIC Network_ID	STRING,
# MAGIC Network_Number	STRING,
# MAGIC LOB_PARTN_ID	DOUBLE,
# MAGIC REF_REQ	STRING,
# MAGIC PCP_REQ	STRING,
# MAGIC Custom	STRING,
# MAGIC Select_Network	STRING
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.Med_NTWK_LKUP_LVL2
# MAGIC SELECT
# MAGIC NTWK_ID,
# MAGIC NTWK_NBR,
# MAGIC LOB_PARTN_ID,
# MAGIC RFRL_RQRD_IND_CD,
# MAGIC PCP_RQRD_IND_CD,
# MAGIC CSTM_NTWK_IND_CD,
# MAGIC SLCT_NTWK_IND
# MAGIC from GOLD_LAKEHOUSE.dbo.WORK_NTWK_LVL_2_XWALK; 

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC 
# MAGIC CREATE OR REPLACE TABLE GOLD_LAKEHOUSE.dbo.FACT_PROD_ADMNSTRN_NTWK_HWBS 
# MAGIC (
# MAGIC NTWK_KEY DOUBLE,
# MAGIC ADMNSTRN_NTWK_ID STRING,
# MAGIC NTWK_TIER_ID DOUBLE
# MAGIC 
# MAGIC );
# MAGIC INSERT INTO GOLD_LAKEHOUSE.dbo.FACT_PROD_ADMNSTRN_NTWK_HWBS
# MAGIC SELECT
# MAGIC 
# MAGIC NTWK_KEY ,
# MAGIC ADMNSTRN_NTWK_ID ,
# MAGIC NTWK_TIER_ID 
# MAGIC 
# MAGIC from GOLD_LAKEHOUSE.dbo.FACT_PROD_ADMNSTRN_NTWK;

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# MARKDOWN ********************

# PA DGTL
